### ISSUE TITLE
Feature Request:  Upload Attachment ID

### ISSUE THREAD

**Issue by Racura** [valendesigns/option-tree#112]
Is it possible to get an upload alternative that uses the attachment id, instead of a absolute url?

So that I can do something like:
    echo wp_get_attachment_image( ot_get_option('logo'), 'medium');

**Comment by pixeldesignstudio** [comment]
Hi everyone,

sorry, I don't get it. Where do I have to make changes to retrieve the ID instead of the URL?
Now I am simple passing the option to an Variable:

$brand_logo = ot_get_option( 'brand_logo');

Thx
