### ISSUE TITLE
OT 2.1.3: Undefined function ot_get_option

### ISSUE THREAD

**Issue by BassemN** [valendesigns/option-tree#146]
Hi,

Great plugin keep up the good work

After I upgraded to OptionTree 2.1.3, I got this error message

Fatal error: Call to undefined function ot_get_option() in /wp-content/themes/mytheme/functions.php on line 127

Please advise

**Comment by nuriarai** [comment]
But then, the plugin is losing the best of its interest, so now I can't define constants in functions.php that are used all around the theme with the values of the option_tree o simply call ot_get_option() from a class or function that are created from functions.php, not inside a theme template. :(

Anyway, thanks for your work.

**Comment by valendesigns** [comment]
I've built many custom themes using OT and the availability of this function has never been a factor when creating complex functionality. I don't feel there are any limitations here. It's not difficult to write your code in a way that runs through a filter first. You  only need to change your approach slightly. 

What are you doing that you need to use that function before a theme is setup? Can you give me a specific use-case that you cannot figure out how to rewrite?

**Comment by nuriarai** [comment]
Thanks for your answer! I'm writing a reservation process, in a hugue site with a lot of other plugins and functionalities that I can't modify or event touch. So, in functions.php we call different files with functions and classes. Between others I call from it to global-variables.php and Reserva.php, the first is where I put the general variables that will be accessed from the clas Reserva.php and the templates that we use for show the forms in the process. So at the very beginning of each template, we call the class Reserva. an example:

<?php
/**
 * Template Name: Reserva Refugis (I)
 */
// L'objecte reserva manega tot el procès de reserva
$reserva = new Reserva();
$reserva->setPas(3);
if(isset($_POST['formulari_reserva'])) {
    $preus = $reserva->preusXRefugi();
	$reserva->validaReservaForm();
	if($reserva->form_valid_reserva) {
		$destination_url = URL_PAGE_RESERVA_PAS2;
		header("Location:$destination_url");
		exit();
		}
} 
get_header();
// Obtenim la llista de refugis
$refugis = get_posts( array(
    'numberposts' => -1,
    'post_type' => 'refugi',
)); ....

Inside the class Reserva() I use information that would be called with ot_get_option() directly or from a constant in global-variables, and also the constant URL_PAGE_RESERVA_PAS2 it would be defined in global-variables.php getting the value from ot_get_option(). 

Maybe I'm losing something or doing something wrong? Thanks for your interest! :)

**Comment by nuriarai** [comment]
Thanks for your answer! I'm writing a reservation process, in a hugue site
with a lot of other plugins and functionalities that I can't modify or
event touch. So, in functions.php we call different files with functions
and classes. Between others I call from it to global-variables.php and
Reserva.php, the first is where I put the general variables that will be
accessed from the clas Reserva.php and the templates that we use for show
the forms in the process. So at the very beginning of each template, we
call the class Reserva. an example:

<?php
/**

   - Template Name: Reserva Refugis (I) */ // L'objecte reserva manega tot
   el procès de reserva $reserva = new Reserva(); $reserva->setPas(3);
   if(isset($_POST['formulari_reserva'])) { $preus = $reserva->preusXRefugi();
   $reserva->validaReservaForm(); if($reserva->form_valid_reserva) {
   $destination_url = URL_PAGE_RESERVA_PAS2;
   header("Location:$destination_url"); exit(); } } get_header(); // Obtenim
   la llista de refugis $refugis = get_posts( array( 'numberposts' => -1,
   'post_type' => 'refugi', )); ....

Inside the class Reserva() I use information that would be called with
ot_get_option() directly or from a constant in global-variables, and also
the constant URL_PAGE_RESERVA_PAS2 it would be defined in
global-variables.php getting the value from ot_get_option().

Maybe I'm losing something or doing something wrong? Thanks for your
interest! :)



Núria Ramoneda i Aiguadé
http://www.paddingzero.com
Front-end development, UX & Wordpress
Tel. +34 619.05.11.98

2015-03-18 13:27 GMT+01:00 Derek Herman <notifications@github.com>:

**Comment by inside83** [comment]
Hey guys
I know it's a bit old.
I'm trying to make it work but adding this to my functions.php gets me an error

```
function ot_get_option( $option_id, $default = '' ) {
	// Get the saved options.
	$options = get_option( ot_options_id() );
	// Look for the saved value.
	if ( isset( $options[ $option_id ] ) && '' !== $options[ $option_id ] ) {
		return ot_wpml_filter( $options, $option_id );
	}
	return $default;
}
add_action( 'after_setup_theme', 'ot_get_option', 2 );

function ot_options_id() {
	return apply_filters( 'ot_options_id', 'option_tree' );
}
add_action( 'after_setup_theme', 'ot_options_id', 2 );

function ot_wpml_filter( $options, $option_id ) {
	// Return translated strings using WMPL.
	if ( function_exists( 'icl_t' ) ) {
			$settings = get_option( ot_settings_id() );
			if ( isset( $settings['settings'] ) ) {
				foreach ( $settings['settings'] as $setting ) {
					// List Item & Slider.
				if ( $option_id === $setting['id'] && in_array( $setting['type'], array( 'list-item', 'slider' ), true ) ) {
						foreach ( $options[ $option_id ] as $key => $value ) {
							foreach ( $value as $ckey => $cvalue ) {
								$id      = $option_id . '_' . $ckey . '_' . $key;
							$_string = icl_t( 'Theme Options', $id, $cvalue );
								if ( ! empty( $_string ) ) {
									$options[ $option_id ][ $key ][ $ckey ] = $_string;
							}
						}
					}
						// List Item & Slider.
				} elseif ( $option_id === $setting['id'] && 'social-links' === $setting['type'] ) {
						foreach ( $options[ $option_id ] as $key => $value ) {
							foreach ( $value as $ckey => $cvalue ) {
								$id      = $option_id . '_' . $ckey . '_' . $key;
							$_string = icl_t( 'Theme Options', $id, $cvalue );
								if ( ! empty( $_string ) ) {
									$options[ $option_id ][ $key ][ $ckey ] = $_string;
							}
						}
					}
						// All other acceptable option types.
				} elseif ( $option_id === $setting['id'] && in_array( $setting['type'], apply_filters( 'ot_wpml_option_types', array( 'text', 'textarea', 'textarea-simple' ) ), true ) ) {
						$_string = icl_t( 'Theme Options', $option_id, $options[ $option_id ] );
						if ( ! empty( $_string ) ) {
							$options[ $option_id ] = $_string;
					}
				}
			}
		}
	}
		return $options[ $option_id ];
}
add_action( 'after_setup_theme', 'ot_wpml_filter', 2 );
```

**Comment by inside83** [comment]
bump...
