### ISSUE TITLE
Feature request: Repeatable fields

### ISSUE THREAD

**Issue by jaldesai** [valendesigns/option-tree#176]
Hi again Derek, 

Hope you are doing good. I have a feature request for OptionTree. How about adding repeatable fields option to types like textbox, textarea and upload? 

In the setting panel, the admin can select whether the current setting would be a repeatable field (let the admin know that "This will only affect the Textbox, Textarea and Upload option type." ). This will add a plus button (+) beside the field in Theme Options. And clicking it would apparently add another instance of the field.

**Comment by valendesigns** [comment]
Went a different way and I have no immediate plans to tackle this. If it becomes something I want to do later I'll reopen.

**Comment by ollietreend** [comment]
That's a shame – this feature would be really useful. +1 for this, if ever you do decide you want to implement it.
