### ISSUE TITLE
Feature request: theme user import/export

### ISSUE THREAD

**Issue by mheesters** [valendesigns/option-tree#259]
Hi,

I'm running the plugin in theme mode and i want the end-user to be able export/import his theme settings. Just like you would do in standalone mode in the settings screen.

I currently made my own solution by adding 2 textareas and using those for import/export. See code below.

But i was wondering if there are any plans (or there is an option i missed) to build this in the current plugin. For example by giving the ability to add a 'import' and 'export' field.

```php
/**
 * Function updates an optiontree textarea field with the current themetopions export data
 * @param  array $options Current set options through option-tree
 */
function showExport($options){
	$serialized=$options;
	$serialized = ! empty( $serialized ) ?  ot_encode( serialize( $serialized ) ) : ''; // serialize the current options
	$options['settings_export']=$serialized; // update current options array, update the textarea field named 'settings_export' with current serialized options
	update_option( ot_options_id(), $options ); // update the optiontree theme options in the database
}
add_action( 'ot_after_theme_options_save','showExport',11); // hook after normal save action

/**
 * Import theme-options in option-tree from optiontree textarea field
 * @param  array $options [Current set options through option-tree
 */
function doImport($options){
	// if the import field is filled
	if ($options['settings_import'] != ''){
		$options=unserialize(ot_decode($options['settings_import'])); // unserialize
		update_option( ot_options_id(), $options ); // and overwrite the current theme-options
	}
}
action( 'ot_after_theme_options_save','doImport',12); // hook after normal save action, and export update
```

**Comment by rvpatel** [comment]
![Image of Yaktocat](https://cloud.githubusercontent.com/assets/6005590/4990882/afcd7a44-698d-11e4-8593-74468440b101.jpg)

Above define screen on option page on define export option?
how we can add on theme options page?

i have applied all filter which u have define but export option display on tree option menu

**Comment by zhuangpan** [comment]
@rvpatel Hi,Did you solve the problem?

**Comment by rvpatel** [comment]
@zhuangpan 
This one not a issue just says this one possible but now i have add separate page menu for import & export.

**Comment by zhuangpan** [comment]
@rvpatel Can you tell me? thanks.

**Comment by rvpatel** [comment]
@zhuangpan 
See more info  if not manage please contact me:
#197 
#173

**Comment by zhuangpan** [comment]
@rvpatel I want to add my option. just like you.
In export option.
You can see in Figure successfully added.
