### ISSUE TITLE
Feature Request: Google Fonts Array for Typography Filter

### ISSUE THREAD

**Issue by Pixelous** [valendesigns/option-tree#30]
Will be greate to have a Google Fonts array for Typography filter. Maybe this would be helpful http://phat-reaction.com/googlefonts.php and http://stackoverflow.com/questions/8547009/how-to-deserialize-this-string-into-a-php-array-of-key-value-pairs Thanks.

**Comment by Lifestohack** [comment]
Can you please share with me? I am developing the theme with option tree, I need it.

**Comment by CapitalH** [comment]
@Lifestohack Please give me a couple of days and I will create a gist and will share the link here. For now just go on with your development and consider adding google fonts to the Option Tree in theme mode a done deal. Sorry if you have to wait I really don't have the luxury of time these days.

**Comment by valendesigns** [comment]
Closing in favor of PR #444
