### ISSUE TITLE
Display Option Tree field as a column in a CPT's admin panel view

### ISSUE THREAD

**Issue by IntricatePixels** [valendesigns/option-tree#302]
Hi Derek,

Not sure if this has been already asked before, looked through the repo here but could not find anything.

I'm using OT in theme mode for my child theme.  I have a custom post type, let's say called "bikes".  Using Option Tree, i have registered a field to the "bikes" cpt called "featured bike".  Code example:

```
add_action( 'admin_init', 'tb_bikes_meta_boxes' );

function tb_bikes_meta_boxes() 
{
    $tb_bikes_meta_boxes = array(
        'id'        => 'tb_bikes_meta_boxes',
        'title'     => 'Bike Info',
        'desc'      => '',
        'pages'     => array( 'bikes' ),
        'context'   => 'advanced',
        'priority'  => 'low',
        'fields'    => array( 
            array(
                'label'       => 'Featured Bike?',
                'id'          => '_featured_bike_checkbox',
                'type'        => 'checkbox',
                'desc'        => '',
                'choices'     => array(
                                    array (
                                    'label'       => 'Yes',
                                    'value'       => 'Yes'
                                    )
                    ),
                'std'         => '',
                'rows'        => '',
                'post_type'   => '',
                'taxonomy'    => '',
                'class'       => ''
            ))
    );
    ot_register_meta_box( $tb_bike_meta_boxes ); 
}
```

Now I want to display this option, the "Featured Bike" checkbox, in the admin panel view for the Bikes cpt as a column but also in the "Quick Edit" menu, so that the admin user can see what this option was set to or change it using the "Quick Edit" option without having to go into the post itself to make the change.

I have attached a screenshot illustrating this.

![ot_custom_field_in_cpt_admin_view](https://cloud.githubusercontent.com/assets/1676144/2706518/be4ef818-c492-11e3-8a5c-99b38219a6a2.png)

Is this possible?

**Comment by valendesigns** [comment]
The best I can do is give you some sample code that you can use to add the column yourself. Adding OT meta boxes to the quick edit is not something I want or plan to do anytime soon. However, displaying the value of a meta box is not that difficult.

```PHP
// Add the column
function my_manage_posts_columns( $columns ) {
	$new_columns = array(
		'demo_show_gallery' => __( 'Show Gallery', 'ThemeName' )
	);
  return array_merge( $columns, $new_columns );
}
add_filter( 'manage_posts_columns' , 'my_manage_posts_columns' );

// Manage the value displayed
function my_manage_posts_custom_column( $column, $post_id ) {
  switch ( $column ) {
    case 'demo_show_gallery' :
      $demo_show_gallery = get_post_meta( $post_id, 'demo_show_gallery', true );
        if ( $demo_show_gallery )
          echo $demo_show_gallery;
      break;
  }
}
add_action( 'manage_posts_custom_column' , 'my_manage_posts_custom_column', 10, 2 );
```

Sorry it has taken so long to respond back.
