### ISSUE TITLE
dynamic.css permissions on some servers

### ISSUE THREAD

**Issue by BoragThungg** [valendesigns/option-tree#315]
Hi, Brilliant plugin. Thank you. 
We've developed a theme for a client for him to resell but his test server requires the dynamic.css file to be at least 666 in order to save the css changes. Our servers have no such issues as the default 644 works perfectly. But the client says this could be an issue for him selling the theme. Is this supposed to be a manual permissions change by an end user who buys a theme that uses your options plugin or are we doing something wrong?

Thanks again for a great plugin.

**Comment by valendesigns** [comment]
I've opened a new pull request where we can discuss this feature moving forward. Closing in favor or #448
