### ISSUE TITLE
How to retrieve an option in functions.php

### ISSUE THREAD

**Issue by gerardbm** [valendesigns/option-tree#316]
Hello, I have a new question.

First of all, it's really good your framework. I'm migrating the options from my own options page (it was too simple) and everything works as espected.

But now I'm creating all the settings and changing my old get_option() to the new ot_get_option(). If I try to enable/disable some options of my theme, included in functions.php, it only works if I use it inside of a function, but not outside, when I want to enable/disable some functions at the same time.

For example:

if (ot_get_option('szt_strip_category') === "on") {
function 1...
function 2...
function 3...
}

It returns «Fatal error: Call to undefined function ot_get_option() in [...]/functions.php on line 228».

I also tried to export the settings file and then load it at the beginning of the file functions.php, but it didn't work.

When I used before the simple get_option() it worked. Do you think I can fix it easily?

Thank you for your time! :)

**Comment by MohammadAbedini** [comment]
i am using of Option Tree framwork in WP.
i have important issue:

i added product category in option themes section. already i want use from this in product loop.

<?php
              $args = array(
              'post_type' => 'product',
              'posts_per_page' => 6,
              'product_cat' => ot_get_option('woocommerce-cat'),
              'orderby' => 'date'
              );
              $loop = new WP_Query( $args );
              while ( $loop->have_posts() ) : $loop->the_post(); global $product; ?>


i put [   ot_get_option('woocommerce-cat')   ] code front of product_cat line but not work. what is right method?

NOT WORK >>>  'product_cat' => ot_get_option('woocommerce-cat'),
