### ISSUE TITLE
Creating custom options for "List-item" option in Option Tree

### ISSUE THREAD

**Issue by danielchikaka** [valendesigns/option-tree#329]
Hey guys, I have a problem, I need to change the default options for a “List-item” option in Option tree . Right now the default are “Title/Image/Link/Descriptions” .. I want to remove them and add my own. I have written this code: 

``` PHP
array(
  'id'          => 'academic_success_content',
  'label'       => 'Academic Success Content',
  'desc'        => 'Enter the academic success content. It will appear in the home page in list items format',
  'std'         => '',
  'type'        => 'list-item',
  'section'     => 'academic_perfomance',
  'settings'    => array( 
    array(
      'id'          => 'academic_success',
      'label'       => 'Academic Success',
      'type'        => 'textarea-simple',
    )
  )
)
```

but when i preview the themes options , the default list item "title" is still there and i only want to see the Academic Success textarea. What should i do?

**Comment by ericbrockman** [comment]
How do you delete all options except the title? Just to make a simple list without any content or images, etc...

**Comment by valendesigns** [comment]
There is a filter you can use to filter the settings for a list-item type that will do what you want. I'm on my phone and don't know it off hand. I'll check when I get back in front of a computer.

**Comment by valendesigns** [comment]
@ericbrockman 
```PHP
function filter_ot_list_item_settings( $settings, $id ) {

  // Title only
  if ( 'your_option_id' === $id ) {
    return array();
  }

  return $settings;
}
add_filter( 'ot_list_item_settings', 'filter_ot_list_item_settings', 10, 2 );
```

**Comment by ericbrockman** [comment]
Thanks @valendesigns !

**Comment by ericbrockman** [comment]
Is it possible to add some of the fields and not others, I know the `title` is required, but how would you add say just the `title` and the `image`?
