### ISSUE TITLE
Replace "load_template" with "require"

### ISSUE THREAD

**Issue by bitcommit** [valendesigns/option-tree#335]
Hello,

In the documentation you're suggesting to use `load_template` to load OptionTree:

``` php
/**
 * Required: include OptionTree.
 */
load_template( trailingslashit( get_template_directory() ) . 'option-tree/ot-loader.php' );`
```

The `load_template()` function is not intended for non-template files. Its purpose is to offer a fallback when loading a template file that is missing. For example if you're calling `load_template('page-custom.php')` and that `page-custom.php` is missing then it will attempt to load `page.php` instead.

This function can also be used in order to allow plugins to override the template used: http://codex.wordpress.org/Function_Reference/load_template

Using this function in this context to load OptionTree does not add any functionality compared to a simple `require` and is a performance hit.

**Comment by mdmayankpatel** [comment]
It's Working fine in option tree WordPress 
/**
     * Load a file
     *
     * @return    void
     *
     * @access    private
     * @since     2.0.15
     */
    private function load_file( $file ){

      load_template($file );

    }
