### ISSUE TITLE
Feature Request: Allowing textarea via filter

### ISSUE THREAD

**Issue by ghost** [valendesigns/option-tree#342]
I'm using TinyMCE inside meta boxes, so I've had to edit two files:

1) includes/ot-meta-box-api.php
Line 120
Comment out

```
/* only allow simple textarea due to DOM issues with wp_editor() */ 
// if ( $_args['type'] == 'textarea' )
//  $_args['type'] = 'textarea-simple';
```

2) /includes/ot-functions-admin.php
Line 3859

```
/* only allow simple textarea inside a list-item due to known DOM issues with wp_editor() */
// if ( $_args['type'] == 'textarea' )
// $_args['type'] = 'textarea-simple';
```

Is it possible to create a filter for these so I don't have to edit core? Just for those of us who understand the risks of using TinyMCE?

**Comment by AlexMinaev** [comment]
@valendesigns 
I've added this filter and it works fine in metaboxes, but in "list item" when I press add new item, textarea shown but editor not work correctly, when I click "visual" tab I see js error http://prntscr.com/7egmey can you look on it. Thanks!
I'm using WordPress 4.2.2 and OT 2.5.5

**Comment by samh87** [comment]
Same issue for me, the textarea hotfix isn't working correctly on the latest OT.

**Comment by amitbiswas06** [comment]
Dear @valendesigns ,

First, thank you for this awesome plugin. I know that everything is not possible to do with a free plugin. But this particular issue is really so close to be resolved! I am getting same issue exactly as @AlexMinaev has described. 

The "textarea" is working good in meta. But inside "list-item", it has some visual issue. When we are adding a list item, the visual editor buttons are not there, but after saving the post or as draft, the visual editor works well with all facilities. 

Can you help? Or if anyone has found the solution, please let me know.

Thank you so much again.

**Comment by spaxter** [comment]
Same issue... Can you help please?
