### ISSUE TITLE
I have to load the options page twice after editing them

### ISSUE THREAD

**Issue by gerardbm** [valendesigns/option-tree#346]
Good morning. When I add new options I have to  r̶e̶s̶e̶t̶ load the options page twice in order to make them appear in the options page. Is there a way to avoid this? I'm not sure if it's an issue or a problem of my installation/configuration.

It wouldn't be a problem, actually. But if I want to add new options in a future (for the next versions of my WordPress theme), I don't like that my clients have to  r̶e̶s̶e̶t̶ load their options for every theme update.

Thanks in advance ;)

**Comment by valendesigns** [comment]
Load the settings on the 'init' action instead of `admin_init` and add a check for is_admin() and it will work. I'll update the `theme-options.php` export file too.

**Comment by gerardbm** [comment]
Thanks, this is good!

I'm not an expert on programming, so I think I'm doing something wrong because it still needs two loads. This is my code:

In functions.php directly:

```php
// Required: set 'ot_theme_mode' filter to true.
add_filter( 'ot_theme_mode', '__return_true' );

// This will hide the settings & documentation pages.
add_filter( 'ot_show_pages', '__return_false' );

// This will hide the "New Layout" section on the Theme Options page.
add_filter( 'ot_show_new_layout', '__return_false' );

// Required: include OptionTree.
load_template( trailingslashit( get_template_directory() ) . 'option-tree/ot-loader.php' );
```

Then I have an 'after_setup_theme' action to load some 'add_theme_support' functions, register menus, etc.

Then I load the settings:

```php
function load_settings(){

	if( is_admin() ) {

		// Theme Options
		load_template( trailingslashit( get_template_directory() ) . 'theme-options/options.php' );

		// Options Filters
		load_template( trailingslashit( get_template_directory() ) . 'theme-options/options-ot-filters.php' );

		// Theme Meta Boxes
		load_template( trailingslashit( get_template_directory() ) . 'theme-options/meta-boxes.php' );
	}

}

add_action('init', 'load_settings');
```

And finally I wrap the functions on the 'after_theme_setup' action to be able to use the 'ot_get_option()' function in the functions.php file. I thought it was needed the priority 2 but it works without it.

Am I missing something?

Thanks for your time, Derek. Your options framework is the best.

**Comment by valendesigns** [comment]
I don't see the benefits of using `load_template`, I do the following...
```PHP
require( trailingslashit( get_template_directory() ) . 'theme-options/options.php' );
```
I don't think that's your problem though, but just something that stood out. 

Try setting the `init` action to a lower priority like 1-9.

**Comment by gerardbm** [comment]
Ops! I was loading the settings on the 'init' action, but then my options.php file had an 'admin_init' action at the top. I didn't understand you at the beginning, hehe.

It works perfect, so this is solved! ;-)
