### ISSUE TITLE
Call to undefined function ot_get_media_post_ID()

### ISSUE THREAD

**Issue by RobbyMcCullough** [valendesigns/option-tree#349]
Hi there! Thanks for working on and releasing this plugin! I am running into an issue when using Option Tree with my plugin, the [FastLine Page Builder](http://themes.fastlinemedia.com). Once both plugins are installed and activated, any time we launch our page builder on a page the following error is thrown:

Fatal error: Call to undefined function ot_get_media_post_ID() in /home/fastr/public_html/chameleon/wp-content/plugins/option-tree/ot-loader.php on line 686

Any thoughts on why this might be happening? I would be happy to help dig into the source and fix the issue, I just need some direction =D. Thanks much!

**Comment by demetrius143** [comment]
I know this post and question is super old but here is a quick fix for those of you who are having plugin conflict in admin:
`

      if (!is_object($post) && function_exists('ot_get_media_post_ID'))
        $settings['post']['id'] = ot_get_media_post_ID();
`
