### ISSUE TITLE
ot_get_option() not working in a page template?

### ISSUE THREAD

**Issue by jackhorton** [valendesigns/option-tree#371]
Hi, I am experiencing some very odd behavior with `ot_get_option()`.  Normally, `ot_get_option("header-image")` is called from header.php in our theme and works just fine, however we are making a custom home page using a page template - one that hides the normal header image, and uses it within the page template itself. When I try to use the same function call in the page template, though, nothing shows up.  Any idea why this is happening?

I saw #146 however because its a page template, the theme should already be loaded, no?

**Comment by manukmsv** [comment]
// Get the value saved on Theme Options Page
$header-image = ot_get_option( 'header-image' );

// Get the value saved for a Page, Post or CPT ( Within the loop )
$header-image = get_post_meta( $post->ID, 'header-image', true );

// Wrap the value in a P tag and echo it
echo wpautop( $header-image );
