### ISSUE TITLE
Add readonly to datepicker

### ISSUE THREAD

**Issue by sparkdevelopment** [valendesigns/option-tree#373]
Can an additional parameter be added for datepicker (and I guess date/time picker too) to add:
```
readonly="readonly" 
```
to the html input element. This prevents the user from entering the date via the keyboard, essential when trying to prevent the user entering a different date format.

**Comment by valendesigns** [comment]
I'll add a filter to make this readonly for 2.5.0

**Comment by valendesigns** [comment]
Filters added to the 2.5.0 branch. Cheers!

**Comment by sparkdevelopment** [comment]
Thanks Derek!
