### ISSUE TITLE
Has anyone used TinyMCE in a modal / thickbox?

### ISSUE THREAD

**Issue by themovation** [valendesigns/option-tree#379]
I think it would be solve a lot of issues to load TinyMCE in a thickbox / modal vs editing in directly in a meta box. Very similar to Visual Composer. WordPress already has issues with drag / drop and there are other issues as well. I think a lot of people would love to start using full tinymce in their meta boxes as well inside list items. That would be so awesome.

Here is an example using Visual Composer
Edit Page
http://grab.by/zamy

Modal / Thickbox with TinyMCE
http://grab.by/zamE

Just wondering if any one has done this and if they would be willing to share their code.

Cheers!

**Comment by valendesigns** [comment]
I don't have any immediate plans to make this change and it doesn't seem like anyone has done it yet or is sharing if they have, so I'm closing the issue for now. Sorry.
