### ISSUE TITLE
Upload option removed %20 from external url

### ISSUE THREAD

**Issue by Theme20** [valendesigns/option-tree#386]
Hello,

First Thanks for plugin, When i adding external url to upload input like:

http://mysite.com/this%20is%20title/

after save it changed my url to:

http://mysite.com/thisistitle/

( removed %20 why?! ) So how can i fix this problem Or how can i get this:

http://mysite.com/this is title/

Thanks for your help.

**Comment by valendesigns** [comment]
@Theme20 This is solved in version 2.5.0 coming out Monday.

**Comment by Theme20** [comment]
That's great, Thanks man :+1:
