### ISSUE TITLE
A conflict with another plugin which use media uploader in front-end

### ISSUE THREAD

**Issue by cfuyuki** [valendesigns/option-tree#389]
I just found a small confilict with a plugin that uses media uploader in its front-end.

My current wp theme uses option tree plugin. I recently activated a premium plugin called "Frontend Publishing Pro" (http://codecanyon.net/item/frontend-publishing-pro/8517990) and got an error says
"Fatal error: Call to undefined function ot_get_media_post_ID() in /home2/tuningsy/public_html/blank/wp-content/themes/santino/bw/lib/option-tree/ot-loader.php on line 688". 

This was solved by adding a simple line of code:

if(function_exists('ot_get_media_post_ID'))

directly before the function call:

ot_get_media_post_ID();

in ot-loader.php of option tree plugin.

The author of plugin "Frontend Publishing Pro" suggested this fix and it fixed the problem perfectly but I won't like to change the line every time the theme updates possibly with a new version of option tree.

Do you think it is doable to implement the line of code in the next update? 

Thank you for your time in advance.

**Comment by FL3R** [comment]
Thanks for the solution!
