### ISSUE TITLE
Is there an equivalent of ot_set_option function

### ISSUE THREAD

**Issue by tomperfectspace** [valendesigns/option-tree#393]
I want to update value of a particular option set via option tree from another plugin. Is there a function to do so or I will have to write my own?

Any help would be appreciated.

**Comment by valendesigns** [comment]
This is now in version 2.5.0

**Comment by valendesigns** [comment]
I have to remove this code after considering the backwards compatibility issues and that there is no sanitization before being inserted into the DB. I have plans to revamp how OT sanitizes input values in 2.6.0 and this will make it back in then. For now you can use the following code to do what you need, but expect it will change in the future to include the option type param for sanitizing the values, so rename the function.

```PHP
if ( ! function_exists( 'ot_update_option' ) ) {

  function ot_update_option( $option_id, $option_value ) {

    // Get the option ID.
    $options_id = ot_options_id();

    // Get the options array.
    $options = get_option( $options_id );

    // Update the options array.
    if ( isset( $options[$option_id] ) ) {
      $options[$option_id] = $option_value;
      update_option( $options_id, $options );
    }

  }

}
```
