### ISSUE TITLE
Javascript Option Type

### ISSUE THREAD

**Issue by DannyCooper** [valendesigns/option-tree#416]
Would it be possible to use ace.js to add a javascript option type? Like the CSS option type, many theme developers offer an option for tracking codes/custom js

**Comment by valendesigns** [comment]
It's should be simple enough to create a JS option type using ace.js, though I don't have the time to do it so you'll need to create a pull request with some code to get the ball rolling.

**Comment by valendesigns** [comment]
I'm adding this option type to 2.5.0. However, I'm not adding any dynamic functionality, just the JavaScript option type that use the `ace.js` editor in `javascript` mode for now. Maybe once more work is done on saving dynamic files with `css` we can circle back on adding a dynamic `js` file.
