### ISSUE TITLE
Container option type

### ISSUE THREAD

**Issue by wpwebbouw** [valendesigns/option-tree#420]
When you want to style a container like a div or an input and you want to set background, border color, border style, border width, then you need a lot of different options to accomplish this. It would be nice to combine these in one option type. Perhaps it could also include padding, dimensions (width/height), text-align and the typography options.

I was also looking for a way to add a border-radius option. I could abuse the new spacing option type for that purpose, but then the units select is obsolete and the arrows should point to the corners. Are there diagonal arrows in the option-tree-font?

**Comment by valendesigns** [comment]
There are new option types in the 2.5.0 release, coming hopefully soon, that should solve most if not all of your needs. You can see what those option types are here #411.
