### ISSUE TITLE
Icon font in Section and Tab labels

### ISSUE THREAD

**Issue by shofer4eto** [valendesigns/option-tree#422]
What's the proper way to use the Font Awesome icons integrated in OT within the section/tab titles?
I did this for example, doesn't seem like the fanciest output though:

<pre><code>
&#39;sections&#39;        =&gt; array(
      array(
        &#39;title&#39;       =&gt; &#39;&lt;span class=&quot;ot-icon-desktop&quot;&gt;&lt;/span&gt; Header&#39;,
        &#39;id&#39;          =&gt; &#39;header&#39;,
        ), 
      array(
        &#39;title&#39;       =&gt; &#39;&lt;span class=&quot;ot-icon-font&quot;&gt;&lt;/span&gt;Typography&#39;,
        &#39;id&#39;          =&gt; &#39;typography&#39;
        )
)</code</pre>

Also is there a different, more thorough documentation with examples other than the one that ships with the plugin?

**Comment by valendesigns** [comment]
I've added some minimal styles to fix the placement of the icons when included in section titles to the release-2.5.0 branch. They should appear centered vertically in v2.5.0. As for documentation, there is the included stuff in the plugin and then also the [option-tree-theme](https://github.com/valendesigns/option-tree-theme). Sorry, but I can't really do any more than what is available with the time I have.

**Comment by shofer4eto** [comment]
This is more than enough, Derek, much appreciated!
Official release of 2.5.0?
Cheers!

**Comment by valendesigns** [comment]
Likely next week, but minus the customizer ticket. I just don't have time to do it.
