### ISSUE TITLE
dynamic.less

### ISSUE THREAD

**Issue by CapitalH** [valendesigns/option-tree#423]
Hi

Is it possible to have the dynamic css to write to a less file, like dynamic.less and then have that less file be processed via js or php? I know the processing part of the less file has nothing to do with OptionTree but is it possible to write to a less file using OptionTree at all? and if so how?

**Comment by valendesigns** [comment]
You could hook in and change the file path for each individual option using `css_option_file_path` or globally, as well, by not worrying about the `$field_id` parameter in your filter. The following code is how the filter is created in `ot-functions-admin.php`.

```PHP
/* path to the dynamic.css file */
$filepath = get_stylesheet_directory() . '/dynamic.css';

/* allow filter on path */
$filepath = apply_filters( 'css_option_file_path', $filepath, $field_id );
```

**Comment by CapitalH** [comment]
Thanks for the answer.

I don't which part of your answer I didn't get right but here is what I did:

I created a new css field with the ID of dynamic_less
Then I put this in my functions.php

```php
if ( ! function_exists( 'cfw_ot_less_field' ) ) {
	function cfw_ot_less_field() {
		$filepath = get_stylesheet_directory() . '/dynamic.less';
		return $filepath;
	}
}
add_action('css_option_file_path', 'cfw_ot_less_field', 'dynamic_less');
```

What happens now is that the code inside all of my CSS fields with different IDs are now being written to dynamic.less file and dynamic.css is no longer enqueued.

So I went ahead and added this code after the code above:

```php
if ( ! function_exists( 'cfw_ot_css_fields' ) ) {
	function cfw_ot_css_fields() {
		$filepath = get_stylesheet_directory() . '/dynamic.css';
		return $filepath;
	}
}
add_action('css_option_file_path', 'cfw_ot_css_fields');
```

But this one actually overrides the first code. I also tried adding the field ID to the second code but didn't help. I'm not sure what i'm doing wrong.

**Comment by valendesigns** [comment]
This is not network enabled, you just need to change the file path?

**Comment by CapitalH** [comment]
Yes this issue has nothing to do with the multisite.

The issue with the codes above is that I can not have two different fields writing to two different files. I am not sure which part of my codes above is incorrect.

Basically, I want to have two files and two fields.
Dynamic LESS field to write to my dynamic.less file
Dynamic CSS field to write to my dynamic.css file.

**Comment by valendesigns** [comment]
if ( ! function_exists( 'cfw_ot_css_fields' ) ) {
    function cfw_ot_css_fields( $filepath, $field_id ) {
        if ( $field_id == 'dynamic_less' ) {
          $filepath = get_stylesheet_directory() . '/dynamic.less';
        }
        return $filepath;
    }
}
add_filter( 'css_option_file_path', 'cfw_ot_css_fields', 10, 2 );

**Comment by CapitalH** [comment]
Thank you very much. I know these are busy days for you and I really appreciate the help.

**Comment by valendesigns** [comment]
No worries!
