### ISSUE TITLE
Theme Options not saving in Construct theme by Squidix

### ISSUE THREAD

**Issue by thatcherkirke** [valendesigns/option-tree#429]
Hello,

(I have tried contacting my theme developer, but they have not replied to any of my support tickets, emails, or wall posts on themeforrest)

The theme I purchased was integrated with the Option Tree plugin. As of now, all of the theme options save and can be modified, except for any option controlled by drop down menus that receive a yes/no value. However other drop down menus, font selection for example, work.

I have tried modifying my .htaccess and php.ini files and installing my theme on a fresh wp installation on a different server, but nothing I did had any effect.

Has anyone encountered a bug like this or have a potential solution?

Much appreciated!

**Comment by valendesigns** [comment]
How are your yes/no dropdowns created? Please provide code examples.

**Comment by thatcherkirke** [comment]
Hello,

We have since changed themes. Thank you very much for your reply!
