### ISSUE TITLE
Import demo content

### ISSUE THREAD

**Issue by kekkster** [valendesigns/option-tree#433]
Hi!

I have a question and hope someone here knows how to do it.

I found a forum thread about "1-click demo import" to Wordpress and there is a solution for it. 
Now I would like to implement this into my own theme that uses Option Tree. The problem is that I don´t know how to do this. I have created a tab for the import section but I can´t find a proper solution for triggering the script. 
Maybe there already is an import function in OT?

Here is a link to the thread: http://wordpress.stackexchange.com/questions/158443/one-click-demo-content-installation-feature-in-wordpress-theme-options-panel

ANY advise or help is greatly appreciated. Thanks!

**Comment by valendesigns** [comment]
OptionTree has import/export functionality built in by default, and if you can't see it you've turned it off. You should use that feature and not try and write your own.

**Comment by kekkster** [comment]
I have seen that and I will try it out. Is it possible to move it "inside" the options panel, as its own section tab?

**Comment by valendesigns** [comment]
Don't put it in the theme options. Try creating a new custom page using OT and use the built in options for importing and exporting. Look at how the other settings pages are created and mimic that with your own custom ID. See if that works out of the box first. There may be a tweak needed here and there but it's all doable.=
