### ISSUE TITLE
Sidebar Select — issue with Standard value and "Choose Sidebar"

### ISSUE THREAD

**Issue by vburlak** [valendesigns/option-tree#435]
Hi there.

Found some bug.
I'm using `Sidebar Select` in my theme options with defined Standard value `sidebar-primary`
My code: 

```
array(
	'id'          => 'sidebar_search_widget',
	'label'       => 'Some label',
	'desc'        => 'Some description',
	'std'         => 'sidebar-primary',
	'type'        => 'sidebar-select',
	'section'     => 'sidebar',
	'rows'        => '',
	'post_type'   => '',
	'taxonomy'    => '',
	'min_max_step'=> '',
	'class'       => '',
	'condition'   => 'sidebar_global:is(on),sidebar_search:not(none)',
	'operator'    => 'and'
  )
```

By default — all works great.

If you choose first option from Sidebar Select named `Choose Sidebar` and Save Changes — Sidebar Select will show you, that Standard option (defined as Standard in code above — `sidebar-primary`) is selected.

But `get_option()` function will return nothing from Sidebar Select field up until the options are not saved again with installed value differs from `Choose Sidebar`

Regards

**Comment by valendesigns** [comment]
It's not really a bug as much as a side effect of using a standard value which does not let you have empty values. Unfortunately, the only way to really avoid this issue is to not use a standard value, as the very essence of a standard value means not empty.
