### ISSUE TITLE
OT numerous entries in my wp_posts table

### ISSUE THREAD

**Issue by shofer4eto** [valendesigns/option-tree#436]
Using 2.43 for my new Theme, after some time the WP Admin panel became really slow, after some investigation I found out OT is writing to my wp_posts table upon every Admin reload, a row looks like this:

ID
post_author
post_date
post_date_gmt
post_content
post_title
post_excerpt
post_status
comment_status
ping_status
post_password
post_name
to_ping
pinged
post_modified
post_modified_gmt
post_content_filtered
post_parent
guid
menu_order
post_type

===================================================
20876
1
2015-01-19 11:26:47
2015-01-19 11:26:47
Media
private
closed
closed
media-20499
2015-01-19 11:26:47
2015-01-19 11:26:47
0
http://localhost/freelance/fortuna/wp/?option-tree=media-20499
0
option-tree

I found what is doing it:

add_action( 'admin_init', 'ot_create_media_post', 8 );

in the ot-loader.php

Any idea why I need it would be greatly appreciated?
Thanks in advance!

**Comment by shofer4eto** [comment]
Just realized it was a bug that has been fixed in 2.35, waiting for the cleanup script in 2.5, thanks! :)

**Comment by valendesigns** [comment]
There is already a clean up script in the most recent version.

**Comment by shofer4eto** [comment]
Thank you!
I already downloaded it, about to implement it. 
Quick question, when is 2.5 planned for release? Cheers!
