### ISSUE TITLE
Forbidden message when saving data

### ISSUE THREAD

**Issue by yalamber** [valendesigns/option-tree#438]
I have WordPress install in it's own directory called wordpress, when i save in option tree at http://example.com/wordpress/wp-admin/themes.php?page=ot-theme-options I get redirected to http://example.com/wordpress/wp-admin/options.php with following message displayed 
Forbidden

I updated option tree to latest and also WordPress to latest. I got the same issue.

**Comment by valendesigns** [comment]
Is this a multisite install or is there any other info I should know about other than WP is in a directory?=

**Comment by yalamber** [comment]
It is WordPress 4.1 single install(no multisite). OptionTree is version 2.4.6. 
Other plugins installed  and active are 
-Advanced Custom Fields
-Akismet
-Contact Form 7
-MailChimp for WordPress Lite
-WordPress SEO
All are in latest version.  
Also I guess SuPHP is enabled in hosting env.

**Comment by valendesigns** [comment]
Is the site live? Please put your site in maintenance mode (if live), deactivate all plugins and check for conflicts before we go any further.

**Comment by yalamber** [comment]
I deactivated all plugins and trie. Still got same message. I will try it on a fresh install and see and update you.

**Comment by yalamber** [comment]
So this works ok with subdir install of wordpress. I am not sure what else could cause this problem. Will test

**Comment by valendesigns** [comment]
What is the permission level of the account your trying to save theme options with?

**Comment by valendesigns** [comment]
Unfortunately, I can't go any further with this issue without new information and I have to assume it's a conflict with your themes implementation of OT because it's really an isolated incident. If you haven't solved it reopen the ticket, but supply new info or it will never get addressed.
