### ISSUE TITLE
Generating dynamic.css

### ISSUE THREAD

**Issue by sky4git** [valendesigns/option-tree#439]
Hi,

I am using option-tree in child-theme-mode. I am using some CSS options like colorpicker to set theme color. 

My problem is, I don't know how to use dynamic.css. I created dynamic.css in my root theme folder. I enqueued it in wordpress, and I also added a test CSS class like below.
h1{
	color: {theme_color};
}

Here, theme_color is the colorpicker ID.
 Now I am not sure what I need to do to actually option-tree to popup theme_color in dynamic.css when I save theme options. Currently, option-tree doing nothing and WordPress returned empty css.
It surely not permission problem as I am working on Windows localhost, 

Any clues??
Thanks.

**Comment by valendesigns** [comment]
You have to create a CSS option type. It will save to dynamic.css and be enqueued without you needing to do anything. Put your code in the CSS option type and save. =
