### ISSUE TITLE
option tree option for Google font 

### ISSUE THREAD

**Issue by xpeeder** [valendesigns/option-tree#443]
I saw option tree dont have google font use option and i have found a plugin but its no longer supported :(
https://github.com/doitmax/option-tree-google-fonts

is there any possibility to add google font option in next update ??

Thank you

**Comment by valendesigns** [comment]
This is already being worked on and will be in the next release.

**Comment by xpeeder** [comment]
Hi thank you so much. i like to know when next version will be released :)

**Comment by valendesigns** [comment]
I answered this in #410

**Comment by xpeeder** [comment]
This is really great update coming soon :) i really love this update.
 
one more question is it any possibility to add shortcodes in future ? we have found some others framework include shortcodes and wp cutomiser in his framework like unyson, codestar. 
it will be great if we get all thing thing together :) 

I really love to use option tree for my project.  
Thanks again mate :)
