### ISSUE TITLE
Remove CleanUp Message

### ISSUE THREAD

**Issue by mikakaltoft** [valendesigns/option-tree#446]
I have integrated the Option Tree into my theme. I would like to hear if there is a filter available to remove the CleanUp function?

**Comment by valendesigns** [comment]
No there is not. It would not make sense to filter something off that may very well be needed. I can change the way it works or where it displays but turning it off completely is not an option, at this point.

**Comment by valendesigns** [comment]
I've changed the way this works in 2.5.0. It will not display the menu item anymore, only an admin nag with a link to the clean up page when there's something to actually clean up.

**Comment by mikakaltoft** [comment]
Great, I appreciate. I have added it to my theme and would like to keep the Theme Option framework as anonymous as possible, so your change might work well since it will only display when there actually is an update :-)

**Comment by valendesigns** [comment]
You know you can filter the page & menu title for the clean up page.

**Comment by mikakaltoft** [comment]
I actually did not know that. Where can i find the filter for the page and menu title for the clean up page? :-)

**Comment by valendesigns** [comment]
https://github.com/valendesigns/option-tree/blob/master/includes/ot-cleanup-api.php#L84

**Comment by valendesigns** [comment]
As well, another filter could be added to the nag here https://github.com/valendesigns/option-tree/blob/master/includes/ot-cleanup-api.php#L101

**Comment by mikakaltoft** [comment]
Amazing, thanks a lot!
