### ISSUE TITLE
Upload option type issue with ot-upload-attachment-id in v2.5.0

### ISSUE THREAD

**Issue by mpalaczyk** [valendesigns/option-tree#454]
Hi,

Latest change for upload option type regarding sanitization causes ot-upload-attachment-id class functionality to break, esc_url_raw function automatically adds http:// to the id.

I saw that there is no access to field settings in ot_validate_setting function to check for class, and i guess that it must be fixed on the js side.

**Comment by valendesigns** [comment]
It could possibly be fixed by checking if the value is an integer and then filter with `esc_url_raw` if it's not. I'll likely be putting out a hotfix i.e. v2.5.1 mid week to address any of regressions.
