### ISSUE TITLE
colorpicker-opacity not converting to rgba properly for type css

### ISSUE THREAD

**Issue by johnh10** [valendesigns/option-tree#456]
Great new stuff! But seems to be an issue here:

Create type 'colorpicker-opacity' with id 'post_bg_color' and set the color to #fff and opacity to 1.0 in Theme Options

In my type css I have the rule

.post, .page {
background-color: {{post_bg_color}};
}

which on 'Save Changes', outputs this to dynamic.css:

.post, .page {
background-color: rgba(0, 255, 255, 1);
}

If I set the color to #ffffff it becomes

.post, .page {
background-color: rgba(15, 255, 255, 1);
}

**Comment by valendesigns** [comment]
I'll look into it tomorrow. Thanks for the heads up.

**Comment by johnh10** [comment]
I took a look into this today. In function ot_hex2RGB where $hex is #fff:

The code
else if( strlen( $match[1] ) == 3 ) {
      list($r, $g, $b) = array( $hex[0].$hex[0], $hex[1].$hex[1], $hex[2].$hex[2] );
    }
makes the variable $r contain '##' instead of 'ff'.

For now I added
   $hex = $match[1];
before that if/else nest and that seems to work.

**Comment by valendesigns** [comment]
Please test the hotfix-2.5.1 branch for the updated colorpicker opacity.

**Comment by johnh10** [comment]
Tested! Seems good. :+1:

**Comment by valendesigns** [comment]
The colorpicker opacity does not except an array anymore. It excepts either hexadecimal or rgba values. Please update your standard value. Normally I wouldn't make a change like this after an option type is released but it's only been 4 days in the wild so I think the risk is low and it's better that it gets changed now than later.

**Comment by valendesigns** [comment]
Wait, I take that back you did find a weird bug. I misread your reply.

**Comment by valendesigns** [comment]
Now it's fixed.

**Comment by johnh10** [comment]
2.5.1 tested and seems to work :+1:

**Comment by acastdeveloper** [comment]
Hi. I'm new and I'm using 2.6 version of Option Tree. 

Colorpicker setting doesn't show me field to put manually hexadecimal color. Is that right? In that case how could I add a field to add it manually to have better control of colors? 

Thanks.
