### ISSUE TITLE
error in child theme ot-loader.php on line 661

### ISSUE THREAD

**Issue by xpeeder** [valendesigns/option-tree#458]
Hi 
Today i have setup a child theme in my theme i am getting error in  /ot-loader.php on line 661
. and ot child theme mode also true.
<pre> Warning: include_once(/Applications/MAMP/htdocs/theme/wp-content/themes/theme Child Theme/Applications/MAMP/htdocs/theme/wp-content/themes/theme/framework/option-tree/includes/ot-functions.php): failed to open stream: No such file or directory in /Applications/MAMP/htdocs/onevent3/wp-content/themes/theme/framework/option-tree/ot-loader.php on line 661</pre>

i am confused why this happened

**Comment by valendesigns** [comment]
How is OT installed, as a plugin or in your theme?

**Comment by xpeeder** [comment]
In my Theme

**Comment by valendesigns** [comment]
The parent theme or child theme?

**Comment by xpeeder** [comment]
i have installed in parent theme. and create a child theme for my theme

**Comment by valendesigns** [comment]
What OT filters have you added to `functions.php` to activate theme mode?

**Comment by xpeeder** [comment]
i have just connect ot-loader.php in functions.php

and here is the theme mode  filter from ot-loader.php

add_filter('ot_theme_mode', '__return_true');
add_filter('ot_child_theme_mode', '__return_true');

**Comment by valendesigns** [comment]
Remove this filter `add_filter('ot_child_theme_mode', '__return_true')`.

**Comment by valendesigns** [comment]
You should be connecting to OT in your parent them. Your child theme is unaware of OT and none of those filters or inclusions should be in the child theme.

**Comment by xpeeder** [comment]
Hi
it will be true or false in ot-loader.php ? 
if i set true its getting same error message

**Comment by valendesigns** [comment]
You do not set child theme mode anywhere.

**Comment by valendesigns** [comment]
You have it installed in the parent theme. Child theme mode means OT is installed in the child theme.

**Comment by xpeeder** [comment]
oh ok thanks
