### ISSUE TITLE
Child themes unable to load Google Fonts

### ISSUE THREAD

**Issue by johnh10** [valendesigns/option-tree#464]
Using Option Tree Theme Mode for a parent theme.
Created a child theme off of the parent theme.
When I switch to the child-theme the 'google-fonts' type is an empty select box. All other types load fine. Have tried several child themes with same results.

**Comment by valendesigns** [comment]
I'm headed down to my office in a minute, I'll get this patched for 2.5.1 today.

**Comment by valendesigns** [comment]
I figure out what the issue was. I'll have it ready to test in 10-20 minutes.

**Comment by valendesigns** [comment]
This should now be fixed. Please checkout hotfix-2.5.1 and test it ASAP. I'd like to release it in the next hour or two. Cheers!

**Comment by johnh10** [comment]
2.5.1 tested and seems to work. :+1:
