### ISSUE TITLE
Issue: Child theme loads dynamic.css from child AND parent.

### ISSUE THREAD

**Issue by johnh10** [valendesigns/option-tree#465]
Child theme loads dynamic.css from child AND parent.
Is this supposed to happen or is it more of a 'user-beware' type of issue?

**Comment by valendesigns** [comment]
Probably always done that. Nothing changed in that regards. Shouldn't do that though in all reality. Thanks for the heads up. Something for 2.5.2 I suppose.

**Comment by valendesigns** [comment]
Are you saying it loads two different files or both sets of CSS to the same file?

**Comment by johnh10** [comment]
Here's what I see when I view source on the child theme:

<link rel='stylesheet' id='ot-dynamic-site_css-css'  href='http://www.mysite.com/wp-content/themes/superflex/dynamic.css?ver=2.5.1' type='text/css' media='all' />
<link rel='stylesheet' id='ot-dynamic-superflex_css-css'  href='http://www.mysite.com/wp-content/themes/superflex-child/dynamic.css?ver=2.5.1' type='text/css' media='all' />
<link rel='stylesheet' id='ot-dynamic-superflex_css2-css'  href='http://www.mysite.com/wp-content/themes/superflex/dynamic.css?ver=2.5.1' type='text/css' media='all' />

The child theme didn't make any changes, besides saving a new dynamic.css
However I have only seen it on my development test site, and when installing it on other sites it seems to work fine. Really, I have no idea why. :(

**Comment by valendesigns** [comment]
I can't reproduce this issue. The only thing I noticed is that until the theme options are saved the theme loads the parent themes dynamic styles, but as soon as you save that stops happening. If you experience this on a live site reopen the issue, or if you can tell me how to reproduce this consistently.

Cheers!
