### ISSUE TITLE
Upgrading from 2.4.6 to 2.5.1 gave me the 'White screen' of death?

### ISSUE THREAD

**Issue by Chrisedmo** [valendesigns/option-tree#466]
I am not using it in my theme directly - I am using it as plug in. 

When i comment out my ot_register_meta_box… i can safely log back in to my admin again - PHEW!

Any ideas why this would be?

This is my code for ref:

    add_action( 'admin_init', 'custom_meta_boxes' );

    function custom_meta_boxes() {

      $page_intro = array(
        'id'        => 'page_intro',
        'title'     => 'Page Intro',
        'desc'      => 'Enter the description that will appear under the page header',
        'pages'     => array( 'page'),
        'context'   => 'normal',
        'priority'  => 'high',
        'fields'    => array(
          array(
            'id'          => 'page_intro_text',
            'label'       => '',
            'desc'        => '',
            'std'         => '',
            'type'        => 'textarea',
            'class'       => '',
            'choices'     => array()
          )
        )
      );

      // Person Options
      $person_details_meta = array(
          'id' => 'person-details',
          'title' => 'Details',
          'pages' => array('person'),
          'context' => 'normal',
          'priority' => 'low',
          'fields' => array(
              array(
                  'id' => 'person_thumbnail',
                  'label' => 'Thumbnail',
                  'desc' => 'This image must be 400 x 400.',
                  'type' => 'upload',
              ),
              array(
                  'label' => 'Job Title',
                  'desc' => 'Enter this person\'s job title',
                  'id' => 'person_jobtitle',
                  'type' => 'text'
              ),
              array(
                  'label' => 'Email',
                  'desc' => 'Enter an email address for this person',
                  'id' => 'person_email',
                  'type' => 'text'
              ),
              array(
                  'label' => 'Telephone Number',
                  'desc' => 'Enter a telephone number for this person in the following format, 01534 629623',
                  'id' => 'person_tel',
                  'type' => 'text'
              ),
              array(
                  'label' => 'Twitter',
                  'desc' => 'Copy and paste the URL to this person\'s Twitter feed',
                  'id' => 'person_twitter',
                  'type' => 'text'
              ),
              array(
                  'label' => 'LinkedIn',
                  'desc' => 'Copy and paste the URL to this person\'s LinkedIn profile',
                  'id' => 'person_linkedin',
                  'type' => 'text'
              ),
              array(
                  'label' => 'Instagram',
                  'desc' => 'Copy and paste the URL to this person\'s Instagram',
                  'id' => 'person_instagram',
                  'type' => 'text'
              ),
          )
      );
      
      //ot_register_meta_box( $page_intro );
      // ot_register_meta_box( $person_details_meta );

    }

**Comment by valendesigns** [comment]
My first guess is you don't have a check for function exist in your metabox code so when the plugin deactivates your theme throws an error causing a white screen.

**Comment by BassemN** [comment]
Try to set ```define('WP_DEBUG', true);``` on your wp-config.php to display the error messages.

**Comment by valendesigns** [comment]
I updated from 2.4.6 to 2.5.1 on three different websites I use OT for and none of them had a single issue. This is more than likely a theme compatibility problem, and even more likely the one I mentioned above. You need to always do function checks because the plugin gets deactivated when it's upgraded and if your theme doesn't have the checks in place it will error out and fail. Which means the plugin gets downloaded but not reactivated which leaves the error persistent and you are unable to access your admin. Closing for now, but reopen if you add the function checks and it still happens.

**Comment by Chrisedmo** [comment]
I know this is closed now, but I fixed this by adding in the following around my above code:
    if (function_exists( 'get_option_tree') ) {
      …
    }
