### ISSUE TITLE
Upgrading plugin leaves only menu and blank wp-admin

### ISSUE THREAD

**Issue by jbhully** [valendesigns/option-tree#467]
Have just updated to latest version and - as per the title - and nothing appears on the site apart from the main menu with no content. Can login to the site, but wp-admin is totally blank page. Assume we need to get in via FTP and rollback the plugin ? If so, where do we get previous version, and how would we restore any settings? 

Or is there an alternative workaround or fix to at least let us access wp-admin and resolve the problem?

**Comment by jbhully** [comment]
Update: by browsing source  on wp-admin page it is possible to see that wp-admin has been disabled.

**Comment by BassemN** [comment]
Try to set the define('WP_DEBUG', true); on your wp-config.php to display the error messages.
also you can download old releases from here https://github.com/valendesigns/option-tree/releases

**Comment by jbhully** [comment]
Thanks, BassemN

**Comment by valendesigns** [comment]
What version of OT are you upgrading from and do you have `function_exists` checks in your metabox and theme options files?

**Comment by jbhully** [comment]
Problem resolved. Programmer had not read your warnings and had tried to upgrade an OT in themes from .4.6 to .5.x using the plugins menu. Deleted the resultant OT folder from plugins, put 4.6 back into themes and amended config to point to OT in themes. Site restored. Lessons learnt.
