### ISSUE TITLE
Notice: Undefined index: label in option-tree/includes/ot-settings-api.php on line 460

### ISSUE THREAD

**Issue by xpeeder** [valendesigns/option-tree#468]
I am getting a notice after update my option tree old version to 2.5
460 line have this code have 
<pre>$setting['label'], </pre>

here settings field 
<pre>/* add each setting */
            add_settings_field( 
              $setting['id'], 
              $setting['label'], 
              array( $this, 'display_setting' ), 
              $page['menu_slug'],
              $setting['section'],
              $setting
            );</pre>

is there i have doing any wrong ? 

Thank you

**Comment by xpeeder** [comment]
when i update post or something we are getting warning message to 
http://prntscr.com/66kmkk

i am really confused why this happened to me. 
Is this option tree issue ?? or from my theme ? 

Thank you

**Comment by valendesigns** [comment]
Do your theme options have missing label fields?

**Comment by xpeeder** [comment]
label displayed without any issue
http://prntscr.com/66kr01

**Comment by valendesigns** [comment]
There are five other tabs. And possibly list items that could be missing the label. Also, upgrade to 2.5.1 please. I like troubleshooting with the most recent version.

**Comment by xpeeder** [comment]
all label work here. also i have update  latest version just connect with theme. still notice display on top.
http://prntscr.com/66kt29

Thank you

**Comment by valendesigns** [comment]
If all the labels were working it wouldn't be showing that error. Please send a copy of your settings array to derek at valendesigns dot com.

**Comment by valendesigns** [comment]
All of these options are missing labels...
```PHP
xs_second_welcome_message
xs_learn_more_btn_url
xs_download_btn_url
```
Which is why you have 3 notices.

**Comment by xpeeder** [comment]
i was thinking it will not affect. thats why i just removed to looks good.

Thanks brother for this help :)

i have sent a small donation for you for this awesome and easy option panel (Y)

**Comment by valendesigns** [comment]
Thank you, glad to help!
