### ISSUE TITLE
Disable drag & drop for list-item option type for some options

### ISSUE THREAD

**Issue by BassemN** [valendesigns/option-tree#472]
Hi,

Is there any way to disable drag & drop feature for list-item option type for some options?

Thanks,

**Comment by valendesigns** [comment]
No there is not.

**Comment by valendesigns** [comment]
Why do you want to do that, out of curiosity?

**Comment by BassemN** [comment]
I'm using list-item to create unlimited sidebars feature so drag & drop feature doesn't make sense on this case.

**Comment by valendesigns** [comment]
We could create a CSS class that when added to the `list-item` option type will stop the drag & drop feature.

**Comment by BassemN** [comment]
Thank you @valendesigns . Can you please add this to 2.5.2 millstone?

**Comment by valendesigns** [comment]
This is added to 2.5.2, but typically I do not add new features to a hotfix branch. In the future these kind of requests will not make it into a hotfix. But I'll give you this one. Just add `not-sortable` to the `class` option for your list item.

**Comment by BassemN** [comment]
Thank you very much
