### ISSUE TITLE
Google Fonts Font Family CSS equivalent value

### ISSUE THREAD

**Issue by shofer4eto** [valendesigns/option-tree#473]
I have successfully set a Google Font for a field, then retrieved it in the front end.
The font-family field is for example "droidserif".
How do I get the font family's equivalent to set for a field with CSS in the front End? 
I basically need the "Droid Serif" value dynamically converted from the font family array.
Thanks in advance!

**Comment by gerardbm** [comment]
You need this: https://github.com/valendesigns/option-tree/pull/444#issuecomment-72634452

It helped me!

**Comment by valendesigns** [comment]
The `ot_google_fonts` theme mod holds the array of font families that you can then grab the string from:
`$ot_google_fonts = get_theme_mod( 'ot_google_fonts', array() );`

The following would return the value you want.
`$ot_google_fonts['droidserif']['family']`

The comment @gerardbm linked to above has a more encompassing example with `isset` checks and is dynamic. It should be pretty easy to modify into what you need.
