### ISSUE TITLE
Fatal Error: call to undefined function ot_get_option()

### ISSUE THREAD

**Issue by faham29** [valendesigns/option-tree#474]
Hello, 

First of all many thanks for this beautiful plugin.

I am using version 2.5.1 of the plugin in theme mode and I am trying a different approach with it. My intention is to create a dynamic style.php that fetches value from theme options however I am unable to get this to work as in the style.php I can't seem to be able to access the ot_get_option() function.

I have tried using add_action with the following code:

function include_template() {
		wp_enqueue_style( 'theme-option', get_template_directory_uri() . '/css/style.php',array() , '1.0', all);
	}
	add_action('after_setup_theme', 'include_template', 2);

Along with that I tried copying the ot_get_option() and ot_wpml_filter() function to functions.php but to no avail.

Is there anyway that this can be done or do I have to use a workaround which I feel is quite shabby and incorrect way of coding.

Thank you

**Comment by tjuris** [comment]
when ( which wp hook ) do you include your style.php in? Make sure its after optiontree is loaded.

**Comment by valendesigns** [comment]
Try something like this.

Add to `functions.php`
```PHP
function custom_enqueue_scripts() {
  wp_enqueue_style( 'theme-option', get_template_directory_uri() . '/css/style.php',array() , '1.0', all);
}
add_action( 'wp_enqueue_scripts', 'custom_enqueue_scripts' );
```

Inside `styles.php`
```PHP
function custom_theme_styles() {
  // process and echo the CSS here.
}
add_action( 'after_setup_theme', 'custom_theme_styles' );
```

**Comment by faham29** [comment]
The solution to my issue was to call for cache-control header like the below code:
style.php
	$absolute_path = explode('wp-content', $_SERVER['SCRIPT_FILENAME']);
	$wp_load = $absolute_path[0] . 'wp-load.php';
	require_once($wp_load);
	header('Content-type: text/css');
	header('Cache-control: must-revalidate');
	if ( function_exists( 'ot_get_option' ) ) {
              #some function to manipulate css variables
        }
functions.php
function include_template() {
   wp_enqueue_style( 'theme-option', get_template_directory_uri() . '/css/style.php',array() , '1.0', all);
}
add_action('after_setup_theme', 'include_template', 2);

This seems to have worked for me so I am writing this here in case it helps anyone out.
