### ISSUE TITLE
Feature request: ot-admin.css version in sass/scss or less

### ISSUE THREAD

**Issue by vburlak** [valendesigns/option-tree#477]
Hi @valendesigns !
I'm interested in deep customization of `ot-admin.css`

At first I thought I just do overwrite styles in my separate .css file.
But after I looked in deatails of `ot-admin.css` — I want to ask, is it possible to publish scss/sass or less source version of ot-admin.css? (of course, if such version exists now).

Before post that issue, i'm tried to use [some](http://sebastianpontow.de/css2compass/) online converters (css to scss in my opinion). But all of them - do terrible(unusable) things with so much css.

Regards!

**Comment by vburlak** [comment]
Still, if you generating ot-admin.css from sass/scss/less, and you can provide that sources in any form. Please tell me what the best practice to filter `wp_enqueue_style( 'ot-admin-css');`.

I'm tryed `wp_dequeue_style( 'ot-admin-css')` and `wp_deregister_style('ot-admin-css')` after ot-loader.php require, but unsuccessfully..

**Comment by valendesigns** [comment]
I plan on adding build tools and sassifying the admin CSS in 2.6

**Comment by vburlak** [comment]
Oh, very cool!

Îòïðàâëåíî ñ iPhone

18.03.2015, â 1:53, Derek Herman <notifications@github.com> íàïèñàë(à):

**Comment by danimalweb** [comment]
Looking forward to this.
