### ISSUE TITLE
how to get list item meta-box value in shortcode?

### ISSUE THREAD

**Issue by rasel2339** [valendesigns/option-tree#479]
i am trying get list item value in shortcode, but this code not working, thanks.

$variable = get_post_meta ($post->ID, 'your_id', true);

	if ( !empty( $variable ) ) {
		echo '<ul>';
	foreach( $variable as $any_name ) {
		echo '<li>'.$any_name['title'].'</li>';
		}
		echo '</ul>';
	}

**Comment by valendesigns** [comment]
You keep changing the title but it's not all that clear as to what you want help with here. All I can do is show you how to write a shortcode.
```PHP
function foobar_func(){
  global $post;
  $variable = get_post_meta( $post->ID, 'your_id', true );
  $output = '';
  if ( ! empty( $variable ) && is_array( $variable ) ) {
    foreach( $variable as $any_name ) {
      $output.= $any_name['title'];
    }
  }
  return $output;
}
add_shortcode( 'foobar', 'foobar_func' );
```

**Comment by rasel2339** [comment]
sorry. and thank you for first reply. actually i am new here, so make mistake when i post. 
i just add  " global $post; " on my code, now its working!!. thanks. thanks again for your help.

**Comment by valendesigns** [comment]
No worries. Glad to help.
