### ISSUE TITLE
CSS and JS option type not working under tab

### ISSUE THREAD

**Issue by Theme20** [valendesigns/option-tree#481]
Hello, 

Custom CSS and Javascript option type under second tab not working.

**Comment by valendesigns** [comment]
Not working how?

**Comment by Theme20** [comment]
In default section its working: http://awesomescreenshot.com/0244p9je8f

But inside tab not working: http://awesomescreenshot.com/0c14p9jw92

Ofcourse not sure i'm using true, tab code, here is my code:

array(
	'id'		=> 'favicon-tab',
	'label'	=> __('Favicon', 'T20'),
	'type'	=> 'tab',
	'section'	=> 'general'
),
array(
	'id'		=> 'favicon',
	'label'	=> __('Favicon', 'T20'),
	'type'	=> 'upload',
	'section'	=> 'general'
),

array(
	'id'		=> 'css-js-tab',
	'label'	=> __('Custom CSS, JS', 'T20'),
	'type'	=> 'tab',
	'section'	=> 'general'
),
array(
	'id'		=> 'custom-css-head',
	'label'	=> __('Custom CSS', 'T20'),
	'type'	=> 'css',
	'section'	=> 'general'
),
array(
	'id'		=> 'custom-js-head',
	'label'	=> __('Custom JS', 'T20'),
	'type'	=> 'javascript',
	'section'	=> 'general'
),


Note: in second screenshot when i've opened inspect element of my browser it woks again.

Thanks.

**Comment by gerardbm** [comment]
@Theme20, are you enqueuing Javascript in the admin of your theme? This can cause conflicts affecting directly to OptionTree.

**Comment by Theme20** [comment]
@gerardbm no, also i've checked it with deactivate all plugins.

**Comment by valendesigns** [comment]
This is a legit bug. I'll look into tomorrow.

**Comment by Theme20** [comment]
Thanks :+1:

**Comment by valendesigns** [comment]
This is fixed in the hotfix-2.5.2 branch.
