### ISSUE TITLE
ot_post_formats doesn't working correctly

### ISSUE THREAD

**Issue by wahid55** [valendesigns/option-tree#484]
Hello,
I am using add_filter( 'ot_post_formats', '__return_true' ); filter for my website.
When It's return_true, everything work fine. But when __return_false, everything work fine without post format image. 
When I select Post Format Image, the metabox still display.
http://i.imgur.com/fXdUnFb.png
But I don't want to see that when return_false.
How can I hide it when return_false.

**Comment by valendesigns** [comment]
Do you have the OT post formats option activated in your theme?

**Comment by valendesigns** [comment]
This is sorted in 2.5.2 coming out tomorrow. Thanks for brining it to my attention.

**Comment by wahid55** [comment]
If I active OT post format in my them, then everything working well.
But The problem is happening, after install the option tree plugin. When I install it, the problem occur.
Thanks for your attention :+1:
