### ISSUE TITLE
option tree styling missing and new meta boxes not appearing

### ISSUE THREAD

**Issue by Chrisedmo** [valendesigns/option-tree#485]
Hi guys, I'm having a bit of a hard time trying to get this to work. I am using OT 2.5.2 in theme mode, but my meta boxes seem to have the default wordpress meta box styling applied and they do not look like the option tree meta boxes. 

I am registering my meta boxes like so:

    if (function_exists( 'get_option_tree') ) {
    function custom_meta_boxes() {
      $page_intro = array(
        'id'        => 'page_intro',
        'title'     => 'Page Intro',
        'pages'     => array('page'),
        'context'   => 'normal',
        'priority'  => 'high',
        'fields'    => array(
        	array(
            'id'          => 'page_intro_text',
            'label'       => 'Page Intro',
            'desc'        => 'This will appear at the top of the page',
            'type'        => 'textarea'
    		),
        	array(
    	        'label' => 'Insert Slider',
    	        'desc' => 'Select images to display in the header. Images must be 1200px wide by 410px deep.',
    	        'id' => 'banner_slider',
    	        'type' => 'gallery'
    	    ),
    	)
      );
      // Person Options
      $person_details_meta = array(
          'id' => 'person-details',
          'title' => 'Details',
          'pages' => array('person'),
          'context' => 'normal',
          'priority' => 'low',
          'fields' => array(
              array(
                  'id' => 'person_thumbnail',
                  'label' => 'Thumbnail',
                  'desc' => 'This image must be 400 x 400.',
                  'type' => 'upload',
              ),
              array(
                  'label' => 'Job Title',
                  'desc' => 'Enter this person\'s job title',
                  'id' => 'person_jobtitle',
                  'type' => 'text'
              ),
              array(
                  'label' => 'Email',
                  'desc' => 'Enter an email address for this person',
                  'id' => 'person_email',
                  'type' => 'text'
              ),
              array(
                  'label' => 'Telephone Number',
                  'desc' => 'Enter a telephone number for this person in the following format, 01534 629623',
                  'id' => 'person_tel',
                  'type' => 'text'
              ),
              array(
                  'label' => 'Twitter',
                  'desc' => 'Copy and paste the URL to this person\'s Twitter feed',
                  'id' => 'person_twitter',
                  'type' => 'text'
              ),
              array(
                  'label' => 'LinkedIn',
                  'desc' => 'Copy and paste the URL to this person\'s LinkedIn profile',
                  'id' => 'person_linkedin',
                  'type' => 'text'
              ),
              array(
                  'label' => 'Instagram',
                  'desc' => 'Copy and paste the URL to this person\'s Instagram',
                  'id' => 'person_instagram',
                  'type' => 'text'
              ),
          )
      );
      
      ot_register_meta_box( $page_intro );
      ot_register_meta_box( $person_details_meta );
    }
    add_action( 'admin_init', 'custom_meta_boxes' );
    }

And the meta boxes look like this (taken from a single 'person'): 

![screen shot 2015-03-31 at 09 44 16](https://cloud.githubusercontent.com/assets/255639/6915282/a937a3ba-d78a-11e4-80ad-a2fcace68ece.png)

And last night I added in another option to the $page_intro = the 'banner_slider' and it is not appearing at all.

Aside form this the information is appearing when I am calling it in my theme files?

Any ideas?

**Comment by valendesigns** [comment]
Those are not the OT meta boxes, they are the built in custom fields. You need to click the "Screen Options" tab at the top of the page and unhide the meta boxes.

**Comment by Chrisedmo** [comment]
Hi @valendesigns but if I do that, there are custom meta boxes at all? any ideas why they would not be registering via option tree?

**Comment by valendesigns** [comment]
You need to likely map meta capabilities for your custom post type. What is the code that you use to register the post type?

**Comment by Chrisedmo** [comment]
Many thanks for the feedback. I also have some meta boxes I would like to appear under a regular page too (in the above code), and only the old one ( 'page_intro_text) seems to be appearing as a custom field. It's odd, this is the first problem I've encountered with this plug in.

But here is that particular custom post type for reference:

    function register_people() {

        $labels = array(
            'name'                => __( 'People', 'text-domain' ),
            'singular_name'       => __( 'Person', 'text-domain' ),
            'add_new'             => _x( 'Add New Person', 'text-domain', 'text-domain' ),
            'add_new_item'        => __( 'Add New Person', 'text-domain' ),
            'edit_item'           => __( 'Edit Person', 'text-domain' ),
            'new_item'            => __( 'New Person', 'text-domain' ),
            'view_item'           => __( 'View Person', 'text-domain' ),
            'search_items'        => __( 'Search People', 'text-domain' ),
            'not_found'           => __( 'No People found', 'text-domain' ),
            'not_found_in_trash'  => __( 'No People found in Trash', 'text-domain' ),
            'parent_item_colon'   => __( 'Parent Person:', 'text-domain' ),
            'menu_name'           => __( 'People', 'text-domain' ),
        );

        $args = array(
            'labels'              => $labels,
            'hierarchical'        => true,
            'description'         => 'description',
            'taxonomies'          => array(),
            'public'              => true,
            'show_ui'             => true,
            'show_in_menu'        => true,
            'show_in_admin_bar'   => true,
            'menu_position'       => null,
            'menu_icon'           => null,
            'show_in_nav_menus'   => true,
            'publicly_queryable'  => true,
            'exclude_from_search' => false,
            'has_archive'         => true,
            'query_var'           => true,
            'can_export'          => true,
            'rewrite'             => true,
            'capability_type'     => 'post',
            'supports'            => array(
                'title', 'editor', 'author', 'thumbnail',
                'excerpt','custom-fields', 'trackbacks', 'comments',
                'revisions', 'page-attributes', 'post-formats'
                )
        );

        register_post_type( 'person', $args );
    }

    add_action( 'init', 'register_people' );

**Comment by Chrisedmo** [comment]
I've solved this, so I'll add the fix for any future users… 

I had my code that registered the meta boxes in the following code:

    if (function_exists( 'get_option_tree') ) {
        …
    }

I had this in my functions.php from when I was using it as a plug-in. Removing that code solved my issues and restored my meta boxes.

**Comment by gerardbm** [comment]
@Chrisedmo, maybe that is because the function 'get_option_tree' is deprecated.

Quoted from OT documentation: *«This function has been deprecated. That means it has been replaced by a new function or is no longer supported, and may be removed from future versions. All code that uses this function should be converted to use its replacement.»*

**Comment by valendesigns** [comment]
There are two things wrong with wrapping the meta box code like that. First, is what @gerardbm has already mentioned, which is that the `get_option_tree` function is deprecated and you should be using `ot_get_option` instead. Second, that function will never be available in time for that check to work. OptionTree is loaded from a filter and calling functions directly when they are not available will cause the code to never run. A better way to check that you can register meta boxes is inside your `custom_meta_boxes` function you can do this:
```PHP
if ( function_exists( 'ot_register_meta_box' ) ) {
  ot_register_meta_box( $page_intro );
  ot_register_meta_box( $person_details_meta );
}
```
Then you are making sure that Option Tree is available, but at the right time and for the right function.
