### ISSUE TITLE
Request: Add inherit fallback to other option types in dynamic.css

### ISSUE THREAD

**Issue by johnh10** [valendesigns/option-tree#486]
Inherit works great as the fallback for link-color types (https://github.com/valendesigns/option-tree/issues/469)

I'd like to see the same functionality on other types that require a css prefix, such as *colorpicker-opacity* and *border*, and probably others.

For instance defining
content_bg_color as type *colorpicker-opacity* and content_border as type *border* with the following css rule:

    .content { 
    background-color: {{content_bg_color}};
    border: {{content_border}};
    }

writes the following to dynamic.css if the end user doesn't set them:

    .content { 
    background-color: ;
    border: ;
    }

Instead, I would like to see the fallback as

    .content { 
    background-color: inherit ;
    border: inherit;
    }

**Comment by valendesigns** [comment]
We need to decide on which option types need this treatment and solve it once and for all. Please feel free to add to this list in the comments and I'll update the list below as needed. 

- [ ] border
- [ ] colorpicker-opacity

**Comment by johnh10** [comment]
Hello, I tested this with hotfix 2.5.3 and I'm not getting the 'inherit' for border and colorpicker-opacity types when there is no default defined and user does not set a value.

    .content { 
    background-color: ;
    border: ;
    }

**Comment by valendesigns** [comment]
Not sure what made you think it was, but it's not been added yet.

**Comment by johnh10** [comment]
Sorry my eyes tricked me when I got the hotfix notification.

**Comment by valendesigns** [comment]
No worries. I'll get to it soon.

**Comment by valendesigns** [comment]
I think some of these option should just fallback to `none` instead of `inherit`. Thoughts?

**Comment by johnh10** [comment]
Some types do not support <code>none</code> so perhaps <code>transparent</code> instead.

**Comment by valendesigns** [comment]
Look at the [readme.txt](https://github.com/valendesigns/option-tree/blob/hotfix-2.5.3/readme.txt#L130-L133) for hotfix-2.5.3
