### ISSUE TITLE
Remove Title on List Items

### ISSUE THREAD

**Issue by florianflock** [valendesigns/option-tree#487]
Hey,
is it possible to remove Title element in Lists?
Many Thanks,
Florian

**Comment by BassemN** [comment]
+1 for this

**Comment by florianflock** [comment]
@valendesigns is on easter holiday maybe :)

**Comment by valendesigns** [comment]
You cannot remove the title, but you can filter the label & description with `ot_list_item_title_label` & `ot_list_item_title_desc`.
