### ISSUE TITLE
Add spaces or divider between words in Google font opt. values e.g value=roboto+slab

### ISSUE THREAD

**Issue by mnkystudio** [valendesigns/option-tree#491]
Hi,

Google font option values using Typography option $body_font['font-family'] outputs font name without spaces or some kind of divider. For example, robotoslab instead of roboto slab, so it doesn't work. Can you please add spaces or divider ("+" for examle so it is possible to use str_replace). 

Thank you!

**Comment by valendesigns** [comment]
It is that way by design and is not a bug. If you want the label value and not the key read this https://github.com/valendesigns/option-tree/issues/473#issuecomment-76312173

**Comment by valendesigns** [comment]
Also this https://github.com/valendesigns/option-tree/pull/444#issuecomment-72634452
