### ISSUE TITLE
Add radio label as a CSS class

### ISSUE THREAD

**Issue by Codevz** [valendesigns/option-tree#492]
Hi, 

Hope you're doing well, Could you please in the next update remove "esc_attr" just from radio and checkbox label title output. I want add font-icon for radio label.

Thanks.

**Comment by valendesigns** [comment]
Sorry, but no. That's there for security purposes and is this way to adhere to the WordPress validation guidelines. You should add the font icon using CSS `:before` and not directly in the content anyhow. Just rethink your approach slightly and you can overcome this with CSS.

**Comment by Theme20** [comment]
Please add class for radio label in next update:

class="' . esc_attr( $choice['label'] ) . '"

In this case we can easily add font icon for radio then with a little css it will woks fine :+1: 

Thanks
