### ISSUE TITLE
Google Fonts no longer displaying in Typography option

### ISSUE THREAD

**Issue by cocolero** [valendesigns/option-tree#495]
I upgraded to the latest Optiontree and noticed that my Cambria font had disappeared from my H1 and other font classes. When I went to see what the Typography options settings were in Optiontree, I seem to remember that there were some Google API options in there or was it my imagination?

http://cl.ly/image/2A2h2i3y1z2b

**Comment by valendesigns** [comment]
I don't know what custom settings your theme use to have. However, I cannot reproduce this issue in any case. So I'll need more information. Also, where is the Google font option type in your theme panel? If it's doesn't have one then it's not possible to have Google fonts in your typography option without some other custom functionality.
