### ISSUE TITLE
The typography option in the plugin is not working

### ISSUE THREAD

**Issue by faham29** [valendesigns/option-tree#497]
I am trying to simply embed the plugin in a WordPress theme that I am creating but it appears that the typography options are not functional.

I tried adding font selector for menu but the css is not enqueued. Another issue that I observed was that the plugin gives out font family is lower case and replaces the whitespace with hyphen. This is rendering the font family unusable even if I enqueue the google font stylesheet manually.

Please let me know if there is some modifications that I need to do to make this work. I did tried a var_dump and noticed that the get_theme_mod for google fonts is not rendering any output and the function calling the wp_enqueue_style for google fonts is not getting triggered.

I have not made any special modifications to the code apart from a single var_dump which has also been removed now.

Kindly suggest a work around.

Regards
Faham

**Comment by valendesigns** [comment]
First, I would **highly** recommend you stop using theme mode. It's pointless and should be deprecated, though it's likely not your issue here. You only need 1 Google Font option type to add multiple fonts and it will automatically enqueue the stylesheet from Google. As well, it will automatically insert the google font into the typography option type after it has been saved to the database. If you are not using `dynamic.css` to add CSS to your theme and need to get the label value and not array key of the Google font you will need to read this https://github.com/valendesigns/option-tree/pull/444#issuecomment-72634452.

**Comment by faham29** [comment]
@valendesigns Thank you for your quick response. I am sorry, I did read the comment but unfortunately I am still getting the array key and not the label.

Can you please point me to something more specific.

Also I am unable to get any value in the array for this particular code 

 $ot_google_fonts = get_theme_mod( 'ot_google_fonts', array() );
I believe there is something not right in get_theme_mod as I am not getting anything even on a var_dump

**Comment by valendesigns** [comment]
Is this a Multisite install?

**Comment by faham29** [comment]
No, it is a single pager. I am using style.php and have added a few fonts, russo one and others for my requirement.

But even without adding these fonts the stylesheet is not enqueued indicating that the get_theme_mod is returning a blank array and hence the functions are not executing.

**Comment by valendesigns** [comment]
Is it live somewhere I can see it?

**Comment by faham29** [comment]
http://projects.code-eon.com/cet/

**Comment by valendesigns** [comment]
Send login info for WP and FTP if you can to derek@valendesigns.com and I'll take a peek.

**Comment by valendesigns** [comment]
You don't have a Google Font option type added to your theme options. Add one and your problem will go away.

**Comment by faham29** [comment]
@valendesigns Google font option type are added under Menu font and couple of other sections but it is still the same.

**Comment by valendesigns** [comment]
Remove the old OptionTree you have in your themes core.

**Comment by valendesigns** [comment]
I added your fonts in the footer section and they are now linked to Google in your document head.

**Comment by valendesigns** [comment]
Why did you delete them?

**Comment by faham29** [comment]
I have not deleted any fonts yet but I was going ahead to delete the old option tree from theme

**Comment by valendesigns** [comment]
Weird. Tell me when you have deleted the old OT.

**Comment by faham29** [comment]
I have renamed it and have removed require_once from theme

**Comment by faham29** [comment]
Still the same, you can notice that get_theme_mods is not giving any output either.

**Comment by valendesigns** [comment]
Because you have not added your google fonts yet. Go to your "Footer" tab in your theme options and add the fonts.

**Comment by faham29** [comment]
It surely works Thanks.... I did not knew that to add typography I had to add Google fonts from theme options.

**Comment by valendesigns** [comment]
The fonts will not show unless you add them. It doesn't automatically insert all the fonts into the dropdown. It would be overwhelming and slow things down even more.
