### ISSUE TITLE
WP Database Issue - wp_option_tree

### ISSUE THREAD

**Issue by maarcin** [valendesigns/option-tree#500]
Hi,

Since couple days I have this issue in the admin dashboard:

<pre>WordPress database error: [Table 'test.wp_option_tree' doesn't exist]
SHOW FULL COLUMNS FROM `wp_option_tree`</pre>

Not sure why. I use latest version from WP.org and it's included as a plugin. I use WP 4.1.2-RC1. This didn't show up when I used OT v2.4.6. Any ideas?

Cheers

**Comment by valendesigns** [comment]
It's already been fixed in the Core. This is not an OT issue.

**Comment by maarcin** [comment]
Just updated WP to 4.2-RC2-32233 and issue is gone. Thanks.

**Comment by valendesigns** [comment]
You're welcome. Glad to help.
