### ISSUE TITLE
using ot_insert_css_with_markers_fallback

### ISSUE THREAD

**Issue by CapitalH** [valendesigns/option-tree#501]
Hi

After upgrading the OT to it's latest version my theme became a mess since most of the options were not designed to be used via the inherit fallbacks added in the recent version of OT.

Reading the changelog I also realized there is a filter to eliminate these fallbacks. I would like to disable it completely. How can I use this filter to do it?

**Comment by valendesigns** [comment]
Have you looked at the source code where the filter is?

**Comment by CapitalH** [comment]
Yes I have, but my knowledge of filters is intermediate. A code example would help me alot realizing how to use other filters too.

**Comment by valendesigns** [comment]
I believe this should do the trick. Let me know.

`add_filter( 'ot_insert_css_with_markers_fallback', '__return_empty_string' );`

**Comment by CapitalH** [comment]
Yes it does the trick, As always, thank you very much.

**Comment by valendesigns** [comment]
No worries. 😃
