### ISSUE TITLE
use Category Checkbox in query

### ISSUE THREAD

**Issue by mahdi-alavi** [valendesigns/option-tree#502]
Hi, 
how can use Category Checkbox in query
in theme theme-options:
`
array(
'id'          => 'news_last',
'label'       => __( 'Category Checkbox', 'theme' ),
'desc'        => '',
'type'        => 'category-checkbox',
'section'     => 'news',
'operator'    => 'and'
), 
`
in page:
`
$newsLast = ot_get_option( 'news_last' );
$news = new WP_Query( array( 'post_type' => 'post', 'cat' => $newsLast, 'post_status' => 'publish', 'posts_per_page' => '7' ) );
if( $news->have_posts() ) : while( $news->have_posts() ) : $news->the_post(); 
`
thanks

**Comment by valendesigns** [comment]
`print_r($newsLast);` and/or `var_dump($newsLast)` and see what comes out.

**Comment by mahdi-alavi** [comment]
Array ( [157] => 157 [6] => 6 )

**Comment by valendesigns** [comment]
What do the docs say about cat, does it accept an array or string?

**Comment by mahdi-alavi** [comment]
@valendesigns 
Excuse! i dont know, but see this
https://codex.wordpress.org/Class_Reference/WP_Query
category__and (array) - use category id.

**Comment by valendesigns** [comment]
Use `category__in` instead of `cat`. If you used `category__and` then it would need to match all the IDs.

**Comment by mahdi-alavi** [comment]
thanks very mach!
it's work

**Comment by valendesigns** [comment]
No problem! Glad to help.
