### ISSUE TITLE
Question about option tree layout

### ISSUE THREAD

**Issue by Theme20** [valendesigns/option-tree#503]
Hi,

Hope you're doing well, I've created some different layout via option tree New Layout bar, Is there any way to get one layout on page1 and another layout on page2 ?!

**Comment by valendesigns** [comment]
You could create your own ot_get_option that excepts a third parameter that is a string value that when set pulls the theme options from the layouts array by the key you passed in. And when the key is empty it grabs from the regular theme options array. It would take maybe 3-5 lines of code to make that work.

**Comment by valendesigns** [comment]
Quick and untested.
```PHP
/**
 * Get Option.
 *
 * @param     string    The option ID.
 * @param     string    The default option value.
 * @param     string    The layouts ID.
 * @return    mixed
 */
if ( ! function_exists( 'ot_get_option' ) ) {

  function ot_get_option( $option_id, $default = '', $layouts_id = '' ) {

    /* get the saved options */
    if ( isset( $layouts_id ) && $layouts = ot_layouts_id() && isset( $layouts[$layouts_id] ) ) {
      $options = $layouts[$layouts_id];
    } else {
      $options = get_option( ot_options_id() );
    }

    /* look for the saved value */
    if ( isset( $options[$option_id] ) && '' != $options[$option_id] ) {

      return ot_wpml_filter( $options, $option_id );

    }

    return $default;

  }

}
```

**Comment by Theme20** [comment]
Thanks man, i will try test it.
