### ISSUE TITLE
Display color opacity into link-color option

### ISSUE THREAD

**Issue by BassemN** [valendesigns/option-tree#505]
Hi @valendesigns 
Is there any way to display color opacity into link-color option type?
Thanks

**Comment by valendesigns** [comment]
Have you tried adding the `ot-colorpicker-opacity` to the `class` field?

**Comment by BassemN** [comment]
Thank you very much, It works like a charm.
Is it possible to apply opacity for only one color(Ex. standard color only)?

**Comment by valendesigns** [comment]
Nope, it's a hammer. One or the other, sorry.

**Comment by BassemN** [comment]
Thank you Derek. That's a good effort
