### ISSUE TITLE
Google font option type returning null

### ISSUE THREAD

**Issue by sky4git** [valendesigns/option-tree#506]
Hi,

I have just updated the option tree version in my theme and found out new option type google fonts. 
I am using as like default example. But dropdown remains empty in theme options page.
Any clues?

This is my code:
array(
        'id'          => 'demo_google_fonts',
        'label'       => __( 'Google Fonts', 'theme-text-domain' ),
        'desc'        => '',
        'std'         => array( 
          array(
            'family'    => 'opensans',
            'variants'  => array( '300', '300italic', 'regular', 'italic', '600', '600italic' ),
            'subsets'   => array( 'latin' )
          )
        ),
        'type'        => 'google-fonts',
        'section'     => 'general',
        'operator'    => 'and'
      ),

What I am getting in theme options page is just like below image.
![google font empty dropdown](https://cloud.githubusercontent.com/assets/8438024/7318186/598b628e-eacc-11e4-985e-72691461f55b.PNG)

I am expecting at least opensans in dropdown. Also I am not sure how to add other fonts.
I am also not using any filters. 
Its a child theme mode of genesis framework.

**Comment by johnh10** [comment]
Try it without the std value to load all the fonts. 

                // Google Fonts
                array(
                        'id'            => 'demo_google_fonts',
                        'label'         => __( 'Load Google Fonts', 'theme-text-domain' ),
                        'desc'          => __( 'Load <a target="blank" href="https://www.google.com/fonts">Google Fonts</a> to enable for use in typographies. You must save these values before the Google fonts will display in the typography dropboxes.', 'theme-text-domain' ),
                        'type'          => 'google-fonts',
                        'section'       => 'general',
                ),

**Comment by sky4git** [comment]
Dropdown is still empty. 
Is there anything to do with child theme?
I think that issue has been fixed, but not sure.

**Comment by valendesigns** [comment]
It's more likely then that your server is not allowing the request to Google for the font list, since the drop down is empty.

**Comment by sky4git** [comment]
Its just WAMP local server. 
Can you suggest me which function/file actually loading fonts on server?
I will play around with it and see where is the problem.
Thanks.

**Comment by valendesigns** [comment]
I'm not in my office right now, I'm driving to get breakfast. Look in the source code for the function that gets the fonts list from Google. It's a WP native function, just don't recall which one.

**Comment by sky4git** [comment]
It turns out php_curl extension wasn't enable on the server which was failing font loading request.
Thanks for your help.

**Comment by valendesigns** [comment]
No problem, glad you figured it out.
