### ISSUE TITLE
Upload input and external URL's

### ISSUE THREAD

**Issue by Theme20** [valendesigns/option-tree#507]
Hello dear Derek, 

I have one problem, when i'm adding external URL for MP3 inside upload option, It will automatic remove spaces. 

Example url: domain/this is a good music.mp3

Output or after save: domain/thisisagoodmusic.mp3

So i'm going to use text input instead of upload now.

**Comment by valendesigns** [comment]
If it were uploading the MP3 then WP would fix your url and it would work. However, pasting an external source file could change the url path because it's ran through esc_url. Which would remove the spaces and try and sanitize the path.

**Comment by Theme20** [comment]
Thanks for reply, so i think better way is text input for external url's
