### ISSUE TITLE
Bug when saving page after option tree update

### ISSUE THREAD

**Issue by mcstauer** [valendesigns/option-tree#509]
Hi Option Tree

I updated to WP 4.2 today, and also i updated my plugins.

One plugin i use is for attaching images to categories (plugin: Category Images) and when i save a category image i get this error
## ISSUE

Warning: Invalid argument supplied for foreach() in /var/www/www.plh.dk/www/wp-content/plugins/option-tree/includes/ot-functions-admin.php on line 5808

Warning: Cannot modify header information - headers already sent by (output started at /var/www/www.plh.dk/www/wp-content/plugins/option-tree/includes/ot-functions-admin.php:5808) in /var/www/www.plh.dk/www/wp-includes/pluggable.php on line 1196

Any idea on how to resolve this?

Thanks
Johan

**Comment by valendesigns** [comment]
My best guess, it sounds like the plugin you use is saving images via AJAX and including the the WP environment the wrong way. I can't be certain, but in any case I don't think this is an issue with OT but the way that plugin saves data. Is it a free plugin that I can download and test?

**Comment by mcstauer** [comment]
Hi again

Thanks for your answer. I will have another look and see if the error is
only related to images.

Yes the plugin is free and called "Category Images".

/Johan



On Mon, Apr 27, 2015 at 3:21 PM, Derek Herman <notifications@github.com>
wrote:

> My best guess, it sounds like the plugin you use is saving images via AJAX
> and including the the WP environment the wrong way. I can't be certain, but
> in any case I don't think this is an issue with OT but the way that plugin
> saves data. Is it a free plugin that I can download and test?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/valendesigns/option-tree/issues/509#issuecomment-96650540>
> .
>



-- 

-- 
Johan Staureby
Mob: 26744707
