### ISSUE TITLE
Issue with zero value for certain option types

### ISSUE THREAD

**Issue by BassemN** [valendesigns/option-tree#510]
Dear Derek,
Spacing option type doesn't accept **0** value for top, right, bottom or left.
Please advise

**Comment by valendesigns** [comment]
So it's not allowing a `0` value? I guess then you would have to set it manually if it returns empty to `0` in the meantime.

**Comment by valendesigns** [comment]
This has happened before with other settings. I'll look into a fix for 2.6.0 though I'm not sure when it will be coming out. Right now I'm rebuilding my website and then next week I'm going to LoopConf. If you can find a solution I can release a hotfix though. I just don't have the time right this moment to do it. Sorry.

**Comment by BassemN** [comment]
I'll try to fix it and push it to `wip` branch

**Comment by BassemN** [comment]
@valendesigns Kindly check this pull https://github.com/valendesigns/option-tree/pull/511

**Comment by BassemN** [comment]
@valendesigns Kindly check this PR https://github.com/valendesigns/option-tree/pull/512
