### ISSUE TITLE
Files uploaded to Grid view are attached to Media post instead of unattached

### ISSUE THREAD

**Issue by earnjam** [valendesigns/option-tree#514]
Option Tree is causing files uploaded from the grid view under Media to be attached to the private Media post in the `option-tree` post type instead of being unattached as expected. 

This does not occur on the list view. 

It appears to be due to the function `shortcode` in `ot-loader.php` filtering the `media_view_settings` and adding a post ID when it should be set to 0. 

Putting this snippet at the beginning of that function fixed it, but I'm not sure what it would do to the gallery stuff because I haven't tested that:

    global $pagenow;
    if ( 'upload.php' == $pagenow ) {
        return $settings;
    }

**Comment by valendesigns** [comment]
Nice catch. I'll look into it. Thanks!

**Comment by valendesigns** [comment]
This code doesn't have any effect on the gallery shortcode, as far as I can tell. From my quick tests everything still works as expected. Thanks for contributing this fix, it's been added to the next hotfix release coming out today. Cheers!
