### ISSUE TITLE
How can I load google web fonts in theme

### ISSUE THREAD

**Issue by ashraf92** [valendesigns/option-tree#516]
Great plugin by the way . I was playing with it and I can not load google font family. 
Does it work like this @import url('http://fonts.googleapis.com/css?family=Open+Sans');. Or it is done automatically?

**Comment by gerardbm** [comment]
Create a new google fonts option type. If you configure a default value, it will be inserted automatically in the head of your site. If not, simply open your options page, select a font and save the options. You can insert a lot of fonts, and the URL will be inserted automatically in the head. Finally, of course, you need to put the values selected in your dynamic CSS.

**Comment by ashraf92** [comment]
That's what I need to know...it will be automatically in the head
