### ISSUE TITLE
Best way to contribute?

### ISSUE THREAD

**Issue by ryanlabelle** [valendesigns/option-tree#517]
What's the best way to contribute to this plugin? We've created a theme using it for theme options and also a page builder via meta boxes. It's worked out pretty well.

**Comment by valendesigns** [comment]
Hey @ryanlabelle,

This repo needs some love & attention and to be modernized with tools like Grunt & Travis CI before any new features are added. So if you want to contribute I would suggest fixing bugs before working on features until 2.6.0 is released. You can start by creating pull requests against the WIP branch.  This article covers my basic git workflow.

http://nvie.com/posts/a-successful-git-branching-model/

P.S. Sorry for the long delay I've been working on the WordPress core lately and things have been hectic.
