### ISSUE TITLE
Create dynamic.css file upon saving options for the first time.

### ISSUE THREAD

**Issue by human-a** [valendesigns/option-tree#521]
Hi

Is there someway to create the dynamic.css file automatically when the options are being saved for the first time and if the dynamic.css file does not exist?

I have already tried this code to do it upon theme activation but it does not work

``` php
add_action("after_switch_theme", "cfw_create_dynamic_css_file",10 , 2);
function cfw_create_dynamic_css_file() {
    fopen("dynamic.css", "r+");
}
```

tried this one too

``` php
if ( is_admin() && isset( $_GET['activated'] ) && $pagenow == 'themes.php' ) add_action( 'init', 'cfw_create_dynamic_css_file', 1 );
```

none of these seem to doing what I want them to do. Is there a callback function (action) when the options are saved? Or is it something I am doing wrong in the codes above?

The idea is that when I publish a theme on themeforest, when the user installs my theme for the first time everything is ok, they are dealing with an empty dynamic.css file where they can write their options, the problem is when an update is published for the theme, the empty dynamic.css file replaces their file and they lose their customization until they go back to their options panel and save their options again. This causes lots and lots of support tickets for the panicked clients thinking they have lost their changes.

**Comment by valendesigns** [comment]
You would need to create a check for the filesystem credentials so you could create the file and then subsequently write to it when updated. I started working on that concept in a branch but didn't get very far with it.

**Comment by CapitalH** [comment]
@valendesigns So it's not going to be an easy task I guess. I'm still trying with no success, I hope someone would come up with a solution.
