### ISSUE TITLE
Accordion option type

### ISSUE THREAD

**Issue by stefusilviu** [valendesigns/option-tree#522]
Hi Derek. What about adding an Accordion option type as an alternative for Tabs? Let's say I need to add general settings for all my shortcodes. I have a general tab called "Shortcodes" and then a sub-tab for each shortcode containing 2-5 settings. If I have a lot of shortcodes, I'll need plenty of tabs on the page head which is bad for small screens. Having all shortcode settings listed without tabs (or other solution) is not an option as the page will become a skyscrapper.

I thought that this feature can help us and should be pretty easy to add it using the jQuery UI and the styles from the list items.

What do you think?
Thanks!

**Comment by valendesigns** [comment]
Sounds good, but I don't have the time to do it. Sorry.
