### ISSUE TITLE
Q: OT and wordpress customizer

### ISSUE THREAD

**Issue by Codevz** [valendesigns/option-tree#523]
Hello, 

What is best way for using / adding optiontree types in WP customizer ?! for example i want add list-items to wp customizer, how can i do it ?! 

Thanks.

**Comment by BassemN** [comment]
Hi @valendesigns 
Is there any simple way to add some OT types to live customizer until you officially support it?
Thanks

**Comment by valendesigns** [comment]
There is nothing simple about making some of these option types customizer controls. So, short answer no. Sorry.
