### ISSUE TITLE
Enqueue global_admin_css only when needed

### ISSUE THREAD

**Issue by devinsays** [valendesigns/option-tree#525]
I was doing a theme review for .org and noticed that the output of global_admin_css was appearing on every page of the admin, even though it didn't appear to be needed.

I'm guessing this is enqueued for folks who use Options Tree as a top level menu item (in which case it does need to be one every page), but if it's under the "Appearance" menu I don't believe you would need to load all that. Is it possible to do a check, and only enqueue global_admin_css when it will actually be used?

**Comment by valendesigns** [comment]
Yeah. I'll look into a better solution. The issue is knowing when meta boxes need the styles in different post types or you create a custom admin page which are all dynamic. Though I'm sure there's a fix as that code is really old. Thanks for the bug report.
