### ISSUE TITLE
error when i update or create au new article

### ISSUE THREAD

**Issue by raphaelBF** [valendesigns/option-tree#526]
Hello 
Thank's for your superb plugin !!!
But i have an issue i cant resolv in a theme i'd maked. :(

I don't know what's wrong but when i click to update a article i have this warning message 

Warning: Invalid argument supplied for foreach() in /plugins/option-tree/includes/ot-meta-box-api.php on line 255

ps : my wordpress and the plugin are updated

**Comment by sabbirk15** [comment]
I think you are using optiontree as theme mode. If so be sure to register the metabox after  Initialize the custom Theme Options.

It should solve your problem.

**Comment by raphaelBF** [comment]
Yes i'm in theme mode, so i code my own options and dont use the plugin as a plugin  drag and drop in the admin.

But i register the metabox at the end of the function as it is said in the demo source code...like that :
 function _custom_meta_boxes(){

    /**
     * Create a custom meta boxes array that we pass to
     * the OptionTree Meta Box API Class.
     */

	   $slide_meta_box =  
	 array(
      'id'          =>  'Slider',
      'title'       =>  'Options du slide',
      'desc'        =>  '',
        'pages'       => 'Slider',
        'context'     => 'normal',
        'priority'    => 'high',
        'fields'      => array(
            
          
			array(

			'label'       => __( 'Nom', 'theme-text-domain' ),
			'id'          => THEME_PREFIX .'_nom',
			'type'        => 'text',
			//'desc'        => __( 'This is a demo Textarea field.', 'theme-text-domain' )
				),
				
			array(

			'label'       => __( 'Pays', 'theme-text-domain' ),
			'id'          => THEME_PREFIX .'_pays',
			'type'        => 'text',
			//'desc'        => __( 'This is a demo Textarea field.', 'theme-text-domain' )
				),
			
			array(

			'label'       => __( 'Lien', 'theme-text-domain' ),
			'id'          => THEME_PREFIX .'_lien',
			'type'        => 'text',
			//'desc'        => __( 'This is a demo Textarea field.', 'theme-text-domain' )
				)
				
				
				));
    $references_meta_box =  

	

	array(
      'id'          =>  'hotels',
      'title'       =>  'Options de l\' hotel',
      'desc'        =>  '',
        'pages'       => 'hotels',
        'context'     => 'normal',
        'priority'    => 'high',
        'fields'      => array(
            
           
			array(

			'label'       => __( 'Quand partir', 'theme-text-domain' ),
			'id'          => THEME_PREFIX .'_quand',
			'type'        => 'textarea',
			//'desc'        => __( 'This is a demo Textarea field.', 'theme-text-domain' )
				),
			array(

			'label'       => __( 'Complément météo', 'theme-text-domain' ),
			'id'          => THEME_PREFIX .'_meteo',
			'type'        => 'textarea',
			//'desc'        => __( 'This is a demo Textarea field.', 'theme-text-domain' )
				),
			array(

			'label'       => __( 'RW adore', 'theme-text-domain' ),
			'id'          => THEME_PREFIX .'_adore',
			'type'        => 'textarea',
			//'desc'        => __( 'This is a demo Textarea field.', 'theme-text-domain' )
				),
			array(

			'label'       => __( 'Hébergement', 'theme-text-domain' ),
			'id'          => THEME_PREFIX .'_hebergement',
			'type'        => 'textarea',
			//'desc'        => __( 'This is a demo Textarea field.', 'theme-text-domain' )
				),
				
			array(

			'label'       => __( 'Situation', 'theme-text-domain' ),
			'id'          => THEME_PREFIX .'_situation',
			'type'        => 'textarea',
			//'desc'        => __( 'This is a demo Textarea field.', 'theme-text-domain' )
				),
				
			array(

			'label'       => __( 'Activités/Interets', 'theme-text-domain' ),
			'id'          => THEME_PREFIX .'_activites',
			'type'        => 'textarea',
			//'desc'        => __( 'This is a demo Textarea field.', 'theme-text-domain' )
				),
			array(

			'label'       => __( 'Infos SUPP', 'theme-text-domain' ),
			'id'          => THEME_PREFIX .'_infos_supp_txt',
			'type'        => 'textarea',
			//'desc'        => __( 'This is a demo Textarea field.', 'theme-text-domain' )
				),
			
			array(

			'label'       => __( 'baseline', 'theme-text-domain' ),
			'id'          => THEME_PREFIX .'_baseline',
			'type'        => 'text',
			//'desc'        => __( 'This is a demo Textarea field.', 'theme-text-domain' )
				),
						array(

			'label'       => __( 'adresse web de l\'hotel', 'theme-text-domain' ),
			'id'          => THEME_PREFIX .'_wwww',
			'type'        => 'text',
			//'desc'        => __( 'This is a demo Textarea field.', 'theme-text-domain' )
				),
			
			array(

			'label'       => __( 'Adresse email de réservation', 'theme-text-domain' ),
			'id'          => THEME_PREFIX .'_email_resa',
			'type'        => 'text',
			//'desc'        => __( 'This is a demo Textarea field.', 'theme-text-domain' )
				),
				
		 array(
                'label'     =>  'Hotel Type',
                'id'        =>  THEME_PREFIX . '_hotel_type',
                'type'      =>  'select',
                'desc'      =>  'Option type hotel',
                'std'       =>  'none',
                'rows'      => '',
                'post_type' => '',
                'taxonomy'  => '',
                'class'     => '',
                'choices'   =>  array(

                    array(
                        'value' => 'slideshows',
                        'label' => 'Slideshows'
                    ),

                ),

            ),

       
            array(
                'label'     => 'Slideshow',
                'id'        => THEME_PREFIX . '_hotel_slideshows',
                'type'      => 'list-item',
                'desc'      => '',
                'class'     => 'hotel-slideshows',
                'settings'  => array(
                    array(
                        'id'        => THEME_PREFIX . '_hotel_slideshow_item',
                        'label'     => 'Image',
                        'type'      => 'upload',
                        'class'     => 'hotel-slideshow-item',
                    )
                )
            ),
			
			
			
			
			
			 array(
                'label'     =>  'Hotel PDF',
                'id'        =>  THEME_PREFIX . '_hotel_pdf',
                'type'      =>  'select',
                'desc'      =>  'Option pdf hotel',
                'std'       =>  'none',
                'rows'      => '',
                'post_type' => '',
                'taxonomy'  => '',
                'class'     => '',
                'choices'   =>  array(

                    array(
                        'value' => 'Pdf',
                        'label' => 'Pdf'
                    ),

                ),

            ),

       
            array(
                'label'     => 'Pdf',
                'id'        => THEME_PREFIX . '_hotel_pdf',
                'type'      => 'list-item',
                'desc'      => '',
                'class'     => 'hotel-pdf',
                'settings'  => array(
                    array(
                        'id'        => THEME_PREFIX . '_hotel_pdf_item',
                        'label'     => 'Pdf',
                        'type'      => 'upload',
                        'class'     => 'hotel-pdf-item',
                    )
                )
            ),
        )
    );
	 
	
								
    ot_register_meta_box( $references_meta_box );
    ot_register_meta_box( $slide_meta_box );
}

**Comment by sabbirk15** [comment]
Try to use something like this 

<?php
add_action( 'after_setup_theme', 'your_metabox_function' );


function your_metabox_function(){
if ( function_exists( 'ot_register_meta_box' ) ) {
		
 $slide_meta_box =  
 array(
  'id'          =>  'Slider',
  'title'       =>  'Options du slide',
  'desc'        =>  '',
    'pages'       => 'Slider',
    'context'     => 'normal',
    'priority'    => 'high',
    'fields'      => array(


        array(

        'label'       => __( 'Nom', 'theme-text-domain' ),
        'id'          => THEME_PREFIX .'_nom',
        'type'        => 'text',
        //'desc'        => __( 'This is a demo Textarea field.', 'theme-text-domain' )
            ),

        array(

        'label'       => __( 'Pays', 'theme-text-domain' ),
        'id'          => THEME_PREFIX .'_pays',
        'type'        => 'text',
        //'desc'        => __( 'This is a demo Textarea field.', 'theme-text-domain' )
            ),

        array(

        'label'       => __( 'Lien', 'theme-text-domain' ),
        'id'          => THEME_PREFIX .'_lien',
        'type'        => 'text',
        //'desc'        => __( 'This is a demo Textarea field.', 'theme-text-domain' )
            )


            ));
$references_meta_box =  



array(
  'id'          =>  'hotels',
  'title'       =>  'Options de l\' hotel',
  'desc'        =>  '',
    'pages'       => 'hotels',
    'context'     => 'normal',
    'priority'    => 'high',
    'fields'      => array(


        array(

        'label'       => __( 'Quand partir', 'theme-text-domain' ),
        'id'          => THEME_PREFIX .'_quand',
        'type'        => 'textarea',
        //'desc'        => __( 'This is a demo Textarea field.', 'theme-text-domain' )
            ),
        array(

        'label'       => __( 'Complément météo', 'theme-text-domain' ),
        'id'          => THEME_PREFIX .'_meteo',
        'type'        => 'textarea',
        //'desc'        => __( 'This is a demo Textarea field.', 'theme-text-domain' )
            ),
        array(

        'label'       => __( 'RW adore', 'theme-text-domain' ),
        'id'          => THEME_PREFIX .'_adore',
        'type'        => 'textarea',
        //'desc'        => __( 'This is a demo Textarea field.', 'theme-text-domain' )
            ),
        array(

        'label'       => __( 'Hébergement', 'theme-text-domain' ),
        'id'          => THEME_PREFIX .'_hebergement',
        'type'        => 'textarea',
        //'desc'        => __( 'This is a demo Textarea field.', 'theme-text-domain' )
            ),

        array(

        'label'       => __( 'Situation', 'theme-text-domain' ),
        'id'          => THEME_PREFIX .'_situation',
        'type'        => 'textarea',
        //'desc'        => __( 'This is a demo Textarea field.', 'theme-text-domain' )
            ),

        array(

        'label'       => __( 'Activités/Interets', 'theme-text-domain' ),
        'id'          => THEME_PREFIX .'_activites',
        'type'        => 'textarea',
        //'desc'        => __( 'This is a demo Textarea field.', 'theme-text-domain' )
            ),
        array(

        'label'       => __( 'Infos SUPP', 'theme-text-domain' ),
        'id'          => THEME_PREFIX .'_infos_supp_txt',
        'type'        => 'textarea',
        //'desc'        => __( 'This is a demo Textarea field.', 'theme-text-domain' )
            ),

        array(

        'label'       => __( 'baseline', 'theme-text-domain' ),
        'id'          => THEME_PREFIX .'_baseline',
        'type'        => 'text',
        //'desc'        => __( 'This is a demo Textarea field.', 'theme-text-domain' )
            ),
                    array(

        'label'       => __( 'adresse web de l\'hotel', 'theme-text-domain' ),
        'id'          => THEME_PREFIX .'_wwww',
        'type'        => 'text',
        //'desc'        => __( 'This is a demo Textarea field.', 'theme-text-domain' )
            ),

        array(

        'label'       => __( 'Adresse email de réservation', 'theme-text-domain' ),
        'id'          => THEME_PREFIX .'_email_resa',
        'type'        => 'text',
        //'desc'        => __( 'This is a demo Textarea field.', 'theme-text-domain' )
            ),

     array(
            'label'     =>  'Hotel Type',
            'id'        =>  THEME_PREFIX . '_hotel_type',
            'type'      =>  'select',
            'desc'      =>  'Option type hotel',
            'std'       =>  'none',
            'rows'      => '',
            'post_type' => '',
            'taxonomy'  => '',
            'class'     => '',
            'choices'   =>  array(

                array(
                    'value' => 'slideshows',
                    'label' => 'Slideshows'
                ),

            ),

        ),


        array(
            'label'     => 'Slideshow',
            'id'        => THEME_PREFIX . '_hotel_slideshows',
            'type'      => 'list-item',
            'desc'      => '',
            'class'     => 'hotel-slideshows',
            'settings'  => array(
                array(
                    'id'        => THEME_PREFIX . '_hotel_slideshow_item',
                    'label'     => 'Image',
                    'type'      => 'upload',
                    'class'     => 'hotel-slideshow-item',
                )
            )
        ),





         array(
            'label'     =>  'Hotel PDF',
            'id'        =>  THEME_PREFIX . '_hotel_pdf',
            'type'      =>  'select',
            'desc'      =>  'Option pdf hotel',
            'std'       =>  'none',
            'rows'      => '',
            'post_type' => '',
            'taxonomy'  => '',
            'class'     => '',
            'choices'   =>  array(

                array(
                    'value' => 'Pdf',
                    'label' => 'Pdf'
                ),

            ),

        ),


        array(
            'label'     => 'Pdf',
            'id'        => THEME_PREFIX . '_hotel_pdf',
            'type'      => 'list-item',
            'desc'      => '',
            'class'     => 'hotel-pdf',
            'settings'  => array(
                array(
                    'id'        => THEME_PREFIX . '_hotel_pdf_item',
                    'label'     => 'Pdf',
                    'type'      => 'upload',
                    'class'     => 'hotel-pdf-item',
                )
            )
        ),
    )
);



ot_register_meta_box( $references_meta_box );
ot_register_meta_box( $slide_meta_box );

}

}	

?>

**Comment by raphaelBF** [comment]
it doesn't change anything...
same warning... :s

**Comment by valendesigns** [comment]
Look at the demo theme and follow that pattern. You need to call the function via a hook, which I believe is init. The OptionTree Theme has metaboxes for you to look at.

**Comment by raphaelBF** [comment]
Yes i call with 
add_action( 'admin_init', 'custom_meta_boxes' );

it's like your demo, but i I have not succeeded to debug...

**Comment by raphaelBF** [comment]
Ok i've searched and found 

In the lasts lines i have two ID which are the same...

     array(
        'label'     =>  'Hotel PDF',
        'id'        =>  THEME_PREFIX . '_hotel_pdf',
        'type'      =>  'select',
        'desc'      =>  'Option pdf hotel',
        'std'       =>  'none',
        'rows'      => '',
        'post_type' => '',
        'taxonomy'  => '',
        'class'     => '',
        'choices'   =>  array(

            array(
                'value' => 'Pdf',
                'label' => 'Pdf'
            ),

        ),

    ),


    array(
        'label'     => 'Pdf',
        'id'        => THEME_PREFIX . '_hotel_pdf',
        'type'      => 'list-item',
        'desc'      => '',
        'class'     => 'hotel-pdf',
        'settings'  => array(
            array(
                'id'        => THEME_PREFIX . '_hotel_pdf_item',
                'label'     => 'Pdf',
                'type'      => 'upload',
                'class'     => 'hotel-pdf-item',
            )
        )
    ),


        'id'        => THEME_PREFIX . '_hotel_pdf',

I changed the second ID and all work fine ;)


Byebye
