### ISSUE TITLE
Options panel is too slow when tabs are used.

### ISSUE THREAD

**Issue by human-a** [valendesigns/option-tree#527]
@valendesigns 

Hi, hope everything is alright with you.

I have recently decided to use the tabs in my options panel but when I use them the panel becomes too slow, takes about 27 to 35 seconds to fully load.

I checked the chrome's profile and realized that 72% of the loading delay is for appending childs, which I guess goes back to the nested tabs.

29573.9 ms72.26 %    -  appendChild

I really need these tabs to organize my options and I only have 1 week of deadline to deliver everything. Is there any way to make it faster?

Here is the chrome profile for loading the options panel:
https://dl.dropboxusercontent.com/u/23845634/CPU-20150524T204526.cpuprofile

Thanks in advance.

**Comment by valendesigns** [comment]
Sorry, I've been gone lately working on many other things. Anyhow, I don't think there is anything that could be done really in regards to this. The whole system needs an overhaul. From the JS to PHP. But I don't have the resources to do that.

**Comment by CapitalH** [comment]
@valendesigns no worries, I understand.

Is there at least some way to cache the options? Any suggestions on that?

**Comment by vburlak** [comment]
@CapitalH found same "bottleneck" in my options, when using tabs.
I think, to try to break each section to a separate page.. (http://stackoverflow.com/a/18745559/1510732)

**Comment by CapitalH** [comment]
@vburlak That's one way to do it, but it still means moving through different pages and might cause confusion for the end user.

@valendesigns How about ajaxifying the options, upon saving I mean. Have you considered adding this functionality to OptionTree?
