### ISSUE TITLE
Color chooser layer not visible

### ISSUE THREAD

**Issue by stamatovic** [valendesigns/option-tree#529]
When clicking on choose color, popup is not visible.
Removing overflow:hidden; from .format-setting shows it but affects the overall form too.
![ot-color-chooser](https://cloud.githubusercontent.com/assets/6067156/7795550/60f26a8c-02d6-11e5-8d65-71871f435177.jpg)

**Comment by valendesigns** [comment]
What version is that?

**Comment by stamatovic** [comment]
2.5.5 but I reverted to 2.5.4 and issue is present too.

**Comment by valendesigns** [comment]
Browser, & OS

**Comment by valendesigns** [comment]
WordPress

**Comment by stamatovic** [comment]
Linux:
Chrome Version 43.0.2357.65 (64-bit)
Firefox 38
Windows:
Chrome 43.0.2357.65
WordPress 4.2.2

**Comment by valendesigns** [comment]
Have you deactivated all other plugins to test for a conflict? The color picker should not be doing that. When you select it, the color picker should push down the content directly below it, not be hidden like it's float isn't being cleared.

**Comment by valendesigns** [comment]
Also, you know you can add opacity to color pickers right? You don't have to relay on a numeric slider.

**Comment by stamatovic** [comment]
You are right. It was the plugin (WP Review). Sorry to report it as an OT issue. I noticed it after OT update and wrongly assumed it is related to OT.
For opacity: I know. Opacity slider value is used when same color is shown as an overlay over other elements. For example, red is used as a solid background and it is transparent when used as overlay over image.
Again, sorry for reporting the wrong issue and thank you for quick reply.
