### ISSUE TITLE
dynamic.css dqueue

### ISSUE THREAD

**Issue by sky4git** [valendesigns/option-tree#530]
Hi,

I was using the theme in which I enqueued the dynamic.css and it worked fine. 
Now I have created another theme which also use option tree plugin in theme mode, but here I am not using theme options or dynamic.css. Somehow, my new theme is still enqueuing the other theme's dynamic.css file? 

I dont understand how could this be possible. I have checked the code and its not been added manually anywhere. 

I am working just local WAMP server, nothing fancy. Also its the same wordpress just two different themes, with their own option tree version inside the theme itself.

Can you through some light on it, why this could be happening?

Thanks in advance.

**Comment by valendesigns** [comment]
This is something I noticed recently and definitely needs to be fixed.

**Comment by valendesigns** [comment]
Are they child themes, is one a child of the other, or are they both parent level themes?

**Comment by sky4git** [comment]
I think this is been resolved now. But I cant recall how I have done it. 
Yes, it was a Genesis child theme(s).

**Comment by valendesigns** [comment]
@sky4git I believe changing the check from `get_template` to `get_ stylesheet` in the `ot_load_dynamic_css` function will solve this for child themes. It would restrict loading the `dynamic.css` file to the theme it was made for and not its children.

**Comment by valendesigns** [comment]
I do have concerns that this change may confuse people who have gotten use to this behavior though. Unfortunately, I'm not sure there is any way to mitigate the breakage from fixing it.
