### ISSUE TITLE
Custom options inside a class

### ISSUE THREAD

**Issue by HenriqueMenegale** [valendesigns/option-tree#533]
Hi,

I managed to get custom options working on OT with the action "ot_option_types_array". But it looks like it only supports isolated functions on my functions.php file. 

I'm currently working on a complex project where all methods are inside a class, there is any way to add a class method on a custom option?

Thank you.

Ps.: Sorry for any bad writing, I'm brazilian and my english is far from perfect. :P

**Comment by valendesigns** [comment]
No, there is not currently or planned support for that feature.
