### ISSUE TITLE
How to remove the Import/Export Layouts sections from Settings page?

### ISSUE THREAD

**Issue by shofer4eto** [valendesigns/option-tree#534]
Using v 2.5.5 in Theme Mode, I have:

add_filter( 'ot_show_new_layout', '__return_false' );

to disable Layouts view, also need a filter to remove the Import Layouts and Export Layouts as I obviously don't want them, just like i have filter for the Settings:

add_filter( 'ot_show_settings_import', '__return_false' );
add_filter( 'ot_show_settings_export', '__return_false' );

How do I remove the Import Layouts and Export Layouts sections from the Settings page?

**Comment by rvpatel** [comment]
@shofer4eto
I have check this one not working "__return_false'" for Import / export section.
Just work for ui and document section.
