### ISSUE TITLE
Google Fonts Issue

### ISSUE THREAD

**Issue by xhive** [valendesigns/option-tree#535]
Google Fonts option type sets wrong values. If you select the webfont "Open Sans" it will return  [font-family] => opensans. This Value wont work within css styles. Should be better  [font-family] => "Open Sans" or at least  [font-family] => open-sans.

**Comment by BassemN** [comment]
Font family value is not designed to be displayed directly. Try to use dynamic.css technique or create a function to parse font families like OT do [here](https://github.com/valendesigns/option-tree/blob/master/includes/ot-functions-admin.php#L3583)
