### ISSUE TITLE
option tree update necessary: step-by-step guide available?

### ISSUE THREAD

**Issue by stef-bosse** [valendesigns/option-tree#536]
1. I downloaded the latest version of OptionTree and unarchive the .zip directory. Should I copy&paste all foulders via ftp?
2. I have to deactivate the plugin on wordpress? When I will to reactive the plugin?
3. After that I have to add below code to the beginning of my functions.php. Now I upload the functions.php via FTP?
   /**
   - Required: set 'ot_theme_mode' filter to true.
     */
     add_filter( 'ot_theme_mode', '__return_true' );

/**
- Required: include OptionTree.
  */
  require( trailingslashit( get_template_directory() ) . 'option-tree/ot-loader.php' );
1.  Where I have to paste the content from demo-functions.php ?
2. The option-tree/ot-loader.php is activ.
3. Sorry, but could you support a step-by-step guide? Thanks!

**Comment by Marinski** [comment]
What do you want to do? If you can't figure how to work with plugin, download Option Tree Theme (google it - first result in search is yours) and browse files there to figure out what is happening. And where files have to be included. You can copy structure from there.

Else copy this at the top of your theme's functions.php after opening php tag

/**
 * Optional: set 'ot_show_pages' filter to false.
 * This will hide the settings & documentation pages. Set it 'true' to have access to docs
 */
add_filter( 'ot_show_pages', '__return_false' );

/**
 * Required: set 'ot_theme_mode' filter to true.
 */
add_filter( 'ot_theme_mode', '__return_true' );

/**
 * Required: include OptionTree.
 */
include_once( 'option-tree/ot-loader.php' );

/**
 * Theme Options
 */
include_once( 'option-tree/assets/theme-mode/demo-theme-options.php' );

NOTE - you may change this path ('option-tree/assets/theme-mode/... .php'), according to where your custom theme-options.php file is located
