### ISSUE TITLE
Custom Fields no Longer Loaded in Backend nor Cleanup Menu Option

### ISSUE THREAD

**Issue by jasperf** [valendesigns/option-tree#537]
Been working on changes for a theme (Humble Shop) on a staging server using option-tree (OptionTree 2.5.4) . Somehow the optionTree cleanup option is no longer loaded in the menu nor is a field for the buy now button. In the child theme we have an extra theme-options.php in the child theme root loaded from its functions.php with `include('theme-options.php');` In that file I do load the button field:

```
 array(
        'id'          => 'hs_slider_button_text',
        'label'       => 'Slider Button Text',
        'desc'        => '',
        'std'         => '',
        'type'        => 'text',
        'section'     => 'slider',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
```

The whole file with custom additions is here: http://pastebin.com/DBCrfruu . Array items are saved this way:

```
/* allow settings to be filtered before saving */
  $custom_settings = apply_filters( 'option_tree_settings_args', $custom_settings );

   if ( $saved_settings !== $custom_settings ) {
    update_option( 'option_tree_settings', $custom_settings );
  }

```

File is initiated this way:

```
$saved_settings = get_option( 'option_tree_settings', array() );


 $custom_settings = array( 
    'contextual_help' => array( 
      'sidebar'       => ''
.......
```

Have there perhaps been changes causing these fields to no longer load?

**Comment by valendesigns** [comment]
I do not know about any buy now buttons, they are not native to OptionTree. However, the clean up script only displays when it needs to. If there aren't any issues with your installs DB then you are not going to see the menu item. Also, use the `list-item` option type instead of the the `slider`, it's what replaced the `slider` and is a best practice. Fundamentally they are the same thing, but I don't support the `slider` option type anymore.

**Comment by jasperf** [comment]
Buy now button is just a text field for that button created with Bootstrap
CSS.  This text field and other additional added fields are no longer
loaded . Not in the theme options and not front end . So could be a
database issue but loading of these fields is a server side coding issue I
think.
Will try to figure out what changed in this Back Budd clone during
development that may have caused this.

**Comment by jasperf** [comment]
I think the current parent theme has fields slightly different from the fields in the current child theme. All were copied by another developer to overwrite all as he was not certain how to add certain fields to an exisstinf sectin. I read here https://github.com/valendesigns/option-tree/issues/402#issuecomment-62241474 how to add a new section and fiellds:
```
array(
		'id'          => 'hs_slider_fontsize',
		'label'       => 'Slider Font Size',
		'desc'        => 'Size for logo text',
		'std'         => '',
		'type'        => 'measurement',
		'section'     => 'slider',
		'rows'        => '',
		'post_type'   => '',
		'taxonomy'    => '',
		'min_max_step'=> '',
		'class'       => '',
		'condition'   => '',
		'operator'    => 'and'
	  ),
	  array(
		'id'          => 'hs_slider_fontgoogle',
		'label'       => 'Slider Body Google Font',
		'desc'        => 'If you decided to use Google Font, just insert the font name here. Leave form blank if you want to use default fonts selected above.',
		'std'         => '',
		'type'        => 'text',
		'section'     => 'slider',
		'rows'        => '',
		'post_type'   => '',
		'taxonomy'    => '',
		'min_max_step'=> '',
		'class'       => '',
		'condition'   => '',
		'operator'    => 'and'
	  ),
	  array(
		'id'          => 'hs_slider_button_text',
		'label'       => 'Slider Button Text',
		'desc'        => '',
		'std'         => '',
		'type'        => 'text',
		'section'     => 'slider',
		'rows'        => '',
		'post_type'   => '',
		'taxonomy'    => '',
		'min_max_step'=> '',
		'class'       => '',
		'condition'   => '',
		'operator'    => 'and'
	  ),
```
to section slider WITHOUT copying all code?
