### ISSUE TITLE
google font option not enqueuing font 

### ISSUE THREAD

**Issue by Sagar37** [valendesigns/option-tree#538]
hi there
I'm using OT in theme mode, google font option showing me added font and as well in typography also but its not enqueuing added fonts in pages and enqueue default .open sans font
```<link rel='stylesheet' id='open-sans-css'  href='//fonts.googleapis.com/css?family=Open+Sans%3A300italic%2C400italic%2C600italic%2C300%2C400%2C600&#038;subset=latin%2Clatin-ext&#038;ver=4.2.2' type='text/css' media='all' />```

here how i added option in theme

```array(
        'id'          => 'demo_oogle_fonts',
        'label'       => __( 'Google Fonts', 'domain' ),
        'std'         => '',
        'type'        => 'google-fonts',
        'section'     => 'sec_3',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ) 

kind regards,
Sagar

**Comment by BassemN** [comment]
Google fonts enqueued from OT had id ```ot-google-fonts-css``` please search for it

**Comment by Sagar37** [comment]
solved !
