### ISSUE TITLE
How to use place holder text in text option-type?

### ISSUE THREAD

**Issue by ah-polash** [valendesigns/option-tree#539]
i'd like to add place holder text in text option-type. How can i use place holder text in text option-type?

**Comment by valendesigns** [comment]
It's not currently possible.

**Comment by ah-polash** [comment]
i got another problem in option tree. 
// Get the value saved for a Page, Post or CPT ( Within the loop )
$spyr_demo_numeric_slider = get_post_meta( $post->ID, 'spyr_demo_numeric_slider', true ); 
Not getting any Numeric value from a Numeric-slider option type using above code at current version... can you plz check it.

**Comment by valendesigns** [comment]
First, always create a new issue. Second, unless the global `$post` is available use `get_the_ID()` instead.

**Comment by ah-polash** [comment]
after use get_the_ID() i getting same problem. Can you plz check?
