### ISSUE TITLE
OptionTree Compatible with WPTouch Pro?

### ISSUE THREAD

**Issue by mdsworks** [valendesigns/option-tree#541]
Hello - I'm working on another designer's existing WordPress site to make it mobile using WPTouch Pro. They have used OptionTree. Am I going about this the right way? I'm having trouble getting it to render correctly. Recreating the site entirely to be responsive isn't an option for the client. This may be beyond my HTML/CSS reach. Thanks.

**Comment by valendesigns** [comment]
Sorry for the delay in responding. Though, I don't know how I could help here either. It's beyond my support capabilities to test and verify other peoples plugins are supported. Have you tried it and did it fail?

**Comment by mdsworks** [comment]
Thank you for responding. I understand it to be a matter of getting custom functions of OptionTree to work within WPTouchPro. The homepage doesn't present at all on mobile through WPTouch (there's an image slider, address, etc. created with OptionTree). I'm not sure what to pull from the OptionTree PHP to place in the functions.php file of the WPTouch mobile theme. I would contact WPTouch, but the account is the original developer's, thus no support. Any quick tips you might have would be helpful! Thanks for your time!

**Comment by valendesigns** [comment]
I have no experience with that plugin so I can be of much help.

**Comment by mdsworks** [comment]
Thanks!
