### ISSUE TITLE
Unable to sort option tree items

### ISSUE THREAD

**Issue by viktorvdriet** [valendesigns/option-tree#542]
Somehow it has become impossible for me to sort items on a page/post even though the settings are correctly set.

All the items get the `not-sortable` class and this happened since version `2.5.5`. If I remove the `not-sortable` in the console sorting works just fine and a AJAX call is even done. 

Did something regarding the sorting change in version `2.5.5` that need changes on my end?

**Comment by valendesigns** [comment]
The `not-sortable` class was introduced in 2.5.2 in this commit https://github.com/valendesigns/option-tree/commit/3a5a1da0f1176c2a34dc5dba116e249919441c92 and should never be added to the markup. Are you sure that it is being added to the lists? What does/should get added is the `option-tree-sortable` class to the unordered list, but only when `not-sortable` is missing from the classes array.

I'm checking this out as I type to verify. Unfortunately, I cannot reproduce the issue.

**Comment by viktorvdriet** [comment]
Thanks for now. I still do not know what the solution is. I downgraded to `2.4.2` what worked originally. I've planned to look into this issue in a later stadium.
