### ISSUE TITLE
Migrating a site with OT used with uploaded images - old path

### ISSUE THREAD

**Issue by vyskoczilova** [valendesigns/option-tree#543]
Hi, 
how to avoid this issue? I have a www with a custom made template which is using option-tree. There is usualy lot of uploaded images with for example with a string:
http://autocadlt.idealab.cz/wp-content/uploads/2015/05/autocad-lt-2016-badge-1024px.jpg

but when I move the site on address http://autocadlt.cz and even if I use Velvet blue url in OT are still old urls. Is there any way how to fix this trouble other way than manually? And why Velvet blue url is not finding them?

**Comment by valendesigns** [comment]
Images can't be migrated.
