### ISSUE TITLE
How to add  gradien filde to the theme option

### ISSUE THREAD

**Issue by bbosa** [valendesigns/option-tree#547]
hi bro this is very cool theme option & i use it in my theme in TF , How to add  gradien filde to the theme option

thanks ,

bbosa-themes
http://themeforest.net/user/bbosa-themes

**Comment by valendesigns** [comment]
You would need to create a new option type that has multiple color pickers and settings to achieve your goal. Look at other option types, there is a pattern on how things work.

**Comment by bbosa** [comment]
Hi valendesigns thanks for your replay ,
i try this & i get no luck to get it work if you can make small options type for me i will be very happy 

thanks have nice day/night
