### ISSUE TITLE
Internal Server Error when saving theme options

### ISSUE THREAD

**Issue by clairedouglas** [valendesigns/option-tree#548]
Hello, 

We have recently purchased this theme: http://themeforest.net/item/idstore-responsive-multipurpose-ecommerce-theme/4792186 

When we save the theme options, we get an internal server error. 

The error log shows this:

[Wed Jul 29 20:26:16 2015] [warn] [client 217.137.225.85] (104)Connection reset by peer: mod_fcgid: error reading data from FastCGI server, referer: http://justincase.consil.co.uk/wp-admin/admin.php?page=ot-theme-options
[Wed Jul 29 20:26:16 2015] [error] [client 217.137.225.85] Premature end of script headers: options.php, referer: http://justincase.consil.co.uk/wp-admin/admin.php?page=ot-theme-options
[Thu Jul 30 12:18:15 2015] [warn] [client 80.82.113.220] (104)Connection reset by peer: mod_fcgid: error reading data from FastCGI server
[Thu Jul 30 12:18:15 2015] [error] [client 80.82.113.220] Premature end of script headers: wp-cron.php

Could this be caused by the OptionTree plugin?

Thank you. 
Claire.

**Comment by valendesigns** [comment]
It�s most likely a server permissions issue when writing the dynamic CSS file. What host are you using?

**Comment by clairedouglas** [comment]
We are using 34sp.

**Comment by valendesigns** [comment]
Sorry, I�ve never heard of it. Try changing the permissions of the dynamic.css file.

**Comment by valendesigns** [comment]
Were you able to change the file permissions?

**Comment by clairedouglas** [comment]
We are running FastCGI so file permissions don't come into it. Our host changed a couple of server settings which got it working. Thank you for your help.
