### ISSUE TITLE
Metabox Textarea WYSIWYG

### ISSUE THREAD

**Issue by anteksiler** [valendesigns/option-tree#55]
When I try to add a textarea using the below code:

```
array(
    'label'       => 'Page Splash Text',
    'id'          => 'page_splash',
    'type'        => 'textarea',
    'desc'        => 'This is the html to be shown on top of pages. You can use your shortcodes or html.',
    'std'         => '',
    'rows'        => '4'
  ),
```

This does not display the WYSIWYG buttons.

**Comment by ruturaaj** [comment]
I have added a new control to Option Tree framework. It's the integration of SummerNote editor control. The new Field Type is "editor" which also shows and works good in Metaboxes. Here is the screenshot of editor in Metabox:

http://prntscr.com/hknx48

Added few more enhancements to default Option Tree, but currently testing my code. Once found error-free, I will surely publish my version. In the meantime, if anyone is interested, ping me here with your Email and I will send you my version in ZIP file.
