### ISSUE TITLE
Any way we can add text to option-tree-sub-header?

### ISSUE THREAD

**Issue by anteksiler** [valendesigns/option-tree#552]
I am hiding the Layout selection using:

    add_filter( 'ot_show_new_layout', '__return_false' );

But, I would also like to add html in its place.

**Comment by valendesigns** [comment]
The only action that is in the area you are trying to change is `ot_header_list`, though you would need to wrap the items with `li` so they don't break the OT header layout. What are you trying to add?

**Comment by anteksiler** [comment]
Hi @valendesigns, thanks for the reply. I am trying to add couple of links such as our support forum, etc.

**Comment by valendesigns** [comment]
Oh, then the hook I mentioned would be perfect for that.

**Comment by anteksiler** [comment]
Thanks for the help @valendesigns, I was actually asking for the bar underneath the header, but this works as well :)

**Comment by valendesigns** [comment]
Technically the layout control is not in that markup either. It's moved with CSS.

**Comment by anteksiler** [comment]
Anyway I can do that as well? Maybe I can add some links and move append with javascript to #option-tree-sub-header

**Comment by valendesigns** [comment]
Sure, you could do whatever you wanted to. JS would probably be the easiest.

**Comment by anteksiler** [comment]
Thanks Derek :)

**Comment by valendesigns** [comment]
Yeah, no worries.
