### ISSUE TITLE
Extending Option-Tree to custom post types 

### ISSUE THREAD

**Issue by francoisw** [valendesigns/option-tree#553]
Hi there,

Is there a way to extend Option Tree to also include custom post types and not only posts?

Kind regards
Francois Wessels

**Comment by BassemN** [comment]
Hello francoisw,
What do you mean by include custom post types?

**Comment by francoisw** [comment]
Hi there,

Thanks for the reply -- we have a home page news category that displays on the front page. Please see the supplied screenshot: http://glui.me/?i=28lx6666oy2cbsl/2015-08-11_at_16.10.png/

We have a custom post type called events which we would also like to include in this list to choose from. Hope that explains it a bit better. 

Kind regards
Francois Wessels

**Comment by valendesigns** [comment]
There is already an option called `Custom Post Type Select` that you can use for this.
