### ISSUE TITLE
Theme Check Errors - add_theme_page()

### ISSUE THREAD

**Issue by korchung** [valendesigns/option-tree#554]
These errors came back suddenly after a using theme check plugin. Refer to https://github.com/valendesigns/option-tree/issues/453 

REQUIRED: ot-settings-api.php. Themes should use add_theme_page() for adding admin pages.
Line 99: $theme_check_bs   = 'add_menu_page';

REQUIRED: ot-cleanup-api.php. Themes should use add_theme_page() for adding admin pages.
Line 82: $theme_check_bs = 'add_menu_page';

**Comment by stamatovic** [comment]
If helps anyone: I removed the warning from theme check by following modification to OT code:
$theme_check_bs = 'add_menu_'.'page';
So just modify the string to be addition of two parts they can't detect on their own on all locations they report it.
