### ISSUE TITLE
Appearance->Theme Options without root admin Option Tree

### ISSUE THREAD

**Issue by gbell12** [valendesigns/option-tree#555]
Is there a proper way to get rid of the Option Tree menu item on the root of the Admin menu (child theme mode)?  I don't want my client messing around in there.  My options are being driven by a theme-options.php, so it's superfluous, right?

Also, can I change the OptionTree text from "Appearance->Theme Options", which already exists in that sub-menu, to something like OptionTree Options?  I didn't have any luck modifying the language files to do this.

**Comment by doitmax** [comment]
Hi,

to remove the "OptionTree" menu item you can add this filter to your child themes functions.php file:

<code>
add_filter( 'ot_show_pages', '__return_false' );  
</pre>

To change the menu item title you can add this filter:

<code>
add_filter( 'ot_theme_options_menu_title', function() { return __('OptionTree Options', 'option-tree'); } ); 
</pre>

Hope that helps :)

**Comment by gbell12** [comment]
Oh beaut!  Works great.  Thanks for that.
