### ISSUE TITLE
Display alt and title attribute of uploaded image in front-end

### ISSUE THREAD

**Issue by IntricatePixels** [valendesigns/option-tree#558]
Hi Derek,

I'm using the 'upload' field that allows users to upload an image that's displayed on the front-end.

The image in the Media library already has alt and title meta data entered and I need to display the alt and title info on the front end as well.

This is what my function looks like at the moment:

```php
function display_products() 
{
	global $post;
	
	$popular_products = get_post_meta( $post->ID, '_popular_products_list', true );
    
    if ( $popular_products )
    {
        echo '<ul>';
        foreach ( $popular_products as $popular_product ) 
        {
            echo '<li>
                    <a href="' . $popular_product['_popular_products_link'] . '" title="' . $popular_product['_popular_products_name'] . '">                       
                        <span class="product-name">' . $popular_product['_popular_products_name'] . '</span>
                        // this is where I need to display alt and title meta data for uploaded image
                        <img src="' . $popular_product['_popular_products_image'] . '" />
                    </a>
                 </li>';
        }
        echo '</ul>';
    }
}

**Comment by doitmax** [comment]
Basically this is not an OptionTree thing but a WordPress.

You need to get the image attachment id from the image upload field, fetch the attachment post and then get the alt and title meta field from it.

<pre>
$attachment = get_post( $attachmentID );
$alt = get_post_meta( $attachment->ID, '_wp_attachment_image_alt', true );
$image_title = $attachment->post_title;
$caption = $attachment->post_excerpt;
$description = $attachment->post_content;
</pre>

This is just a raw example and you need to adjust it to your needs.

Cheers

**Comment by IntricatePixels** [comment]
Thanks @doitmax I will give this one a try today!

**Comment by IntricatePixels** [comment]
I ended up using a similar solution as @doitmax suggested, where I created three function I can call any time I need the attachment's alt text or title.  

```php

/**
 * 
 *  Get attachment id by url (guid)
 *  
 */
function get_attachment_id_from_src ($image_src) {
    global $wpdb;
    
    $query = "SELECT ID FROM {$wpdb->posts} WHERE guid='$image_src'";
    $id = $wpdb->get_var($query);
    return $id;
}

/**
 * 
 *  Get the attachment's alt text
 *  
 */
function get_image_alt($image_url){
    $attachmentid = get_attachment_id_from_src ($image_url);
    $alt = get_post_meta($attachmentid, '_wp_attachment_image_alt', true);

    return $alt;
}

/**
 * 
 *  Get the attachment's title
 *  
 */
function get_image_title($image_url){
    $attachmentid = get_attachment_id_from_src ($image_url);
    $attachment = get_post( $attachmentid );
    $image_title = $attachment->post_title;

    return $image_title;
}
```

Then you would get the alt or title in an image like this (in this example I'm looping through a list item, so the data is stored in the $data array:

```html
<img src="<?php echo $data['_image_url'] ?>" alt="<?php echo get_image_alt( $data['_image_url'] ) ?>" title="<?php echo get_image_title( $data['_image_url'] ) ?>" />
```

It would be a nice addition to OptionTree if this was all built in upon image upload. So, you'd have an option to also populate the alt or title tags on the html markup.
