### ISSUE TITLE
SVG Support in image preview after upload

### ISSUE THREAD

**Issue by danimalweb** [valendesigns/option-tree#562]
SVG's are not natively supported supported by WordPress due to security concerns, but I often use a plugin called "SVG Support" as logo files and vairous icons I use are always in SVG format.

SVG are not displayed like other images after being uploaded via the option type "upload".

I've looked at the JS code which neededs to be altered and I was wondering if I created a pull request to add svg previews under the upload field, would you take it?

Any support for this? I know its a little controversal as SVG's can contain js code and are thus a security concern. But hey its 2015 and we should be using vector graphics.

**Comment by YourBusyBee** [comment]
I'd second this request, for sure!

**Comment by valendesigns** [comment]
You can create a PR, though I can't guarantee it will be excepted as-is and may need to be discussed and further modified before merge.
