### ISSUE TITLE
malicious url in readme ( harmless for plugin )

### ISSUE THREAD

**Issue by tjuris** [valendesigns/option-tree#563]
I've noticed that WordFence ( a security plugin ) picks up an URL from the readme.txt to flauntbooks dot com, which is currently listed as a malicious by Google's safe browsing.

Might be a temporary issue on that site and does not affect the plugin in any way, but still annoying. Is there any chance contributor URLs could be slightly obfuscated in markup?

**Comment by phpanos** [comment]
I noticed this as well when scanned with WordFence on my client's site who got hacked.

**Comment by valendesigns** [comment]
I'll remove the url in the next update.
