### ISSUE TITLE
CSS type problem, HTML encodes ">" sign.

### ISSUE THREAD

**Issue by shofer4eto** [valendesigns/option-tree#564]
When adding CSS to a css type field the ">" sign gets HTML encoded so:

#menu > ul > li {

for example becomes:

#menu & gt; ul & gt; li {

which is unexpected behavior.

Thanks in advance!

**Comment by shofer4eto** [comment]
Anyone? 

What good is this field type if it messes up the output in the front end?
Single and double quotes are also html encoded... and they are commonly used for fonts in the font-family rule ...
for example: 

font-family: "Droid Serif";

or content: " ";


Thanks!

**Comment by valendesigns** [comment]
Decode the output.

**Comment by dzeriho** [comment]
> Decode the output.

Hi, decoding the output still shows encoded value in the settings page and CSS processor finds this as an error?

![image](https://user-images.githubusercontent.com/5435570/65140517-03862b80-da0f-11e9-8f4f-047cb7e08183.png)
