### ISSUE TITLE
Option Tree Conflict With MyCurator & PressForward Bookmarklet

### ISSUE THREAD

**Issue by king954** [valendesigns/option-tree#565]
I've spoken to the theme developer and they said the conflict is an issue between the plugin and option tree.  It's the same problem as this one:

https://github.com/valendesigns/option-tree/issues/400

Everything is updated to the newest versions.  I'm running the valenti theme with the most recent option tree and both plugins are up to date.  When I try to use the get it or nominate it bookmarklet I get a blank screen and this error message in my logs.  I can't find a way around this problem.

PHP message: PHP   1. {main}() /home/****_/public_html/wp-content/plugins/pressforward/includes/nomthis/nominate-this.php:0
PHP message: PHP   2. require_once() /home/**_**/public_html/wp-content/plugins/pressforward/includes/nomthis/nominate-this.php:33
PHP message: PHP   3. do_action() /home/****_/public_html/wp-admin/admin.php:168
PHP message: PHP   4. call_user_func_array:{/home/**_***_/public_html/wp-includes/plugin.php:503}() /home/**_**/public_html/wp-includes/plugin.php:503
PHP message: PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, function 'ot_default_settings' not found or invalid function name in /home/******/public_html/wp-includes/plugin.php on line 503

PHP message: PHP   1. {main}() /home/*****_/public_html/wp-content/plugins/pressforward/includes/nomthis/nominate-this.php:0
PHP message: PHP   2. require_once() /home/**_**_/public_html/wp-content/plugins/pressforward/includes/nomthis/nominate-this.php:33
PHP message: PHP   3. do_action() /home/**_**_/public_html/wp-admin/admin.php:168
PHP message: PHP   4. call_user_func_array:{/home/**_**_/public_html/wp-includes/plugin.php:503}() /home/**_**/public_html/wp-includes/plugin.php:503
PHP message: PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, function 'ot_add_xml_to_upload_filetypes' not found or invalid function name in /home/*****/public_html/wp-includes/plugin.php on line 503

PHP message: PHP   1. {main}() /home/*****_/public_html/wp-content/plugins/pressforward/includes/nomthis/nominate-this.php:0
PHP message: PHP   2. require_once() /home/**_**_/public_html/wp-content/plugins/pressforward/
2015/10/06 23:22:32 [error] 16038#0: *120986 FastCGI sent in stderr: "
PHP message: PHP   2. require_once() /home/**_**/public_html/wp-content/plugins/pressforward/includes/nomthis/nominate-this.php:33
PHP message: PHP   3. do_action() /home/*****_/public_html/wp-admin/admin.php:168
PHP message: PHP   4. call_user_func_array:{/home/**_**_/public_html/wp-includes/plugin.php:503}() /home/**_**_/public_html/wp-includes/plugin.php:503
PHP message: PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, function 'ot_modify_layouts' not found or invalid function name in /home/**_***/public_html/wp-includes/plugin.php on line 503

PHP message: PHP   1. {main}() /home/*****_/public_html/wp-content/plugins/pressforward/includes/nomthis/nominate-this.php:0
PHP message: PHP   2. require_once() /home/**_**_/public_html/wp-content/plugins/pressforward/includes/nomthis/nominate-this.php:33
PHP message: PHP   3. do_action() /home/**_**_/public_html/wp-admin/admin.php:168
PHP message: PHP   4. call_user_func_array:{/home/**_**/public_html/wp-includes/plugin.php:503}() /home/****_/public_html/wp-includes/plugin.php:503
PHP message: PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, function 'ot_create_media_post' not found or invalid function name in /home/**_***/public_html/wp-includes/plugin.php on line 503

PHP message: PHP   1. {main}() /home/****_/public_html/wp-content/plugins/pressforward/includes/nomthis/nominate-this.php:0
PHP message: PHP   2. require_once() /home/**_**/public_html/wp-content/plugins/pressforward/includes/nomthis/nominate-this.php:33
PHP message: PHP   3. do_action() /home/****_/public_html/wp-admin/admin.php:168
PHP message: PHP   4. call_user_func_array:{/home/**_**/public_html/wp-includes/plugin.php:503}() /home/****_/public_html/wp-includes/plugin.php:503
PHP message: PHP Fatal error:  Call to undefined function ot_register_meta_box() in /home/**_***/public_html/wp-content/themes

**Comment by valendesigns** [comment]
The get it and nominate it bookmarklet are likely doing Ajax in a way that loads the admin again. I would need copies of the plugins to diagnose the issue.

**Comment by king954** [comment]
These are the plugins:
https://wordpress.org/plugins/pressforward/
https://wordpress.org/plugins/mycurator/

**Comment by valendesigns** [comment]
Old. Closing, comment if it's still a problem.
