### ISSUE TITLE
Two or more default values under a condition

### ISSUE THREAD

**Issue by gerardbm** [valendesigns/option-tree#568]
Hi! I have two skin colors (light and dark) so I would like to have two default values in some colorpickers. A simple solution would be to duplicate all the 'Colorpicker' and 'Colorpicker Opacity' options under a normal condition, like this one:
```php
'condition' => 'color_skin:is(light)',
// OR
'condition' => 'color_skin:is(dark)',
```
But I can't do that in some options: Typography, Background... (Because these options have more values that I don't want to duplicate, obviously).

Is it possible to do that by using a filter?

**Comment by doitmax** [comment]
If i get you right, you want to have fields visible when one of the two conditions matches?

If so, you can do it easily and without filtering by using "operator":

<pre>
array(
	'id' => 'your-field-id',
	'label' => __( 'Your Label', 'option-tree' ),
	'std' => '',
	'type' => 'text',
	'operator' => 'or',
	'condition' => ''color_skin:is(light),color_skin:is(dark)',
),
</pre>

By default the operator is set to <code>'operator' => 'and'</code>

Hope that helps!

Cheers, Dennis

**Comment by gerardbm** [comment]
Hi, @doitmax.

Not exactly. The option will be always visible, but the default value should change according to the skin color. For example, I have this option:

```php
array(
    'id' => 'heading_h3_typo',
    'label' => 'Headings H3',
    'std' => array(
        "font-size" => "20px",
        "line-height" => "24px",
        "font-color" => "",
    ),
    'type' => 'typography',
    'section' => 'font_options',
),
```
It would be nice if the default value of the ```font-color``` property contains two values. For example: if I enable the dark skin, the default color is ```#ccc```, if I enable the light skin, the default color is ```#333```. if I have a saved color on dark skin, get this color, and finally, if I have a saved color under light skin, get this other color.

Moreover, if I change the ```font-color``` value when the dark skin is enabled and I want to restore it, when I press the ```default``` button it only restores the default for the dark skin.

Some premium themes have this option: Avada, Enfold... Excepting that these themes, when you switch the skin it, removes the saved value, recovering the default one. I prefer if the saved value is not removed.

A method would be:
```php
 "font-color" => $color_skin,
```
But I can't get the saved value into the options page (```options.php```) itself:
```php
$color_skin = ot_get_option( 'color_skin', 'light' );
    if ( $color_skin === 'light' ) {
        $color_skin = '#333';
    } elseif ( $color_skin === 'dark' ) {
        $color_skin = '#ccc';
    }
```
I also can separate the colorpickers from the 'Typography' and 'Background' with a filter and duplicate them all (one colorpicker for dark and one colorpicker for light, on every option). But this idea would increase a lot the number of options. The page load is getting worse.

It would be good if it were possible without duplicating the options.

**Comment by gerardbm** [comment]
I close it. The only way is adding some extra Javascript.
