### ISSUE TITLE
Options invading the plugin territory

### ISSUE THREAD

**Issue by gerardbm** [valendesigns/option-tree#570]
Hi! I have some options which are invading the plugin territory (some meta tags, custom post types, share buttons, Analytics ID...), so I would like to separate them in a plugin that creates a new options page.

I'm using OT in theme mode, integrated in the theme. If I change the theme mode to plugin mode, an OT plugin activation will be required after a first theme install. By the other hand, I shouldn't have more than one OT installed at the same time in a single WordPress site.

Is there a way I can achieve this separation of the options? Thanks in advance.
Regards.

**Comment by valendesigns** [comment]
If you want to use OT to build plugin options then I would suggest you install OT as a plugin. Adding option pages is actually pretty easy to do, just look at how the theme options are created for an example.

**Comment by gerardbm** [comment]
Thanks! I will give it a try using the TGM plugin activation.
