### ISSUE TITLE
list-item returning word 'array' instead of list items.

### ISSUE THREAD

**Issue by ericbrockman** [valendesigns/option-tree#573]
So I'm trying to give the option to make a list of features. In my theme-options.php file I have the following code:

`array(
    'id'          => 'feat_list_items',
    'label'       => __( 'List', 'sandl' ),
    'type'        => 'list-item',
    'section'     => 'general'
)`

I'm calling it in the theme like so:

`<?php echo ot_get_option( 'feat_list_items' ); ?>`

The problem is that it just adds the word "array" to the page instead of the list of items I've added using the theme options interface.

Any ideas out there to what I might being doing wrong?

Any help is, as always, greatly appreciated.

thanks!

**Comment by BassemN** [comment]
@ericbrockman This happen because list-item returns an array not a string. use print_r and you will see the entire array
```php
<?php print_r(ot_get_option( 'feat_list_items' )); ?>
```

**Comment by ericbrockman** [comment]
Thanks BassemN, this got me closer. However the page is now returning the array like so:

Array ( [0] => Array ( [title] => list item 1 ) [1] => Array ( [title] => list item 2 ) [2] => Array ( [title] => list item 3 ) [3] => Array ( [title] =>  list item 4 ) ) 

What I'd like is for it just to return the list items, like so:

list item 1
list item 2
list item 3
list item 4

**Comment by BassemN** [comment]
@ericbrockman 
You need to make a simple foreach like the below
```php
<ul>
<?php
$items = ot_get_option( 'feat_list_items' );
foreach ( $items as $item) {
    echo '<li>' . $items['title'] . '</li>';
}
?>
</ul>
```

**Comment by sabbirk15** [comment]
try this....

<?php 
$feat_list_items = ot_get_option( 'feat_list_items' ); 
foreach( $feat_list_items as $feat_list_item ) {
	echo $feat_list_item['title'].'<br>';
}
?>

**Comment by ericbrockman** [comment]
Thanks BassemN, that worked after making a quick change;
From: `echo '<li>' . $items['title'] . '</li>';` to `echo '<li>' . $item['title'] . '</li>';`
