### ISSUE TITLE
Simple conditional to implement code if field has value.

### ISSUE THREAD

**Issue by ericbrockman** [valendesigns/option-tree#574]
I'm sure this is easy, but I'm still learning php. I just want to know how to implement a simple conditional statement that would work like so:

`<?php if (ot_get_option( $id // is set)) : ?>
...do something
<?php endif; ?>`

**Comment by BassemN** [comment]
@ericbrockman 
Try to use
```php
<?php
if( isset( ot_get_option( $id ) ) ) {
// do something
}
?>
```

**Comment by BassemN** [comment]
@ericbrockman 
I advise you to use `!empty` instead of `isset` as the following
```php
<?php
if( !empty( ot_get_option( $id ) ) ) {
// do something
}
?>
```

**Comment by ericbrockman** [comment]
Thanks again BassemN!

**Comment by ericbrockman** [comment]
Hmmm, I must be misunderstanding something because I can't get this to work correctly. I have a element `#home-hero` that I want added to the DOM only if there is a background image option, `#home-hero-bg` set. But `#home-hero` seems to be added to the DOM whether or not the background image option, `#home-hero-bg` set. Here's what I have;

In theme: 
`<?php if( !empty( ot_get_option( 'home-hero-bg' ) ) ) { ?>
    <div id="home-hero"></div>
<?php } ?> `

In theme-options.php:
`array(
      'id'          => 'home-hero-bg',
      'label'       => 'Landing Page Image',
      'desc'        => 'Upload an image to show at the top of your home page.',
      'type'        => 'background'
      'section'     => 'general'
)`

CSS in dynamic.css:
`#home-hero {
    {{home-hero-bg}}
}`

**Comment by BassemN** [comment]
@ericbrockman What is the generated content of dynamic.css file?

**Comment by valendesigns** [comment]
The value of `ot_get_option( 'home-hero-bg' )` is going to be an associative array of values because it's a background option type. So you need to do you check against the keys in that array, not the main associative array which is not going to be empty.
