### ISSUE TITLE
Conditional post format status and chat

### ISSUE THREAD

**Issue by ashraf92** [valendesigns/option-tree#575]
Can I have a text area field for status post format and repeater text field for chat post format?

**Comment by BassemN** [comment]
@ashraf92 I don't think you can make this as the allowed formats gallery, link, quote, video and audio as you can see [here](https://github.com/valendesigns/option-tree/blob/fd8fce859a39645b3525f0ae7de80ba4bfdf5182/includes/ot-post-formats-api.php#L64) I'll create a PR to allow extra post formats so @valendesigns can merge it.

**Comment by BassemN** [comment]
@ashraf92  @valendesigns 
Check this PR https://github.com/valendesigns/option-tree/pull/577 to add support for aside, chat and status post formats meta boxes

**Comment by ashraf92** [comment]
Thank you. Work perfectly for me.

**Comment by BassemN** [comment]
@ashraf92 Great

**Comment by BassemN** [comment]
@valendesigns Can you add this feature to the next version?
