### ISSUE TITLE
OT default fonts option returns the key

### ISSUE THREAD

**Issue by gerardbm** [valendesigns/option-tree#581]
I'm using the following code to get the `font-family` value (Google Fonts and OT default fonts). While Google Fonts option works perfect, OT default fonts option returns the key («times») instead of the value («"Times New Roman", sans-serif»).

```php
if ( ! empty( $body_typo[ 'font-family' ] ) ) {
	$ot_google_fonts = get_theme_mod( 'ot_google_fonts', array() );
	if ( isset( $ot_google_fonts[ $body_typo[ 'font-family' ] ][ 'family' ] ) ) {
		$body .= 'font-family: "' . $ot_google_fonts[ $body_typo[ 'font-family' ] ][ 'family' ] . '";';
	} else {
		// It returns «times» instead of «"Times New Roman", sans-serif»
		$body .= 'font-family: ' . $body_typo[ 'font-family' ] . ';';
	}
}
```
This function `print_r( array_values( $body_typo ) );` outputs:
```html
Array
(
    [0] => #000000
    [1] => times
    [2] => 13px
    [3] => normal
    [4] => normal
    [5] => 400
    [6] => 0em
    [7] => 20px
    [8] => none
    [9] => none
)
```
**EDIT:** for clarifying, it normally works because the `font-family` is ***case insensitive***, so "times" works as it was "Times New Roman". Also, "arial" works as it was "Arial", and so on... But what happens if we want to use some web-safe fonts, like `'verdana' => 'Verdana, Geneva, sans-serif'`, then it only shows `verdana`. Same issue using a filter. To fix it I must use:

```php
'Verdana, Geneva, sans-serif' => 'Verdana, Geneva, sans-serif',
'"Times New Roman", sans-serif' => '"Times New Roman", sans-serif',
```

**Comment by valendesigns** [comment]
Why not just using the `ot_recognized_font_families()` function which would supply both Google & regular fonts, you just need to pass in the setting ID. This is how the `ot_insert_css_with_markers` function builds the dynamic CSS.
```PHP
if ( ! empty( $value['font-family'] ) ) {
  foreach ( ot_recognized_font_families( $marker ) as $key => $v ) {
    if ( $key == $value['font-family'] ) {
      $font[] = "font-family: " . $v . ";";
    }
  }
}
```
