### ISSUE TITLE
Fold Question

### ISSUE THREAD

**Issue by Uranbold** [valendesigns/option-tree#582]
Hello,

Is there are fold option available? I can't find it on Documentation.

Thanks.

**Comment by valendesigns** [comment]
No. What is a fold option?

**Comment by Uranbold** [comment]
Example: 

Option A has True False and if True selected more options will come up. False will disable other options.

Fold means -> Hiding options based on parent option value.

Thanks.

**Comment by doitmax** [comment]
This is called "Condition" in OptionTree. You should check the documentation for it.

**Comment by Uranbold** [comment]
Thanks @doitmax. Sorry for my bad i will check it!
