### ISSUE TITLE
is this possible to freeze first option in Typography field?

### ISSUE THREAD

**Issue by enkhtulga** [valendesigns/option-tree#585]
Hello,
for example: I want to freeze first option that named "font-size" in Typography option type, when i scroll down a lot of options. It means that "font-size" is not scrolling just freeze or locked in first option. Why is this need for me. Because there is undefined field name when i chosen "12px" in there. Field name is not coming up. Is there any solution?
Thanks,

**Comment by valendesigns** [comment]
I'm not sure what you're asking.

**Comment by enkhtulga** [comment]
To keep first option of select visible while you scroll to another options, you can lock first option in Typography option type by freezing or lock. What about it? how to decide it?
