### ISSUE TITLE
Google Fonts Default Value

### ISSUE THREAD

**Issue by Uranbold** [valendesigns/option-tree#587]
Hello,

How to set the std value to Google fonts option type.

I tried it something like this

<pre>'std'         => array(
            'opensans' => array(
                "family" => "Open Sans",
            )),
</pre>
and it's not applied.

Thanks.

**Comment by valendesigns** [comment]
```PHP
'std' => array( 
  array(
    'family'    => 'opensans',
    'variants'  => array( '300', '300italic', 'regular', 'italic', '600', '600italic' ),
    'subsets'   => array( 'latin' )
  )
)
```
