### ISSUE TITLE
Child Theme – Call to undefined function ot_settings_id()

### ISSUE THREAD

**Issue by pablopaul** [valendesigns/option-tree#593]
Hello,
I use the Hueman Theme which includes Option Tree in Theme Mode and a according child theme.
In the child theme I want to extend the options like this:

```
function my_ot_setting( $custom_settings ) {

    // Add section
    if ( isset( $custom_settings['sections'] ) ) {
        $custom_settings['sections'][] = array(
            'id'            => 'test_section',
            'title'         => 'Test Section via Child'
        );
    }

    return $custom_settings;

}
add_filter( ot_settings_id() . '_args', 'my_ot_setting');
```

but get the error `Fatal error: Call to undefined function ot_settings_id() in xxx/wp-content/themes/xxx-hueman-child/functions.php on line 34`.

Update: I guess the filter is added earlier then "after_theme_setup" so this is why there is the error. My temporary fix is to to replace the òt_settings_id()` call with the actual settings name, but is no general solution. 

What could be solution to provide the dynamic settings name earlier so that the filter can be added correctly?

**Comment by Web1776** [comment]
Just came across this same issue.

My solution was to define this function in the child theme just before adding the filter:

```php
if ( ! function_exists( 'ot_settings_id' ) ) {
  function ot_settings_id() {    
    return apply_filters( 'ot_settings_id', 'option_tree_settings' );
  }
}

add_filter( ot_settings_id() . '_args', 'my_ot_setting');
...
```

**Comment by pablopaul** [comment]
@Web1776 nice solution, thanks for sharing!

**Comment by valendesigns** [comment]
You have to call OT function inside a hook. Otherwise, they are not available yet.
