### ISSUE TITLE
How to set Default value

### ISSUE THREAD

**Issue by gouravrr** [valendesigns/option-tree#594]
How to set Default value to text option type in Option Tree while theme options customization.
here is the sample code snippete which I used..

array(
        'id'          => 'set_forgot_password_mail_subject',
        'label'       => __( 'Set Forgot Password Mail Subject', 'mailling' ),
        'desc'        => __( 'Here you can set the forgot password mail subject.<br/>Default code is,<br/><strong>Your New Password</strong>' ),
        'std'         => '',
        'type'        => 'text',
        'section'     => 'mails',
        'rows'        => '',
        'post_type'   => '',
        'default'     => 'Your New Password',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and',  
      ),

**Comment by gerardbm** [comment]
To set the default value on each option you must use the `std` field:
```php
'std' => 'Your New Password',
```

**Comment by gouravrr** [comment]
thank you, Its working well.
