### ISSUE TITLE
Is it possible to add math functions to the built in CSS processor?

### ISSUE THREAD

**Issue by ericbrockman** [valendesigns/option-tree#595]
Specifically if I set up an option using color_picker, and apply the user-selected color to elements using the dynamic.css, can I also use that dynamic.css to add an integer to that value?

ex. user-selected color: #cfcfcf (ot_option = link_color)
```
a {
    color:{{link_color}};
}

a:hover {
    color:{{link_color}} + 10;
}
```
So the the hover color would end up being: #d9d9d9

If so can you spell out the proper syntax for doing so? 
Thanks! First WP theme and loving this plugin, so far.

**Comment by valendesigns** [comment]
Sorry, that's not possible. You could setup a second color picker for the hover color though.

**Comment by ericbrockman** [comment]
Ah got it, have other people asked? Especially for use with colors I think math functions would be a great feature.

Thanks for the quick response ;)
