### ISSUE TITLE
theme_options page crashes when textarea field is in use

### ISSUE THREAD

**Issue by annyrams** [valendesigns/option-tree#597]
Hi,
We are using this plugin for a while and works great. We noticed recently the theme_options page crashes ( script taking too long ) when textarea field type is in use. 

I think it has to do with some kind of incompatibility between the TinyMCE and option tree plugin in the new version of wordpress ( 4.4.1 ).

We are on wordpress managed godaddy hosting.

Let me know if you need any additional information.

thanks for the great plugin.
sagar

**Comment by rvpatel** [comment]
@annyrams 
you have using text-area as meta field or list-item?
IF yes so this data saved on serialize format and special character on not added slash so this one break when data get from db.
https://github.com/valendesigns/option-tree/issues/613
