### ISSUE TITLE
Gallery Option Type Issues

### ISSUE THREAD

**Issue by MDSilviu** [valendesigns/option-tree#601]
Hi,

I found a few problems with the gallery type.
On Mozilla Firefox the drag and drop feature doesn't work.
When pressing "Create Gallery" button, the upload media button doesn't show up, and the loading spinner stays on screen, pressing reorder or any other button fixes this problem.
![gallery_loading](https://cloud.githubusercontent.com/assets/5260249/12949813/a0cd7caa-d012-11e5-8ef0-ebee3da7aa51.jpg)

**Comment by valendesigns** [comment]
You need to click add to gallery and add images first.
