### ISSUE TITLE
Notice: Only variables should be passed by reference - PHP 7

### ISSUE THREAD

**Issue by sky4git** [valendesigns/option-tree#607]
I am getting this error on
**\option-tree\ot-loader.php on line 325**

This error is definitely related to PHP 7. I tested the new version with PHP 5.6.16 and it doesn't show up in that. 

I am on Wamp.

**Comment by valendesigns** [comment]
Thanks for reporting the issue. It will be updated in the next release.

**Comment by m-aciek** [comment]
Proposal of resolution can be found here: https://wordpress.org/support/topic/proplem-about-php-notice-only-variables-should-be-passed-by-reference

**Comment by m-aciek** [comment]
For the notice @sky4git mentions, there is an open #614 pull request. Second, analogical pull request #592 is already merged.

**Comment by anteksiler** [comment]
Hi @valendesigns, could you please merge #614 ?

**Comment by valendesigns** [comment]
This is fixed in #695
