### ISSUE TITLE
Meta field for page : "textarea" field display like simple.

### ISSUE THREAD

**Issue by rvpatel** [valendesigns/option-tree#610]
I have creating meta options for selected page with list-items.
I have adding text-area filed now display like simple.
or 
how we remove media options from "text-area" field.

**Comment by sabbirk15** [comment]
I think you should check this thread.... https://github.com/valendesigns/option-tree/issues/55

**Comment by rvpatel** [comment]
@sabbirk15 
Using this function display like WYSIWYG editor

`add_filter( 'ot_override_forced_textarea_simple', '__return_true' );`

**Now how to remove media options (any argument for this) ?**

**Comment by sabbirk15** [comment]
I think I mis understood your question. I think instead of textarea use textarea simple. 

```
 array(
            'id'          => 'demo_list_item_content',
            'label'       => __( 'Content', 'theme-text-domain' ),
            'desc'        => '',
            'std'         => '',
            'type'        => 'textarea-simple',
            'rows'        => '10',
            'post_type'   => '',
            'taxonomy'    => '',
            'min_max_step'=> '',
            'class'       => '',
            'condition'   => '',
            'operator'    => 'and'
          )
```

**Comment by rvpatel** [comment]
![tree-media](https://cloud.githubusercontent.com/assets/5517932/13704004/8c8b3876-e7bf-11e5-8ebd-81f8965f76fb.png)

I wants remove only media button from hear for selected id base.
