### ISSUE TITLE
problem in install

### ISSUE THREAD

**Issue by reuvenlivn** [valendesigns/option-tree#617]
setup twenty fourteen theme (or twenty sixteen...)
download and activate optiontree last version.
refresh the page, got the following:

Fatal error: Cannot unset string offsets in C:\xampp\htdocs\wordpress\wp-content\plugins\option-tree\includes\ot-functions-admin.php on line 616

**Comment by rvpatel** [comment]
U have created any setting for "google-fonts".

**Comment by reuvenlivn** [comment]
No, i did not.
בתאריך 30 במרץ 2016 09:37,‏ "Ravi Patel" <notifications@github.com> כתב:

**Comment by reuvenlivn** [comment]
Hi valendesigns/option-,

I'd like to add you to my professional network on LinkedIn.

- reuven

Confirm that you know reuven: https://www.linkedin.com/e/v2?e=0-in38p2wq-ur&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=Eff7BOVH&invitationId=6127110294591336448








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-in38p2wq-ur&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHCR4y1Pcm8SgAAAVQfec4nmHOYjOw82qoRU5cTgNIe8IwicSqnx1uwEWTxZZQ_DlVaFSoIR3t-c7jlD6tLOLAre-eUaQ1MVQGeHaxz9J4_TT2aqaQXFitbepr_vC4n1Jo0SEAIaKK9LYCtpZAEXBjSTkiPk-_jdFs6C--GaAvvF-qDT-Ve3wnVs2r5tr2ZLx4_&eid=0-in38p2wq-ur


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-in38p2wq-ur&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by reuvenlivn** [comment]
reuven livneh would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-ye5nsi-ina0xa0n-um&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=Eff7BOVH&invitationID=6127110294591336448

View reuven livneh&#39;s profile: https://www.linkedin.com/e/v2?e=-ye5nsi-ina0xa0n-um&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=Eff7BOVH&invitationID=6127110294591336448





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-ye5nsi-ina0xa0n-um&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-ye5nsi-ina0xa0n-um&loid=AQEs-n_T34d0agAAAVQ5Jjzft7iEEX_cpeIAVR5K8UdIIRtKgg46v84JENL8k1KooWUWixanQbqbYmkBSuHs_U9iOGGEEnPqaicKNAr_mrkKZuNyBXlnTVOyQ0ve7LtCLG6iUcM6dYZsHX18YRKhMu5mBLsiC3yek_MWaf9mrTEp6d8Mfh_9GwTKvDU0eukF4q0C

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-ye5nsi-ina0xa0n-um&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by reuvenlivn** [comment]
reuven livneh would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-ye5nsi-ink0wtcp-f5&a=preRegInvite&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=Eff7BOVH&invitationID=6127110294591336448

View reuven livneh&#39;s profile: https://www.linkedin.com/e/v2?e=-ye5nsi-ink0wtcp-f5&a=preRegInvite&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=Eff7BOVH&invitationID=6127110294591336448





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-ye5nsi-ink0wtcp-f5&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=-ye5nsi-ink0wtcp-f5&loid=AQH381ZX83_07gAAAVRcv-gS1GLkkoZjtPY-oW2Ez6-aNTwZAC2CsHbQLoCfHmTf4Lv5YQUqoY0NBNHZoCDrb6cDqF9PabBre8IA672blauMjXpiO669UwCtZWCW5xqV3zgSlee1XOJ0RYrVyF3crxWSNiEIBWwD-5ly7mm1L859k4wuF-6_GSZU1bYDD6euJRbZ

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-ye5nsi-ink0wtcp-f5&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by gerardbm** [comment]
Why do you send him LinkedIn invitations here in a public repository?

**Comment by valendesigns** [comment]
That code has been removed in the new develop version #695
