### ISSUE TITLE
textarea or textarea-simple new line issue on serialization.

### ISSUE THREAD

**Issue by rvpatel** [valendesigns/option-tree#620]
Please fix serialization issue before store data. I have added html formatted address with new lines.

```
<h5>xxxx dsadasd<h5>
<pre>aaaaaaaaa aaaa
bbbbbbbbbbb
csdhakdha djasljd-382415</pre>
```

When i have check database value issue on enter tag (newline).
Why required all text on single line?

**Comment by valendesigns** [comment]
Working fine for me in the new version on the develop branch.
