### ISSUE TITLE
Problem with Google Font - font-family

### ISSUE THREAD

**Issue by canhkieu** [valendesigns/option-tree#623]
In my CSS:

`h1,h2,h3,h4,h5,h6{
    font-family: {{font_heading|font-family}};
    line-height: 125%;
}`

I choosed "Open Sans" font but CSS display:,

 `h1,h2,h3,h4,h5,h6{
    font-family: opensans;
    line-height: 125%;
}`  

How can fix it.

**Comment by Pigrecolab** [comment]
I don't know, I think you can't inside a custom css field... Outside the field you can use:
```
	foreach ( ot_recognized_font_families( $valore ) as $key => $v ) {
                  if ( $key == $valore ) {
                    $retval.= "font-family: " . $v . ";\n";
                  }
                }
```

**Comment by valendesigns** [comment]
The value is stored as the key and not label. So you can't use it in the CSS field unfortunately.
