### ISSUE TITLE
Using OT inside a Custom Post Type's Settings Tab

### ISSUE THREAD

**Issue by StefsterNYC** [valendesigns/option-tree#630]
Hi Derek, or anyone else that may know this. I have a previous OT install on a theme we built awhile back. I've since built a new theme and want to migrate the old OT into a custom post type settings tab. Why? Because I'm already using another options panel. 

So I'm wondering if anyone has ever done this? Thanks.

**Comment by valendesigns** [comment]
I'm not sure what you're asking exactly. I suspect you've moved on as this was a long time ago. If you still need help comment and I'll reopen the issue.

**Comment by StefsterNYC** [comment]
All set. Thanks
