### ISSUE TITLE
PHP Fatal error: undefined function apply_filters() in composer post-update-cmd

### ISSUE THREAD

**Issue by infomaniac50** [valendesigns/option-tree#634]
In my composer.json file I have installed this library. The scripts section runs phpcs to update the installed_paths variable to "../../wp-coding-standards/wpcs".

``` sh
php "vendor/bin/phpcs" --config-set installed_paths ../../wp-coding-standards/wpcs
```

This results in a PHP Fatal error because the function "apply_filters" does not exist.

``` sh
PHP Fatal error:  Uncaught Error: Call to undefined function apply_filters() in /home/derek/workspace/php/option-tree-composer-scripts/vendor/valendesigns/option-tree/ot-loader.php:92
```

I have created a demo to illustrate the problem. I have separated the problem and solution into versions 2.6.0 and 2.6.1. I have also created a pull request to fix the issue. See pull request #633.

You can test the issue yourself by cloning [infomaniac50/option-tree-composer-scripts](https://github.com/infomaniac50/option-tree-composer-scripts). The tag [v2.6.0](https://github.com/infomaniac50/option-tree-composer-scripts/tree/v2.6.0) demonstrates the issue and tag [v2.6.1](https://github.com/infomaniac50/option-tree-composer-scripts/tree/v2.6.1) fixes it with dev-hotfix-2.6.1

**Comment by valendesigns** [comment]
This is fixed in the new version coming soon. It doesn't load OT if WP is not loaded. You can test the PR #695
