### ISSUE TITLE
Possible to add Option Tree metaboxes in nav-menus screen?

### ISSUE THREAD

**Issue by sikandarasr** [valendesigns/option-tree#636]
Hello. 

First of all I want to thank you for this great option builder framework. It works like charm and is very easy to use. 

I got a question for you. Is it possible to add Option Tree metaboxes on nav-menus screen? 

I am trying the following code but it looks like this functionality it not yet available? 

```
$test_meta_box = array(
    'id' => 'mfbmbs',
    'title' => __('Setting', 'text_domain') ,
    'desc' => '',
    'pages' => array(
        'nav-menus'
    ) ,
    'context' => 'normal',
    'priority' => 'high',
    'fields' => array(
```

Any help would be highly appreciated in this regard. 

thanks

Sikandar

**Comment by sikandarasr** [comment]
Alixcan,

thanks for your attention to my question but both of these are completely different. 

My question is not about listing wordpress menus , but rather its about adding custom meta boxes on Wordpress Menu's page.

**Comment by valendesigns** [comment]
No this is not possible AFAIK.
