### ISSUE TITLE
List wordpress menus in Option Tree & Control with On-Off

### ISSUE THREAD

**Issue by alixcan** [valendesigns/option-tree#637]
Hello,

Is there an option for select for created wordpress menus?
that's asked before but self solved https://github.com/valendesigns/option-tree/issues/363

For example,
I had top bar on my theme and i want to add custom menu on it with select box option

i tried to add filter to option theme with custom select box but stucked at this point

``` php
function ot_type_add_custom_option_types( $types ) {
  $menu_Arr = get_terms( 'nav_menu', array( 'hide_empty' => false ) );
  echo '<select>';
  foreach ($menu_Arr as $key) {
  echo '<option value="' . $key->id . '" >' . $key->name . '</option>';
}
  echo '</select>';

}
add_filter( 'ot_option_types_array', 'ot_type_add_custom_option_types' );


```

i can list them but cant save and can control with on - off type 

thank's for your answer and attention.

![screenshot_2](https://cloud.githubusercontent.com/assets/652539/17079066/245a0206-510e-11e6-82d3-d5b3f26a57b8.png)

**Comment by vahabm74** [comment]
hi
How did you solve this problem?
