### ISSUE TITLE
Seperate Pages "Save Changes" Issue

### ISSUE THREAD

**Issue by borademircan** [valendesigns/option-tree#641]
Hello,

I have added multiple admin option pages via OptionTree. However, When a user clicks on "Save Changes", saved values of options which are on other pages are being deleted. I guess the system treats those option fields as empty, during save process.

I also tried to add the options in such a way but it does not save the std value.

``` php
array(
    'id'          => 'option_id',
    'label'       => __( 'Option Name', 'option-tree' ),
    'desc'        => __( 'Option Description.', 'option-tree' ),
    'std'       => ''.get_option('option_id').'',
    'type'        => 'option_type',
    'section'     => 'option_section',
),
```

I also tried:

``` php
'std'         => ''.ot_get_option('option_id').'',
```

but unfortunately it does not work. Any help will be appreciated.

**Comment by valendesigns** [comment]
I'd need to see how all your pages are setup. However, I suspect you moved on. Comment if you want to reopen this.
