### ISSUE TITLE
How to expand total settings number?Settings equal or greater than 82 will not be Saved

### ISSUE THREAD

**Issue by qyouqme** [valendesigns/option-tree#642]
I am developing a theme with too many settings.
I found an issue,when settings equal or greater than 82 the value will not be saved.
ie:the 83th setting's value could't  be saved.

**Comment by valendesigns** [comment]
This is a `max_input_vars` issue. You can see how to fix it here. https://github.com/valendesigns/option-tree/issues/39#issuecomment-17335478
