### ISSUE TITLE
I want retrieve Gallery images inside List Item. How to do that.?

### ISSUE THREAD

**Issue by tobrother** [valendesigns/option-tree#643]
I want retrieve Gallery images inside List Item. How to do that.?

**Comment by Meh0** [comment]
Hello, 

You didn't give details, but this should give you a start. Try this in your template :  
```
<?php 
$gallery_IDs = get_post_meta( $post->ID, **'slug_gallery'**, true );
$gallery_IDs_array = explode(",", $gallery);
?>

<?php if ( $gallery_IDs_array ) : ?>
<ul>
    <?php foreach($gallery_IDs_array as $image_ID) : ?>   
    <li>
    	<?php echo wp_get_attachment_image( $image_ID, 'full' ); ?>
    </li>  
    <?php endforeach; ?>
</ul>
<?php endif; ?>
```
Replace `**'slug_gallery'**` with the id of your gallery. This should work as a basic example. Then adapt to your needs.

Tell me if you need more help.
