### ISSUE TITLE
Compatability with WP version 4.6.1 and higher

### ISSUE THREAD

**Issue by Melbat2015** [valendesigns/option-tree#646]
Is anyone else experiencing compatability issues with version 2.6.0 of OptionTree and WP versions higher than 4.4.5?

**Comment by rvpatel** [comment]
This one 2.6.0 working well in latest version i have using so many site for theme options using theme mode.

**Comment by skip405** [comment]
Using it in the `theme mode` fails for me in beta versions (e.g. 4.7.1, haven't tried it with 4.7.2 yet)

**Comment by valendesigns** [comment]
I've tested the latest version in the develop branch with WP 5.1 and in theme mode and I'm not having any issues.
