### ISSUE TITLE
Request: category-checkbox as hierarchical list

### ISSUE THREAD

**Issue by johnh10** [valendesigns/option-tree#647]
Seems like WordPress get_categories() smushes parent and child categories together in the output as one list. Could you consider a nice hierarchical output instead? 

Best I could find was this snippet, but I hesitate to edit core OT files.

http://snipplr.com/view/60498/wordpress-category-hierarchy/

**Comment by valendesigns** [comment]
Sorry I'm not adding new features to the plugin.
