### ISSUE TITLE
Replace include_once with Native WP function

### ISSUE THREAD

**Issue by anteksiler** [valendesigns/option-tree#650]
OT loader has an include_once function which is soft-rejected by ThemeForest. 

Which native WP function should we use?

**Comment by rvpatel** [comment]
use get_template_part() 
More testing use theme check plugin

**Comment by rvpatel** [comment]
use get_template_part() 
More testing use theme check plugin
or
load_template( trailingslashit( get_template_directory() ) . 'inc/wp_zzyx.php' );
