### ISSUE TITLE
I think this project has been abandoned for some time

### ISSUE THREAD

**Issue by elvishp2006** [valendesigns/option-tree#651]
It has several pull requests without merge or response for a long time, I know it is not easy to maintain a project like this, and I do not know what the owner of the repository is going through, but a lot of people believed in this project, it's not time A fork of this project and move on?

Anyone who has more knowledge about this project would have the courage to keep it? (Sorry my english)

**Comment by wadtech** [comment]
It's a shame, because we used optiontree for a lot of projects. We've started using https://github.com/htmlburger/carbon-fields instead more recently.

**Comment by endy007** [comment]
Exactly what I was thinking about lately.... I have optiontree installed on a lot of clients' WP sites and I would definitely welcome having someone who would be able to solve some of the issues.

**Comment by nash-ye** [comment]
I had started a fork for this plugin:
https://github.com/Arageek/option-tree

Please, report any bugs, or PRs to the new repository.

**Comment by skip405** [comment]
Hi guys, I've also felt the lack of OT support, even in merging PRs (one of them is mine). Sure Derek has got his reasons.

I've recently started my own version of an Option Plugin (from scratch) incorporating the OT ideas + adding my own vision to some of the fields (mainly the Repeater field + multiple WYSIWYGs, etc.) The plugin is in version 0.0.1, so feel free to get it and test it, the first major release will be very soon. The [documentation](https://docs.alchemy-options.com/) is also being written.

https://github.com/AlchemyOptions/AlchemyOptions

The process of setting options up is the same as in OT, so no need to learn a new way.
