### ISSUE TITLE
v4.7 doesn't show the Theme Options page under Appearance (theme mode)

### ISSUE THREAD

**Issue by skip405** [valendesigns/option-tree#654]
Hi Derek and everyone,

Latest Wordpress version (4.7) doesn't seem to show the Theme Options menu page in the Appearance section.
Direct access to `domain.com/wp-admin/themes.php?page=ot-theme-options` results in `Sorry, you are not allowed to access this page.`

The issue is reproduced in the Theme Mode. I haven't tested the Plugin Mode.

**Comment by tobiasharth** [comment]
Same issue with the meta boxes. Can not find the function ```ot_register_meta_box```.

**Comment by Xairoo** [comment]
Works for me on 4.7 without any changes.

I load it this way:

    require_once( get_template_directory() . '/core/theme-options/assets/theme-mode/functions.php' );
    require_once( get_template_directory() . '/core/theme-options/ot-loader.php' );
    require_once( get_template_directory() . '/core/theme-options/assets/theme-mode/theme-options.php' );
    require_once( get_template_directory() . '/core/theme-options/assets/theme-mode/meta-boxes.php' );

**Comment by skip405** [comment]
Never mind, rechecked it once again and found out that I was not doing it in accordance with the `readme.txt`. It all worked for me if I followed the manual.

**Comment by mohdhazwan** [comment]
Sorry @skip405 what did u changed to make it works?

**Comment by skip405** [comment]
@mohdhazwan I moved out the `require` of the `ot-loader.php` from the `after_setup_theme` hook and placed it directly in the `functions.php`. Plugin's readme never states we should use a hook to use in theme mode, and it helped. Good luck
