### ISSUE TITLE
Not working on WordPress v4.7

### ISSUE THREAD

**Issue by ghost** [valendesigns/option-tree#655]
After upgrading to WordPress 4.7 OptionTree is no longer working.

I am using two functions from OptionTree (ot_register_meta_box and ot_get_option). This is an example of how I am using them:

`$metabox_cta = array(
... stuff here
);
if(function_exists('ot_register_meta_box')) {    
        ot_register_meta_box($metabox_cta);
}`

and:

`<a class="navbar-brand" href="<?php echo home_url(); ?>">
                <img src="<?php if(function_exists('ot_get_option')) { echo ot_get_option('logo'); } ?>" alt="Site name">
</a>`

Both of these fail the “function_exists” check and produces no output. They worked just fine on WordPress v4.6.1 though.

This is how I am pulling OptionTree into my theme:

`add_action('after_setup_theme', 'mytheme_setup');
function mytheme_setup() {
    load_theme_textdomain('mytheme', get_template_directory() . '/languages');
    require(trailingslashit(get_template_directory()) . 'option-tree/ot-loader.php');
    require(trailingslashit(get_template_directory()) . 'assets/php/theme-options.php');
    require(trailingslashit(get_template_directory()) . 'assets/php/meta-boxes.php');
	...other stuff`

I am using OptionTree v2.6.0.

Please advise on how to correct this.

**Comment by skip405** [comment]
@martin-siden , I closed [an issue](https://github.com/valendesigns/option-tree/issues/654) yesterday, maybe it can help
