### ISSUE TITLE
Why `$func = 'base64'.'_decode';`?

### ISSUE THREAD

**Issue by darookee** [valendesigns/option-tree#657]
Could you explain why you choose to call functions like [this](https://github.com/valendesigns/option-tree/blob/master/includes/ot-functions-admin.php#L5067)?

I have a compromised WordPress installation to clean up and was searching through the files and almost just deleted this file, but decided to take a closer look. On first glance it could have been a way to hide malicious code.

**Comment by valendesigns** [comment]
It's because people add OptionTree a a package in their theme instead of installing it as a plugin and themes are not allowed to use that function. I've updated that code and made it more clear in the next release #695 coming soon.
