### ISSUE TITLE
Error message after the plugin activation

### ISSUE THREAD

**Issue by juan790** [valendesigns/option-tree#658]
Hello,

I have a premium theme with optiontree default 2.4. When I activated the plugin optiontree 2.6 I have this message:
OptionTree is installed as a plugin and also embedded in your current theme. Please deactivate the plugin to load the theme dependent version of OptionTree, and remove this warning.

What should I do?

Thanks

**Comment by gerardbm** [comment]
Hello, Juan.

It means you have Option-Tree installed twice because your theme is already loading Option-Tree. So you should uninstall the plugin.

You also have the option of removing the embedded Option-Tree of your theme and then use it through the plugin. In this case, make sure you disable it in your `functions.php`:
```php
// Theme Mode
add_filter( 'ot_theme_mode', '__return_false' );

// Show Documentation
add_filter( 'ot_show_docs', '__return_true' );
```

**Comment by juan790** [comment]
Hello, 
thanks for the reply. I want upgrade option-tree to 2.6. So I'll try to make that change. I can copy and paste that code? Thanks.

**Comment by juan790** [comment]
In my function.php (theme child) I set 
`// Theme Mode
add_filter( 'ot_theme_mode', '__return_**false**' );
`
but this code `// Show Documentation
add_filter( 'ot_show_docs', '__return_true' );` is not present.

**Comment by juan790** [comment]
up (sorry for this)

**Comment by skip405** [comment]
You are trying to update Option Tree as a plugin, not as part of your premium theme. Just like @gerardbm told you. You've introduced this problem yourself, it's not an issue with the plugin.

1. Uninstall the plugin you installed
2. Download the latest Option Tree (a zip file)
3. **Back up the current theme** (!!!)
4. Find the old one in your theme and replace all of the files to the new ones
5. Hope that your theme supports the new version

Or (if it's premium) maybe a theme author can help you :)

**Comment by juan790** [comment]
Ok it works! I deleted the old folder "option-tree" and inserted the new folder with FileZilla.
All of the "theme options" settings were unchanged.

Thanks :)
