### ISSUE TITLE
Adding Custom css.

### ISSUE THREAD

**Issue by mtaddia** [valendesigns/option-tree#659]
hi,

i am currently using redux and noticed it output the css inline in the page 

Does OptionTree also output the custom css inline in the page or is there a way to generate a css file for the custom css generated by the options panel?

Is there any benefit to adding the styles inline like this? Usually this is something i would avoid doing so i wanted to ask.

**Comment by halnex** [comment]
I've been wondering the same thing but apparently it doesn't work like Redux Framework.

However, there is a way.

You create your color pickers like you would normally do, then add a CSS field to your options page and inside that, you start assigning the values of the color pickers to your css selectors, like so

```
.copyright {
  background-color: {{footer_copyright_color}};
}
```
Where `{{footer_copyright_ccolor}}` is the ID of the color picker.

You will have to add all the css selectors you want to change inside the CSS field.
