### ISSUE TITLE
Metabox checkbox not working

### ISSUE THREAD

**Issue by FSahinn** [valendesigns/option-tree#662]
Hello, my codes are as follows:

>             array(
>                'id'          => 'yazilim',
>                'label'       => __( 'Kullanılan Yazılım & Diller', 'theme-text-domain' ),
>                'desc'        => __( 'Kullanılan yazılımı veya dilleri buradan seçebilirsiniz.', 'theme-text-domain' ),
>                'std'         => 'wordpress',
>                'type'        => 'checkbox',
>                'operator'    => 'and',
>                'choices'     => array( 
>                    array(
>                        'value'       => 'wordpress',
>                        'label'       => __( 'Wordpress', 'theme-text-domain' ),
>                        'src'         => ''
>                    ),
>                    array(
>                        'value'       => 'html',
>                        'label'       => __( 'HTML', 'theme-text-domain' ),
>                        'src'         => ''
>                    ),
>                    array(
>                        'value'       => 'css',
>                        'label'       => __( 'CSS', 'theme-text-domain' ),
>                        'src'         => ''
>                    ), 
>                )
>            ),  

>                <?php $yazilim = get_post_meta( get_the_ID(), 'yazilim', true );
>                if($yazilim == wordpress):
>                ?>
>                <div class="yazilim wordpress"><i class="fa fa-wordpress"></i>
> <span>Wordpress</span></div>
>                <?php endif; ?>

Despite this, I could not run the code. Can you help me ?

**Comment by ylmylm** [comment]
checkbox yerine list-item kullanın

**Comment by FSahinn** [comment]
@ylmylm list-item kullanıyorum sorun yok. Benim yapmak istediğim checkbox ile 3-4 farklı alan göstermekti ama sanırım olmuyor bu şekilde.

**Comment by ylmylm** [comment]
çalışıyor aslında sadece == yerine != kullanın blocklamak istediğiniz yerine

						   <?php
							$yazilim = get_post_meta( get_the_ID(), 'yazilim', true );
							if($yazilim != 'wordpress'): 
						   ?>
						   <div class="yazilim wordpress"><i class="fa fa-wordpress"></i></div>
						   <?php endif; ?>

**Comment by ylmylm** [comment]
işinize karışmak gibi olmasın amacım sadece size yardımcı olmak.eğer işinize yararsa aşağıdakileri de kullanabilirsiniz

						   <?php 
								$yazilim = get_post_meta( get_the_ID(), 'nt_yazilim', array() );

								foreach( $yazilim as $slide ) { 
									if ( !empty($slide[0] ) ){
										echo '<div class="yazilim '.$slide[0].'"><i class="fa fa-wordpress"></i></div>';
									}
									if ( !empty($slide[1] ) ){
										echo '<div class="yazilim '.$slide[1].'"><i class="fa fa-html"></i></div>';
									}
									if ( !empty($slide[2] ) ){
										echo '<div class="yazilim '.$slide[2].'"><i class="fa fa-html"></i></div>';
									}
								}
							?>		
							
						   <?php 
									$yazilim = get_post_meta( get_the_ID(), 'nt_yazilim', true );

									if ( !empty($yazilim[0] ) ){
										echo '<div class="yazilim '.$yazilim[0].'"><i class="fa fa-wordpress"></i></div>';
									}
									if ( !empty($yazilim[1] ) ){
										echo '<div class="yazilim '.$yazilim[1].'"><i class="fa fa-facebook"></i></div>';
									}
									if ( !empty($yazilim[2] ) ){
										echo '<div class="yazilim '.$yazilim[2].'"><i class="fa fa-twitter"></i></div>';
									}

							?>
