### ISSUE TITLE
Option Tree Clean up Notice on fresh install

### ISSUE THREAD

**Issue by martinetoye** [valendesigns/option-tree#665]
Hi

I'm not sure if I have something wrong of this is standard. 

When I install the theme on a fresh install I seem to be getting the clean up notice but when you click on it its states there is nothing to clean up and then you can click hide. 

Is this a standard function? Or possible I have code wrong somewhere. Could you let me know if its not standard before I begin to look at the code.

If it is standard anyway to hide it for when I publish the theme?

Thanks

**Comment by valendesigns** [comment]
Need more info. This is old, closing it for now. Comment if it's still an issue.
