### ISSUE TITLE
$wpdb->prepare

### ISSUE THREAD

**Issue by Pixelous** [valendesigns/option-tree#667]
Hi,

I received the message from the reviewer:

Please make sure you properly prepare your data for $wpdb.

Please also read 
- http://codex.wordpress.org/Data_Validation#Database 
- http://codex.wordpress.org/Class_Reference/wpdb#Protect_Queries_Against_SQL_Injection_Attacks

Can you take a look if these lines

`$post_ID = $wpdb->get_var( "SELECT ID FROM $wpdb->posts WHERE `post_title` = 'Media' AND `post_type` = 'option-tree' AND `post_status` = 'private'" );`

https://github.com/valendesigns/option-tree/blob/master/includes/ot-functions-admin.php#L900

and

`$attachmentid = $wpdb->get_var( "SELECT ID FROM {$wpdb->posts} WHERE guid='$file'" );`

https://github.com/valendesigns/option-tree/blob/master/includes/ot-functions-admin.php#L1267

should have `$wpdb->prepare` ?

`$post_ID = $wpdb->get_var( $wpdb->prepare( "SELECT ID FROM $wpdb->posts WHERE `post_title` = 'Media' AND `post_type` = 'option-tree' AND `post_status` = 'private'" ) );`

and

`$attachmentid = $wpdb->get_var( $wpdb->prepare( "SELECT ID FROM {$wpdb->posts} WHERE guid='$file'" ) );`

Kind regards,

Anton

**Comment by AlxMedia** [comment]
Got the same message from reviewer. Thanks for sharing the fix.
