### ISSUE TITLE
post_type in Post Select & Post Check Box doesn't work

### ISSUE THREAD

**Issue by Lam-PhanDinh** [valendesigns/option-tree#678]
Hi,
I found this issue when I'm creating WordPress with Option Tree.

When using Option Types is Post Select & Post Checkbox, I'm can't add any post type to those options.

And I tried to resolve it, please see this pull request:

https://github.com/valendesigns/option-tree/pull/677

**Comment by valendesigns** [comment]
Use the Custom Post Type Checkbox and Custom Post Type Select for that.
