### ISSUE TITLE
Colorpicker missing Hex-field

### ISSUE THREAD

**Issue by kekkster** [valendesigns/option-tree#679]
Hi!

The field for hex-color is missing from the colorpicker. Is this a bug or was it removed?
Would really want it back. Is it possible?

I have OptionTree version 2.6.0.

<img width="1308" alt="skarmavbild 2017-11-22 kl 15 00 03" src="https://user-images.githubusercontent.com/6398995/33131150-f40f8cda-cf95-11e7-813b-bb85f0f1129b.png">

**Comment by anteksiler** [comment]
Yeap, this is a new issue with WordPress 4.9

**Comment by shofer4eto** [comment]
+1

**Comment by andy00087** [comment]
I resolved by editing the "ot-admin.css" file to line 2506 and deleting "display: none" in the "hide-color-picker" class.

**Comment by amrikarisma** [comment]
thanks you @andy00087

**Comment by amanhstu** [comment]
@andy00087 Great. That really solved the problem.

**Comment by syntax53** [comment]
thank you @andy00087
