### ISSUE TITLE
This framework hasn't been updated for 2 years

### ISSUE THREAD

**Issue by jitendrabanjara1991** [valendesigns/option-tree#680]
Hi..

I have used option tree and its working fine. But in theme forests its give rejection regarding to option tree updation.  Its give “http://envato.d.pr/mYLMCs/2aoJZdEt this framework hasn’t been updated for 2 years. It is recommended to choose a more updated framework.” this type of error.

Can you update your plugin?

Please give me reply and updated version of your plugin.

Thanks in advance.

**Comment by shofer4eto** [comment]
Same here,

We like our OT plugin, can support be a little more adequate please?

**Comment by jitendrabanjara1991** [comment]
Yes we like your plugin. We can support related to OT.

**Comment by AlxMedia** [comment]
OptionTree is still awesome. It's working perfectly and doesn't really need updating - but it doesn't look good with no updates for 2 years. I'd gladly contribute with CSS fixes if there are any needed ones in a new update.

**Comment by AlxMedia** [comment]
It is still working flawlessly, but a small update would've been nice to keep ThemeForest happy.

**Comment by AlxMedia** [comment]
Here is a small update-fix for the menu focus state:
`
.wrap.settings-wrap .ui-tabs-nav li a:focus { 
  -webkit-box-shadow: none;
     -moz-box-shadow: none;
          box-shadow: none;
}
`

**Comment by ruturaaj** [comment]
Create a fork or separate repo to update it. I have created a separate repo and updated option tree with new field types, columns etc.

**Comment by valendesigns** [comment]
The plugin us being updated you can test the next version in the develop branch in PR #695
