### ISSUE TITLE
Error in Google Fonts with Option Tree Theme Mode

### ISSUE THREAD

**Issue by rafelsanso** [valendesigns/option-tree#682]
Hi!
I have an issue with Google Fonts. I put a simple font selector in my custom_settings variable:

```php
array(
          'id'          => 'main_google_fonts',
          'label'       => __( 'Titles and headers fonts', 'rentshopbike' ),
          'desc'        => sprintf( __( 'The Google Fonts option type will dynamically enqueue any number of Google Web Fonts into the document %1$s. ', 'rentshopbike' ), '<code>HEAD</code>'),
          'std'         => array(
            array(
              'family'    => 'oswald',
              'variants'  => array( '400' ),
              'subsets'   => array( 'latin' )
            )
          ),
          'type'        => 'google-fonts',
          'section'     => 'option_styles',
          'rows'        => '',
          'post_type'   => '',
          'taxonomy'    => '',
          'min_max_step'=> '',
          'class'       => '',
          'condition'   => '',
          'operator'    => 'and'
        ),
```

When I developed the theme, this option works fine, and show the complete list of fonts. But yesterday I migrated the template to a new server. And the selector was blank!
![image](https://user-images.githubusercontent.com/3338672/35779166-0e72da9c-09c9-11e8-839f-262c8eea84bc.png)

I tried to change the API key from Google Apis in the call of the library. But not works.

Any idea? :/

**Note:** It seems that the error comes from using a child theme. When I was change from main Theme to Child Theme, the font dropdown was broken. And it has not worked again. Even if I re-activate the parent theme.

Thank you for your help!

**Comment by victoras** [comment]
+1

**Comment by johnh10** [comment]
Heads up, calls to the Google Fonts API through OptionTree actually are not showing anything because the call

https://www.googleapis.com/webfonts/v1/webfonts?key=OPTIONTREE_KEY&fields=items(family,variants,subsets)&sort=alpha

is returning

> "message": "Project 19383305133 has been scheduled for deletion and cannot be used for API calls. Visit https://console.developers.google.com/iam-admin/projects?pendingDeletion=true to undelete the project.",

So you create your own google API key, enable the Web Fonts Developer API, hook in to OptionTree and replace the old one with yours.

Example:

```
add_filter( 'ot_google_fonts_api_key', 'change_ot_google_fonts_api_key' );

function change_ot_google_fonts_api_key( $key ) {
  return "YOUR_API_KEY";
}
```

**Comment by wp-organic** [comment]
Hello everyone,

Google Fonts issue we fixed. please use this code.


    add_filter( 'ot_recognized_font_families', 'VisaHub_filter_ot_recognized_font_families', 10, 2 );

    function VisaHub_filter_ot_recognized_font_families( $array, $field_id ) {

        $array['helveticaneue'] = "'Helvetica Neue', Helvetica, Roboto, Arial, sans-serif";

        ot_fetch_google_fonts( true, false );

        $ot_google_fonts = wp_list_pluck( get_theme_mod( 'ot_google_fonts', array() ), 'family' );

        $array = array_merge($array,$ot_google_fonts);
      
        if (ot_get_option('typekit_id')) {

            $typekit_fonts = trim( ot_get_option('typekit_fonts'), ' ');
            $typekit_fonts = explode( ',', $typekit_fonts );
            $array = array_merge( $array, $typekit_fonts );
        }
      
        foreach ($array as $font => $value) {
                $thb_font_array[$value] = $value;
        }

        return $thb_font_array;
    }


Thanks -

**Comment by valendesigns** [comment]
You need to create your own Google Fonts API key. The old one is no longer working.
