### ISSUE TITLE
validated for textbox in option tree

### ISSUE THREAD

**Issue by leehaira** [valendesigns/option-tree#684]
How to validated for textbox in option tree, ex: type not include some charactors: ~!@#$%^&*()-_
I try Condition option but not run, please help me validated for textbox, thanks!

**Comment by ruturaaj** [comment]
I think this can only be achieved using jQuery. Option Tree validation will take place only after submission of form (publish/update post or save settings). If you want to disable certain keyboard input keys, it will need to be done through jQuery in real-time. 

Like in this code, the Enter key is disabled... 

`$("input").keypress(function (evt) {

  var keycode = evt.charCode || evt.keyCode;
  if (keycode  == 13) { //Enter key's keycode
    return false;
  }
});`
