### ISSUE TITLE
SuperNeophyte

### ISSUE THREAD

**Issue by SYZYGY-media** [valendesigns/option-tree#686]
inherited OT site. I cannot get OT to move a row in my theme beneath another row. I've moved it in the Theme Options UI Builder. The change shows when I look at it in Appearance->Theme Options. But it does not change on the page. What am I missing. I just trying to move the video section down beneath the first text area http://www.summeratsandyspring.org/.

**Comment by valendesigns** [comment]
Would need a lot more info to troubleshoot this. I assume you figured it out if not leave a comment.
