### ISSUE TITLE
Lose Site When Deactivating Option Tree (on Enfold WordPress Theme)

### ISSUE THREAD

**Issue by help1sos** [valendesigns/option-tree#689]
ive taken over a site that wasnt built by me. i use enfold but the previous developer appears to have used option tree too. i made a bunch of updates to site but its not showing up as planned. when i deactivate the site goes black/everything is gone. when it's active its causing weird formatting with fonts, colors, spacing, wont showed full-width sliders, etc. Please help!

**Comment by valendesigns** [comment]
This is not something that could be fixed without troubleshooting your website.
