### ISSUE TITLE
Enabling ot_child_theme_mode is causing HTTP ERROR 500

### ISSUE THREAD

**Issue by pashata** [valendesigns/option-tree#692]
I'm using The Voux Wordpress theme , it is using OT and i'm trying to enable the child theme mode , i need to add some metaboxes on the custom post types i've created in the child theme ... this is the code i'm using :

`	/* Integrate OptionTree */
	require_once( get_template_directory() . '/inc/admin/option-tree/admin/ot-loader.php' );

	apply_filters( 'ot_child_theme_mode', true );

	$gallery_metabox_gallery = array(
		'id'          => 'post_meta_gallery',
		'title'       => esc_html__('Post Gallery', 'thevoux'),
		'pages'       => array( 'gallery' ),
		'context'     => 'side',
		'priority'    => 'high',
		'fields'      => array(
		  array(
		    'label'       => esc_html__('Post Gallery', 'thevoux'),
		    'id'          => 'post-gallery-photos',
		    'type'        => 'gallery',
		    'desc'        => esc_html__('The image captions will be used as image information on the right side.', 'thevoux')
		  )
		)
	);

	ot_register_meta_box( $gallery_metabox_gallery );`

when i comment out 'ot_register_meta_box' line it works fine , but when it's not commented i'm getting 

lifestyleworld.test is currently unable to handle this request.
HTTP ERROR 500

**Comment by valendesigns** [comment]
You are probably calling the function before it's available. Wrap everything in a hook like so:
```
// Activate child theme mode.
apply_filters( 'ot_child_theme_mode', true );

// Add meta boxes.
add_action( 'admin_init', 'custom_metabox_gallery' );

/**
 * Custom Gallery Meta Box.
 */
function custom_metabox_gallery() {
	$gallery_metabox_gallery = array(
		'id'          => 'post_meta_gallery',
		'title'       => esc_html__( 'Post Gallery', 'thevoux' ),
		'pages'       => array( 'gallery' ),
		'context'     => 'side',
		'priority'    => 'high',
		'fields'      => array(
			array(
				'label' => esc_html__( 'Post Gallery', 'thevoux' ),
				'id'    => 'post-gallery-photos',
				'type'  => 'gallery',
				'desc'  => esc_html__( 'The image captions will be used as image information on the right side.', 'thevoux' ),
			),
		),
	);

	if ( function_exists( 'ot_register_meta_box' ) ) {
		ot_register_meta_box( $gallery_metabox_gallery );
	}
}
```
