### ISSUE TITLE
Is this still supported

### ISSUE THREAD

**Issue by Blenderman18** [valendesigns/option-tree#693]
I just inherited a site that used this to build the site, but it says this was removed from the plugin repository for a security issue? Is this true? Is there an update to it or is this just not supported anymore. Thanks.

**Comment by valendesigns** [comment]
I’m going to patch it in the next week or so. Just trying to find the time.

**Comment by Blenderman18** [comment]
Cool. Thanks for letting me know.

Scott Thornton / Owner/Principal Designer
Blenderhouse Creative
304.995.9270
scott@bhcreative.com
www.blenderhousecreative.com
P.O. Box 4239, Martinsburg, WV 25401

**Comment by valendesigns** [comment]
I'm most of the way through updating to the WordPress Coding Standards and have fixed the security issue that got the plugin taken down. I'm trying to finish it today but we'll see, there's a lot of small changes to make it compliant and very tedious work to say the least.

**Comment by valendesigns** [comment]
Couldn't get it completed fully. I have a few more hours left before I can push everything up for testing. I'm not going to have time again for a couple days. I'll try in the evenings but I have a lot going on this week.

**Comment by Bobraynor2** [comment]
Keep it up man! Your work is appreciated.

**Comment by valendesigns** [comment]
The updates are mostly done. You can test the new version on the develop branch. #695
