### ISSUE TITLE
PHP 7.2 Compatibility

### ISSUE THREAD

**Issue by JustAGuyTryingToCodeSomething** [valendesigns/option-tree#694]
Testing a theme for PHP 7.3 compatibility PHAN reports

`option-tree/includes/ot-functions-admin.php:69 PhanDeprecatedFunctionInternal Call to deprecated function \create_function()
`

Looking it up I see:

```
      // Filters the options.php to add the minimum user capabilities.
      add_filter( 'option_page_capability_' . ot_options_id(), create_function( '$caps', "return '$caps';" ), 999 );
```
And the PHP manual at http://php.net/manual/en/function.create-function.php says it's been deprecated in 7.2.

Thinking of patching with an anonymous function (https://stackoverflow.com/questions/48161526/php-7-2-function-create-function-is-deprecated) for my immediate use, but thought I should flag it so it can be fixed in the main repo.

**Comment by valendesigns** [comment]
This is fixed in the `develop` branch. It will be released soon.
