### ISSUE TITLE
Not working in theme mode

### ISSUE THREAD

**Issue by tsvetipl** [valendesigns/option-tree#705]
Hello I am helping to a friend of mine with her web site, its loo like the developers are udse Oprion tree 2.4.2 but I dont think its function properly. I am not able to add any new items just to edit the existing one. Its installed in theme mode, and also cant see the code in the function.php. I have tried adding the code but then appear a blanck page. The same happend if I install the plugin from the admin back end. Also I am not able to crate any pages to the site or add anything which to function accurate.

**Comment by valendesigns** [comment]
I've responded to this thread over on the .org forums.
